docs(common): add docs about validation
gazprom-neft/consta-uikit pull request #1080
Opened 2021-04-28 10:19 UTC by arhayka

## Описание изменений

Добавила доку про валидацию форм. Взяла из фигмы, немножко переписала (смысл старалась не менять). Добавила кусочек про скрытые подсказки и про то, как не надо писать тексты ошибок.

Картинки не добавляю, просто написала, куда нужно вставить.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-05-17 15:41 UTC, gizeasy requested changes

2021-05-17 15:41 UTC, gizeasy commented on docs/common/validation.mdx
> +<Meta title="Документация|Валидация форм" id="common-validation" parameters={{ order: 305 }} />
Нужно смержится с девом и переименовать файл в validation.stories.mdx

2021-05-19 16:03 UTC, kolebayev approved these changes
Добавил картинки

2021-05-25 10:15 UTC, gizeasy approved these changes

2021-05-25 10:16 UTC, merged