Feat/userselect add
gazprom-neft/consta-uikit pull request #1127
Opened 2021-05-13 06:10 UTC by karpovfv-nedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-05-13 08:53 UTC, gizeasy requested changes

2021-05-13 08:53 UTC, gizeasy commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  getSelectItem: (props: UserSelectItemProps | SelectItemProps) => JSX.Element;
тут лучше оставить только `renderItem?: (item: ITEM) => JSX.Element;` 
и по умолчанию он с использованием компонента `UserSelectItem`

```tsx
 const renderItemDefault = (item: ITEM) => {
    const label = getLabel(item);
    const active
   /// и далее
    return <UserSelectItem label={label} и далее/>;
 };
```

2021-05-13 08:53 UTC, gizeasy commented on src/components/SelectComponents/SelectItem/SelectItem.tsx
> +    item: any;
не используем `any`
дженерики в помошь

2021-05-13 08:53 UTC, gizeasy commented on src/components/User/User.tsx
> +      onIconClick?: (e: React.SyntheticEvent) => void;
onIconRightClick как думаешь? или вообще отовсюду убрать Right

2021-05-13 08:53 UTC, gizeasy commented on src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
> +        {active && <IconCheck className={cnUserItem('CheckIcon')} />}
давай анимацию на появление и исчезнавение иконки прикрутим?
через react-transition-group

2021-05-14 06:16 UTC, karpovfv-nedra commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  getSelectItem: (props: UserSelectItemProps | SelectItemProps) => JSX.Element;
так ведь это дропдаун базового селекта, я думаю ему лучше не использовать по умолчанию UserSelectItem?

2021-05-14 08:20 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
> +        {active && <IconCheck className={cnUserItem('CheckIcon')} />}
анимацию добавил

2021-05-14 08:20 UTC, karpovfv-nedra commented on src/components/User/User.tsx
> +      onIconClick?: (e: React.SyntheticEvent) => void;
да, согласен полностью, лучше назвать `onIconRightClick`, так как iconRight есть

2021-05-14 08:21 UTC, karpovfv-nedra commented on src/components/SelectComponents/SelectItem/SelectItem.tsx
> +    item: any;
добавил дженерик

2021-05-14 08:23 UTC, karpovfv-nedra commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  getSelectItem: (props: UserSelectItemProps | SelectItemProps) => JSX.Element;
я запушил щас изменения по остальным комментам, но опять с ошибками - не соберётся щас.
проблема в том, что компонент `<SelectDropdown ... />` используется помимо UserSelect'a, в BasicSelect, Combobox, MultiCombobox, и в них неохота лезть..

2021-05-14 08:23 UTC, karpovfv-nedra commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  getSelectItem: (props: UserSelectItemProps | SelectItemProps) => JSX.Element;
я если честно пока не знаю, как лучше всего ввести рендер-функцию, чтобы не разрушить существующие компоненты

2021-05-14 13:48 UTC, karpovfv-nedra commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  getSelectItem: (props: UserSelectItemProps | SelectItemProps) => JSX.Element;
обновил

2021-05-17 11:11 UTC, gizeasy commented
Убери стри "с заданным значением"

2021-05-17 11:18 UTC, gizeasy requested changes

2021-05-17 11:18 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +        item={item}
давай компонент нечего не дудет знай об item
пусть просто принимает готовые данные которые нужно по местам в компоненте расставить

2021-05-17 11:18 UTC, gizeasy commented on src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
> +  const { subLabel } = item;
не факт что там будет label так как item неизвестен

2021-05-18 06:44 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelect.tsx
> +        item={item}
`item` убрал из пропсов, прокидываю напрямую `subLabel, url'

2021-05-18 06:45 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
> +  const { subLabel } = item;
так как `item` убрал из пропсов, то `subLabel` сейчас напрямую прокидывается, а он берётся из функции `getUserAdditionalInfo` родительского компонента

2021-05-19 12:05 UTC, gizeasy approved these changes

2021-05-20 10:35 UTC, gizeasy requested changes

2021-05-20 10:35 UTC, gizeasy commented on src/components/BasicSelect/BasicSelect.tsx
>  import { cnSelect } from '../SelectComponents/cnSelect';
удали `index.ts` в компонентах
![image](https://user-images.githubusercontent.com/13190808/118963327-00bfa480-b96f-11eb-8054-961cd184ff18.png)

2021-05-20 10:35 UTC, gizeasy commented on src/components/BasicSelect/BasicSelect.tsx
>  import { cnSelect } from '../SelectComponents/cnSelect';
он совсем не нужен.

2021-05-20 10:35 UTC, gizeasy commented on src/components/BasicSelect/BasicSelect.tsx
> +    const label = getOptionLabel(item as Exclude<typeof value, null | undefined>);
убери приведение к типам, просто типизируй функцию `renderItemDefault` чтоб у нее был дженерик `ITEM`

2021-05-20 11:19 UTC, karpovfv-nedra commented on src/components/BasicSelect/BasicSelect.tsx
>  import { cnSelect } from '../SelectComponents/cnSelect';
удалил

2021-05-20 11:19 UTC, karpovfv-nedra commented on src/components/BasicSelect/BasicSelect.tsx
> +    const label = getOptionLabel(item as Exclude<typeof value, null | undefined>);
убрал приведение

2021-05-25 10:45 UTC, gizeasy requested changes

2021-05-25 10:45 UTC, gizeasy commented on src/components/TagBase/TagBase.css
> +      --user-tag-font-size: var(--size-text-2xs);
Тут от @azhadanov остались не нужные изменения в `TagBase`
верни все пожалуйста как было, если из этого что-то надо было(а кажется что нет), то в компоненте `UserSelect` накинь сверху

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.css
> +  &-Icon {
лучше соблюдать единый нейминг и в js и в css
переименуй в `IconRight`

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.css
> +      background-color: transparent;
а звчем `background-color: transparent;`?

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.css
> +  &-Icon {
Еще можешь добавить в доку: `iconRight`, `onIconRightClick`
и добавить модификацию `withIconRight` в стори

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.css
> +    &_m:not(.user_with-arrow) {
кажется что это не работает уже, разберись зачем оно могло быть тут, если не надо удали

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.tsx
> +          className={cnUser('Avatar', { status })}
в css `-Avatar` ни как не используется, убери пожалуйста `className`

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.tsx
>  export const userPropSizeDefault: UserPropSize = userPropSize[0];
раньше размер по умолчанию был `m` теперь `l`
есть не гласное правило, в массивах значений пропсов первый элемент, это тот который по умолчанию, ну это у нас в проекте

2021-05-25 10:45 UTC, gizeasy commented on src/components/User/User.tsx
>  export const userPropSizeDefault: UserPropSize = userPropSize[0];
т.е. `['l', 'm', 's']` -> `['m', 's', 'l']`

2021-05-25 12:10 UTC, gizeasy requested changes

2021-05-25 12:10 UTC, gizeasy commented on src/components/User/User.tsx
> +  const iconSize = getSizeByMap(iconSizeMap, size);
`iconRightSize`

2021-05-25 12:10 UTC, gizeasy commented on src/components/UserSelect/UserSelectValue/UserSelectValue.css
> +    .Button {
давай разрулим в js
если `_disabled` то не прокидываем `iconRight`и `onIconRightClick`

2021-05-25 12:10 UTC, gizeasy commented on src/components/UserSelect/UserSelectValue/UserSelectValue.css
> +    .User-Block {
тут скорее всего ошибка дизайна, думаю не стоит менять `padding-right`, пусть будет завязан на размер компонента.

2021-05-25 12:10 UTC, gizeasy commented on src/components/UserSelect/UserSelectValue/UserSelectValue.css
> +    .User-Block {
@kolebayev что думаешь?

2021-05-25 12:10 UTC, gizeasy commented on src/components/UserSelect/UserSelectValue/UserSelectValue.tsx
> +      className={cnUserValue({ withCancel, disabled })}
className лучше указывать первым свойством, где это возможно.
Они еще служат для семантического названия, читаешь и понимаешь что за что отвечает

2021-05-25 13:32 UTC, karpovfv-nedra commented on src/components/TagBase/TagBase.css
> +      --user-tag-font-size: var(--size-text-2xs);
да, тут изменения лишние, убрал их

2021-05-25 13:32 UTC, karpovfv-nedra commented on src/components/User/User.css
> +  &-Icon {
переименовал

2021-05-25 13:33 UTC, karpovfv-nedra commented on src/components/User/User.css
> +      background-color: transparent;
не нужен, убрал

2021-05-25 13:33 UTC, karpovfv-nedra commented on src/components/User/User.css
> +  &-Icon {
ага, добавил в сторю атрибут, и в доку добавил пропсы эти

2021-05-25 13:33 UTC, karpovfv-nedra commented on src/components/User/User.css
> +    &_m:not(.user_with-arrow) {
да, это ненужное, убрал

2021-05-25 13:33 UTC, karpovfv-nedra commented on src/components/User/User.tsx
> +          className={cnUser('Avatar', { status })}
убрал

2021-05-25 13:34 UTC, karpovfv-nedra commented on src/components/User/User.tsx
>  export const userPropSizeDefault: UserPropSize = userPropSize[0];
сделал так

2021-05-25 13:34 UTC, karpovfv-nedra commented on src/components/User/User.tsx
> +  const iconSize = getSizeByMap(iconSizeMap, size);
ага, переименовал

2021-05-25 13:34 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelectValue/UserSelectValue.css
> +    .Button {
вообще убрал модификатор `_disabled`

2021-05-25 13:35 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelectValue/UserSelectValue.css
> +    .User-Block {
убрал модификатор `_disabled`, и без него нормально всё, паддинг не меняется, кнопка не добавляется в дом-дерево, если disabled === true

2021-05-25 13:35 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelectValue/UserSelectValue.tsx
> +      className={cnUserValue({ withCancel, disabled })}
перетащил вверх

2021-05-25 14:53 UTC, gizeasy requested changes

2021-05-25 14:53 UTC, gizeasy commented on src/components/MultiCombobox/MultiCombobox.tsx
> +        multi
`multiple` - как нативное свойство селекта и во всех внутрянках поменяй, во всех селектах

2021-05-25 14:53 UTC, gizeasy commented on src/components/User/__stories__/User.stories.tsx
> +        iconRight={(boolean('withIconRight', false) ? iconRight : undefined) as never}
вынеси плиз в `defaultKnobs`
а тут завяжись на переменную

2021-05-25 15:28 UTC, karpovfv-nedra commented on src/components/MultiCombobox/MultiCombobox.tsx
> +        multi
поменял везде multi на multiple

2021-05-25 15:28 UTC, karpovfv-nedra commented on src/components/User/__stories__/User.stories.tsx
> +        iconRight={(boolean('withIconRight', false) ? iconRight : undefined) as never}
сделал

2021-05-25 15:37 UTC, gizeasy requested changes

2021-05-25 15:37 UTC, gizeasy commented on src/components/UserSelect/__stories__/UserSelect.docs.mdx
> +| `multi?`                                | `boolean`                                              | `true`         | Возможность выбрать несколько варинтов
`multiple`
и давай по умолчанию пусть будет `false`

2021-05-25 15:38 UTC, gizeasy requested changes

2021-05-25 15:38 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +    multiple: true,
а почему тут всегда `true`?

2021-05-25 16:30 UTC, karpovfv-nedra commented on src/components/UserSelect/__stories__/UserSelect.docs.mdx
> +| `multi?`                                | `boolean`                                              | `true`         | Возможность выбрать несколько варинтов
поправил

2021-05-25 16:30 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelect.tsx
> +    multiple: true,
убрал его отсюда

2021-05-26 06:02 UTC, gizeasy requested changes

2021-05-26 06:02 UTC, gizeasy commented on src/hooks/useSelect/useSelect.tsx
> +            : getOptionLabel(option)
уберем проверку на `searchFunction` и добавим его обязательность
во всех случаях где он мог быть не обязательным вынесем функции в эти компоненты. 
И дадим пользователю прокидывать свою функцию поиска

2021-05-26 06:02 UTC, gizeasy commented on src/hooks/useSelect/useSelect.tsx
>        const matchWithValueSearch = Boolean(
Кажется тут с логикой какая-то жопа, отрефач плиз, думаю половину грохнуть можно после того как функцию поиска вытащиш

2021-05-26 09:34 UTC, karpovfv-nedra commented on src/components/UserSelect/UserSelect.tsx
> +  const searchFunction = (item: Item, searchValueLowerCase: string): boolean => {
сделал, добавил необязательным пропсом компоненту `searchFucntion` , по дефолту она ищет по `getOptionLabel` и `getOptionAdditionalInfo `

2021-05-26 09:36 UTC, karpovfv-nedra commented on src/hooks/useSelect/useSelect.tsx
> +            : getOptionLabel(option)
сделал, теперь хук `useSelect` всегда ждёт на вход `searchFunction`, добавил её по дефолту во всех селектах, но наверх в api вынес только для `UserSelect`

2021-05-26 09:36 UTC, karpovfv-nedra commented on src/hooks/useSelect/useSelect.tsx
>        const matchWithValueSearch = Boolean(
убрал некоторые проверки

2021-05-26 14:36 UTC, gizeasy approved these changes

2021-05-26 14:38 UTC, merged