Calendar: added component and tests
gazprom-neft/consta-uikit pull request #1154
Opened 2021-05-13 21:26 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-05-17 08:33 UTC, al-fyodorov requested changes

2021-05-17 08:33 UTC, al-fyodorov commented on src/components/Calendar/helpers.ts
> +      // Привел к типам так как TS не понимает что при указанном `type`
TypeScript не особо гениальный инструмент конечно, но если где-то есть проблема с выводом типов, то это не TypeScript глупый, а разработчик не сообразил как написать верный вывод типов, вот пример как можно избавиться от приведения типов и не потерять текущую функциональность:

```tsx
type GetHandleSelectDateProps<TYPE extends CalendarPropType> = TYPE extends 'date' ? {
  type: 'date';
  value?: CalendarPropValue<'date'>
  onChange?: CalendarPropOnChange<'date'>;
  minDate?: Date;
  maxDate?: Date;
} : {
  type: 'date-range';
  value?: CalendarPropValue<'date-range'>;
  onChange?: CalendarPropOnChange<'date-range'>;
  minDate?: Date;
  maxDate?: Date;
}

const isDateRangeParams = (params: GetHandleSelectDateProps<'date' | 'date-range'>): params is GetHandleSelectDateProps<'date-range'> => {
  return params.type === 'date-range'
}

const isNotDateRangeParams = (params: GetHandleSelectDateProps<'date' | 'date-range'>): params is GetHandleSelectDateProps<'date'> => {
  return params.type === 'date'
}

type HandleSelectDate = (props: { value: Date; e: React.MouseEvent<HTMLDivElement> }) => void;

export function getHandleSelectDate<TYPE extends CalendarPropType = 'date' | 'date-range'>(params: GetHandleSelectDateProps<TYPE>): HandleSelectDate {
  if (isDateRangeParams(params)) {
    return ({ value: date, e }) => {
      if (params.minDate && params.maxDate) {
        if (!isWithinInterval(date, { start: params.minDate, end: params.maxDate }) || !isNotNil(params.value)) {
          return;
        }
      }

      if (isDateRange(params.value) && !isOnlyOneDateInRange(params.value) && typeof params.onChange === 'function') {
        return params.onChange({ e, value: [date, undefined] });
      }

      const [startDate, endDate] = params.value || [undefined, undefined];

      if (isDefined(startDate)) {
        if (startDate.getTime() === date.getTime()) {
          return;
        }
        if (typeof params.onChange === 'function') {
          return params.onChange({ e, value: startDate > date ? [date, startDate] : [startDate, date] });
        }
      }

      if (isDefined(endDate)) {
        if (endDate.getTime() === date.getTime()) {
          return;
        }
        if (typeof params.onChange === 'function') {
          return params.onChange({ e, value: endDate > date ? [date, endDate] : [endDate, date] });
        }
      }
    };
  }

  if (isNotDateRangeParams(params)) {
    return (props) => {
      if (!isWithInIntervalMinMaxDade(props.value, params.minDate, params.maxDate)) {
        return;
      }
      if (typeof params.onChange === 'function') {
        return params.onChange(props);
      }
    };
  }

  return () => null
};
```

2021-05-17 08:33 UTC, al-fyodorov commented on src/components/Calendar/helpers.ts
> +      // Привел к типам так как TS не понимает что при указанном `type`
Написан на коленке и многое еще можно упростить, но приводить типы и ссылаться только на то что используемый инструмент работает плохо, это неправильно.

2021-05-17 08:33 UTC, al-fyodorov commented on src/components/Calendar/__stories__/Calendar.mdx
> +| Свойство              | Тип или варианты значения           | По умолчанию | Описание                                                    |
Не знаю как принято, но кажется можно немного лучше сделать описание, как минимум потому что `onChange` это не `Выбранная дата или диапазон дат`, а обработчик событий выбора даты или диапазона дат, по остальным в таблице тоже неплохо бы пройтись.

2021-05-17 08:33 UTC, al-fyodorov commented on src/components/Calendar/CalendarSlider/CalendarSlider.tsx
> +                  role="button"
Если роль кнопка, может тогда перейти на кнопку и убрать отключение ESLint выше?

2021-05-17 10:54 UTC, kolebayev requested changes
перед мержем в дев нужно добавить ссылку на фигму в сторю компонента.
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=58%3A33602

именно в последний момент, чтобы при доделках у тебя не висла страница от загрузки фигмы

2021-05-17 15:16 UTC, gizeasy commented on src/components/Calendar/helpers.ts
> +      // Привел к типам так как TS не понимает что при указанном `type`
спасибо, исправил.

2021-05-17 15:19 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.mdx
> +| Свойство              | Тип или варианты значения           | По умолчанию | Описание                                                    |
да, не верно описано было. Проглядел
остальные параметры еще будут переписоваться когдабудет готовиться полноценная дока

2021-05-17 15:19 UTC, gizeasy commented on src/components/Calendar/CalendarSlider/CalendarSlider.tsx
> +                  role="button"
исправил

2021-05-18 06:25 UTC, gizeasy commented
> перед мержем в дев нужно добавить ссылку на фигму в сторю компонента.
> https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=58%3A33602
> 
> именно в последний момент, чтобы при доделках у тебя не висла страница от загрузки фигмы

Добавил

2021-05-18 06:36 UTC, kolebayev approved these changes

2021-05-18 14:04 UTC, al-fyodorov requested changes

2021-05-18 14:04 UTC, al-fyodorov commented on src/components/Calendar/helpers.ts
> +      if (isDefined(startDate)) {
Лучше старатся избегать вложенных if по возможности, так как большая вложенность усложняет читаемость.

2021-05-18 14:04 UTC, al-fyodorov commented on src/components/Calendar/CalendarSlider/CalendarSlider.tsx
> +                  // tabIndex={0}
Кажется надо удалить.

2021-05-18 15:18 UTC, gizeasy commented on src/components/Calendar/helpers.ts
> +      if (isDefined(startDate)) {
подправил условие и немного сократил код

2021-05-18 15:18 UTC, gizeasy commented on src/components/Calendar/CalendarSlider/CalendarSlider.tsx
> +                  // tabIndex={0}
убрал

2021-05-19 09:19 UTC, al-fyodorov approved these changes

2021-05-19 09:35 UTC, merged