docs(Theme): add color value preview and copy
gazprom-neft/consta-uikit pull request #1173
Opened 2021-05-18 16:36 UTC by kolebayev

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-05-18 18:08 UTC, gizeasy requested changes

2021-05-18 18:08 UTC, gizeasy commented on src/uiKit/components/ThemePreview/ThemePreview.tsx
> +      <SnackBar items={copiedItems} />
добавь класс и уже его опиши в стилях

2021-05-18 18:08 UTC, gizeasy commented on src/uiKit/components/ThemePreview/ThemePreview.tsx
> +      value: primaryColors['--color-bg-default'],
кажется что `value` не нужно держат в объекте, можно на этапе рендера получать значение с помощью `color`

2021-05-18 18:08 UTC, gizeasy commented on src/uiKit/components/ThemePreview/ThemePreview.tsx
> +  const bgColors = [
и нужно описать тип

2021-05-19 09:52 UTC, kolebayev commented on src/uiKit/components/ColorPreview/ColorPreview.css
> +.SnackBar {
я отдельно вынес на уровень ThemePreview, этот снекбар не имеет отношения к компоненту ColorPreview

2021-05-19 11:31 UTC, gizeasy commented on src/uiKit/components/ColorPreview/ColorPreview.css
> +.SnackBar {
так почему?
SnackBar является ребенком ThemePreview
так и в цсс пуст будет элементом блока ThemePreview

2021-05-19 11:31 UTC, gizeasy commented on src/uiKit/components/ColorPreview/ColorPreview.css
> +.SnackBar {
cnThemePreview('SnackBar')

2021-05-19 12:14 UTC, kolebayev commented on src/uiKit/components/ColorPreview/ColorPreview.css
> +.SnackBar {
https://github.com/gazprom-neft/consta-uikit/pull/1173/commits/0350008604bd27716baef34ea497f308d8b42dc6

2021-05-19 12:19 UTC, gizeasy approved these changes

2021-05-19 12:21 UTC, merged