feat(Table): add the ability to collapse table rows
gazprom-neft/consta-uikit pull request #1199
Opened 2021-05-24 08:13 UTC by DmitriyKaurov

## Описание изменений
Добавлена возможность создавать таблицы с группировкой и разворачиванием строк.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-05-25 13:17 UTC, gizeasy requested changes

2021-05-25 13:17 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +    <div style={{ paddingLeft }} className={cnTableRowsCollapse(null)}>
`paddingLeft`  лучше вынести в css а в стайл прокидывать только переменную `level`

2021-05-25 13:17 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +    <div style={{ paddingLeft }} className={cnTableRowsCollapse(null)}>
`cnTableRowsCollapse(null)`
не обязательно прокидывать `null`

2021-05-25 13:17 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +        <span
давай использовать компонент `Button` c `_view_clear` и `_size_s`

2021-05-25 13:17 UTC, gizeasy commented on src/components/Theme/_color/Theme_color_gpnDark.css
> +  --color-bg-nested-level-1: color($color-base-phantom a(6%));
Узнал у дизайнеров, идея была в том что уровни должны накладываться друг на друга, от этого они становятся темнее. Тут подумаем еще как сделать, пока вариант с созданием новых переменных не нравиться. 

Сделать физическую вложенность строк не совсем хорошая затея сейчас, пока вижу только вариант с составным бэкграундом когда один див будет накладываться на другой.

@kolebayev @schurf-des

2021-05-25 13:17 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +          {isExpanded ? <IconArrowDown size="s" /> : <IconArrowUp size="s" />}
иконки поменять местами, чтоб они отражали не состояние а действие

2021-05-25 13:17 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +          {isExpanded ? <IconArrowDown size="s" /> : <IconArrowUp size="s" />}
думаю что можно использовать и одну иконку, и анимировать ее переворот

2021-05-25 13:17 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +          {isExpanded ? <IconArrowDown size="s" /> : <IconArrowUp size="s" />}
@schurf-des что думаешь по поводу анимации?

2021-05-25 15:20 UTC, gizeasy commented on src/components/Theme/_color/Theme_color_gpnDark.css
> +  --color-bg-nested-level-1: color($color-base-phantom a(6%));
решили убрать подкрашивание фона, оставляем все вложенные списки дефолтным бекграундом, или транспарент не помню как оно сейчас

2021-05-26 08:24 UTC, DmitriyKaurov commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +    <div style={{ paddingLeft }} className={cnTableRowsCollapse(null)}>
@gizeasy исправил

2021-05-26 08:25 UTC, DmitriyKaurov commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +    <div style={{ paddingLeft }} className={cnTableRowsCollapse(null)}>
@gizeasy  Сделал отступ через css переменную

2021-05-26 08:29 UTC, DmitriyKaurov commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +          {isExpanded ? <IconArrowDown size="s" /> : <IconArrowUp size="s" />}
@gizeasy  Не совсем понял, получается используем  компонент Button c анимацией как у collapse? Возможно Button  size_s будет смотреться сильно большой в таблице с size='s'?

2021-05-26 14:40 UTC, gizeasy commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +          {isExpanded ? <IconArrowDown size="s" /> : <IconArrowUp size="s" />}
@schurf-des что думаешь про кнопку? иконка там такого же размера, только область клика больше

2021-05-31 06:38 UTC, DmitriyKaurov commented on src/components/Table/RowsCollapse/TableRowsCollapse.tsx
> +          {isExpanded ? <IconArrowDown size="s" /> : <IconArrowUp size="s" />}
@gizeasy Добавил Button в ячейку для разворачивания строк

2021-06-02 09:41 UTC, gizeasy commented
При применении фильтрации возникают ошибки
https://disk.yandex.ru/i/HsDNjEk4Za9Z7g

2021-06-02 15:40 UTC, gizeasy commented
@DmitriyKaurov поправите баг?

2021-06-03 07:32 UTC, DmitriyKaurov commented
> @DmitriyKaurov поправите баг?
Да, постараюсь в ближайшее время

2021-06-07 11:54 UTC, gizeasy commented
@DmitriyKaurov @kolebayev сейчас фильтрация идет по всем уровням вложенности, и получается такая штука, если отфильтровались  выводится список в списке есть элемент который имеет вложенность, но из-за того что его дети не подходят под фильтр их не видно, и не понятно возможно раскрыть элемент или нет. Может фильровать только по первому уровню?

2021-06-07 13:35 UTC, kolebayev approved these changes

2021-06-07 13:47 UTC, gizeasy approved these changes

2021-06-07 13:48 UTC, gizeasy commented
@schurf-des глянь плиз на дизайн, все ли ок

2021-06-08 08:53 UTC, schurf-des approved these changes

2021-06-09 13:51 UTC, merged