feat(Components): refactoring Select, Combobox, UserSelect
gazprom-neft/consta-uikit pull request #1280
Opened 2021-06-11 14:31 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-06-16 12:46 UTC, al-fyodorov commented on src/components/UserSelect/UserSelect.tsx
> +  type Item = typeof items[number];
Еще вывод типов в теле компонента, лучше поправить на использование из generic.

2021-06-16 12:48 UTC, al-fyodorov commented on src/components/UserSelect/UserSelectValue/UserSelectValue.tsx
> +  avatarUrl?: string;
Необязательные props, лучше оставлять внизу списка.

2021-06-16 12:49 UTC, al-fyodorov commented on src/components/UserSelect/__mocks__/data.mock.ts
> +export type MyGroup = string;
Типы если и нужны потом в сторисах, тестах или компоненте, то лучше выносить в отдельный файл.

2021-06-16 12:50 UTC, al-fyodorov commented on src/components/UserSelect/__stories__/UserSelect.stories.tsx
> +      <UserSelect<MyItem, MyGroup, false>
Не очень удобное использование, лучше автовывод типов.

2021-06-16 12:59 UTC, gizeasy commented
> И у файла `src/components/UserSelect/__tests__/UserSelect.test.tsx_` тоже странное расширение.

Пока так закоментировал, в таком виде не уйдет в прод, тесты в процессе написания.

2021-06-16 13:01 UTC, gizeasy commented on src/components/Combobox/__tests__/Combobox.test.tsx_
>  import { simpleItems } from '../../Combobox/__mocks__/data.mock';
Пока так закоментировал, в таком виде не уйдет в прод, тесты в процессе написания.

2021-06-16 13:03 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.docs.mdx
> +```tsx
документация пока в процессе написания, в таком виде не уйдет в прод, уже всезде `tsx`

2021-06-16 13:05 UTC, al-fyodorov commented
@gizeasy, если что у тебя есть история коммитов от туда можно взять файл, от "такого" комментирования пользы нет, кроме того эти файлы на ревью не исчезают, а остаются. И комментария о том что именно их проверять не надо нет.

2021-06-16 13:06 UTC, al-fyodorov commented
Удали их пожалуйста или доработай.

2021-06-16 13:06 UTC, al-fyodorov commented on src/components/Combobox/__stories__/Combobox.docs.mdx
> +```tsx
В этом PR не везде `tsx`, проверяется текущий PR а не другой. Эти исправления нужны здесь.

2021-06-16 13:07 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +import { groups, Item, items, myData, MyGroup, myGroup, MyItem } from '../__mocks__/data.mock';
Можешь аргументировать? я не спорю, интересно почему плохо держать переменные и их типы в одном файле?
или тебе экспорт из одного места не нравиться? могу через `typeof` тогда явно будет что тип относиться к этим данным, хотя и сейчас вроде бы понятно ведь в одном файле. Или в чем еще может быть проблема?

2021-06-16 13:07 UTC, al-fyodorov commented on src/components/Combobox/__stories__/Combobox.docs.mdx
> +```tsx
Или тогда надо на ревью сначала другой PR заслать, с изменениями на `tsx`, а потом этот.

2021-06-16 13:14 UTC, al-fyodorov commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +import { groups, Item, items, myData, MyGroup, myGroup, MyItem } from '../__mocks__/data.mock';
Если предполагается использование этих типов только для данных зашлушек, то оставь, но практика плохая когда тянуть их начинают по storis, tests, и прочим файлам для примеров. Тут проблема не в `почему плохо держать переменные и их типы в одном файле`, а в том что если типы растекутся по куче мест, любое небольшое изменение mock типов потребует доработок во всех этих местах, и за этим надо дополнительнос следить.

2021-06-16 13:35 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +      <Combobox<MyItem, MyGroup, false>
по разному пытался, но тут либо всегда гетеры указывать, либо в зависимости от дженериков делать обязательными гетеры. 
Еще был вариант сделать всегда не обязательными гетеры, тогда типы спокойно сами выводятся, но внутри компонента пришлось бы прибегнуть к приведением типов из за того что не возможно `DefaultItem` привести к `ITEM`

Ну давай я еще раз попытаюсь.
На данный момент мне нравиться что в зависимости от типов данных, гетеры становяться обязательными или не обязательными

2021-06-16 13:36 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +  // parameters: {
скрыл на время, в пре про документацию поставлю на место

2021-06-16 13:47 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +  const renderValueDefaultMultiple: PropRenderValue<Item> = ({ item, handleRemove }) => {
Возможно вынести, но тут вопрос Api либо нам приходит только `item` либо еще приходит все что из гетеров достали. Либо можно вынести функцию которая будет принимать на вход гетеры, и возвращать функцию рендера.

Что думаешь по поводу возвращать не только `item` но и все что пришло от гетеров?

2021-06-16 13:48 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +  useSetInputWidth(controlInnerRef, helperInputFakeElement, inputRef, searchValue, value, multiple);
согласен, подпишу

2021-06-16 14:05 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +import { groups, Item, items, myData, MyGroup, myGroup, MyItem } from '../__mocks__/data.mock';
Понял, но пока проблем вроде не было, а тут и другая сторона медали есть, если в друг апи компонента расширилось и mock данные нужно поменять, то в другим местах ни чего менять не приходиться. Возможно потом передумаем, но пока проблем такого характера не было

2021-06-17 06:45 UTC, al-fyodorov commented on src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
>  import React, { createRef, useEffect, useMemo, useState } from 'react';
Так надо найти в чем проблема и исправить ее, а не маскировать. Пока выглядит так что приша проблема и решили методом "и так сойдет", но это не правильно.

2021-06-18 10:29 UTC, gizeasy commented on src/common.d.ts
> +  // eslint-disable-next-line import/export
отключил для всего файла

2021-06-18 10:36 UTC, gizeasy commented on src/utils/getGroups.ts
> +  // Items
описал по другому

2021-06-18 10:36 UTC, gizeasy commented on src/components/BasicSelect/BasicSelect.tsx
> +export { Select as BasicSelect } from '../Select/Select';
удалил

2021-06-18 10:38 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.docs.mdx
> +```tsx
вернул как было, в следующем Пре будет актуальная дока

2021-06-18 10:40 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +import { groups, Item, items, myData, MyGroup, myGroup, MyItem } from '../__mocks__/data.mock';
Оставлю так, если возникнут проблемы, раскидаем отдельно по примерам. тестам, и строисам

2021-06-18 10:41 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +      <Combobox<MyItem, MyGroup, false>
исправил

2021-06-18 10:42 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +  // parameters: {
скрыл, так как документация и примеру уже не актуальные, В слелудующих прах напишу актуальную документацию

2021-06-18 10:43 UTC, gizeasy commented on src/components/Combobox/__stories__/ComboboxStories.css
> +    &::before {
сам всегда об этом говорю при ревью, и сам же упустил этот момент))
поправил

2021-06-18 10:44 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +export const Combobox: ComboboxComponentType = (props) => {
Описал через функцию, не подскажешь как в т аком виде подкрутить возможность прокинуть `ref`?

2021-06-18 10:45 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +  type Item = typeof items[number];
fix

2021-06-18 10:46 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +  const renderValueDefaultMultiple: PropRenderValue<Item> = ({ item, handleRemove }) => {
Не вынес, по причине того что в функциях используются геттеры, и в любом случае придется при каждом рендере создавать новую функцию, а прокидывать в рендер уже готовые результыты гетеров кажется лишним.

2021-06-18 10:52 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +  useSetInputWidth(controlInnerRef, helperInputFakeElement, inputRef, searchValue, value, multiple);
спусил хук вниз, завел issue на описание компонентов в документации

2021-06-18 10:53 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +            {multiple && <div className={cnSelect('ControlValue')}>{renderControlValue()}</div>}
поправил

2021-06-18 10:55 UTC, gizeasy commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Select: useSelectEventsHandler as EventHandler,
Создал задачку #1295

2021-06-18 10:56 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/__tests__/useSelectEventsHandler.test.tsx
> +// const defaultProps = {
удалил

2021-06-18 10:59 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/__tests__/useSelectEventsHandler.test.tsx
> +  // TODO: когда буду писать тесты разберусь с этим
создал #1296

2021-06-18 11:01 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
>  import React, { createRef, useEffect, useMemo, useState } from 'react';
создал задачку #1297

2021-06-18 11:04 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/__tests__/useSelectEventsHandler.test.tsx
> +    rerender(getComponent((newProps as unknown) as SelectProps<SelectOption, unknown>));
создал задачку #1295 
чтобы исправить типы во всем компоненте `EventInterceptor`

2021-06-18 11:11 UTC, gizeasy commented on src/components/Select/Select.tsx
> +  type Item = typeof items[number];
fix

2021-06-18 11:11 UTC, gizeasy commented on src/components/Select/__tests__/Select.test.tsx_
>  import ResizeObserver from '../../../../__mocks__/ResizeObserver';
исправлю в прах по доке

2021-06-18 11:12 UTC, gizeasy commented on src/components/Select/__stories__/Select.stories.tsx
> +      <Select<MyItem, MyGroup>
fix

2021-06-18 11:13 UTC, gizeasy commented on src/components/Select/__stories__/Select.docs.mdx
> +Для работы компоненту нужно передать тип опции: `<Select<T> {..props}/>`.
дока устарела, будет пр где опишу новую

2021-06-18 11:17 UTC, gizeasy commented on src/components/Select/__stories__/SelectStories.css
> +    &::before {
создал задачку #1298

2021-06-18 12:38 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +      <Combobox<MyItem, MyGroup, false>
есть нюанс((
в текущей реализации так:

тип выводиться
![image](https://user-images.githubusercontent.com/13190808/122557034-e7307c00-d044-11eb-8222-8ba124420b9f.png)


но если прописывать геттер прямо в компоненте без указания типизации то вот так происходит:
по прежнему тип выводится и требуется описать функию нужного типа
![image](https://user-images.githubusercontent.com/13190808/122557234-3080cb80-d045-11eb-82db-c9578ff71073.png)


но 
![image](https://user-images.githubusercontent.com/13190808/122557219-29f25400-d045-11eb-9c44-d3c86396e0f4.png)

Это связано с тем что есть условие на тип 
![image](https://user-images.githubusercontent.com/13190808/122557305-49897c80-d045-11eb-8b0b-985edcef3032.png)


и вывод типа до описания функции работает как описываешь функцию так есть 2 перегрузки одна когда `ITEM extends DefaultItem` и вторая когда нет, так как при указании функции типы одинаковые.

Возможные решения:
1) сделать так чтобы типы условия были разными

![image](https://user-images.githubusercontent.com/13190808/122557663-c157a700-d045-11eb-963c-ac578e42add0.png)

в таком случае типы нормально выводятся но присутствует лишний пропс, который в коде ни как не обрабатывается

![image](https://user-images.githubusercontent.com/13190808/122557800-ecda9180-d045-11eb-80f5-ce0f3d2be633.png)

2) убрать условие `ITEM extends DefaultItem`

![image](https://user-images.githubusercontent.com/13190808/122558036-4347d000-d046-11eb-9b84-233dd13fdb20.png)

в таком случае типы выводятся как следует, без лишних действий
![image](https://user-images.githubusercontent.com/13190808/122558096-55297300-d046-11eb-977d-7e23d0f85ff9.png)

но при указании кастомного ITEM, нет обязательности гетеров, что во первых делает апи компонента не совсем явным (но можно описать это в документации, как требование), а во вторых внутри компонента мы уже не сможем понят какого типа геттер к попал в компонент((

![image](https://user-images.githubusercontent.com/13190808/122558532-dc76e680-d046-11eb-9a43-8c053207c96b.png)
![image](https://user-images.githubusercontent.com/13190808/122558941-55763e00-d047-11eb-8a9b-94d77b3089e3.png)

Второй вариант самый удобный для пользователя но есть возможность сломать компонент, не докинув в него гетера

Что думаешь

2021-06-18 13:40 UTC, gizeasy commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  let index = -1;
не могу придумать в какую(( 
подскажешь?

2021-06-18 13:42 UTC, gizeasy commented on src/components/Select/__stories__/SelectStories.css
> +    &::before {
и тут поправил

2021-06-18 13:42 UTC, gizeasy commented on src/components/SelectComponents/SelectValueTag/SelectValueTag.tsx
> +  handleRemove?: (e: React.SyntheticEvent) => void;
перенес

2021-06-18 14:09 UTC, gizeasy commented on src/components/SelectComponents/helpers.ts
> +      inputRef.current.style.setProperty(
fix

2021-06-18 14:10 UTC, gizeasy commented on src/components/Table/__tests__/filtering.test.ts
> +const FILTERS: Filters<Row> = [...COUNT_FILTERS, ...PRICE_FILTERS];
Тесты упали. TS стал ругаться на типы

2021-06-18 14:11 UTC, gizeasy commented on src/components/User/User.css
> +    /* --button-height: var(--control-height-xs); */
fix

2021-06-18 14:11 UTC, gizeasy commented on src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
> +    avatarUrl?: string;
fix

2021-06-18 14:12 UTC, gizeasy commented on src/hooks/useKeys/useKeys.tsx
> +export type KeyHandler = (prop: {}, e: React.KeyboardEvent) => void;
спасибо, fix

2021-06-18 17:25 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  type Item = typeof items[number];
fix

2021-06-21 10:07 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +  // parameters: {
удалил совсем коментырии и доку, в следующих прах добавлю

2021-06-21 10:07 UTC, gizeasy commented on src/components/Select/__stories__/Select.docs.mdx
> +Для работы компоненту нужно передать тип опции: `<Select<T> {..props}/>`.
удалил доку

2021-06-21 10:15 UTC, gizeasy commented on src/utils/getGroups.ts
> +    for (const item of items) {
сделал через if return, убрал одну вложенность. Стало лучше

2021-06-21 10:15 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  type Item = typeof items[number];
fix

2021-06-21 10:16 UTC, gizeasy commented on src/components/UserSelect/UserSelectValue/UserSelectValue.tsx
> +  avatarUrl?: string;
fix

2021-06-21 10:17 UTC, gizeasy commented on src/components/UserSelect/__stories__/UserSelect.stories.tsx
> +      <UserSelect<MyItem, MyGroup, false>
fix, но есть нюанс. выше описал

2021-06-22 12:44 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +      <Combobox<MyItem, MyGroup, false>
Сделал с дополнительными свойствами указателями на кастомный тип
`customItemType` и `customGroupType`

2021-06-22 14:41 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +      <Combobox<MyItem, MyGroup, false>
Не понравилась реализация((
сделал без проверки на `defaultItem`.
С одной стороны добавляется проблема в том что при указании кастомного `ITEM` нет обязательности геттеров, но как только указываем геттер так ошибок не будет.
Но этой малой кровью мы пришли к тому что типы с наружи компонента нормально выводятся, и есть возможность не указывать все гетеры если они совпадают с дефолтными.

Думаю оставить так, и Api гибче стало и вывод типов нормальный.
В документации выделю **жирным**, что при и спользовании кастомных типов должны быть уверенны что дефотные гетеры подходят а если не подходят нужно указать свои.

2021-06-24 15:38 UTC, al-fyodorov requested changes

2021-06-24 15:38 UTC, al-fyodorov commented on src/components/Select/Select.tsx
> +    getItemKey = (defaultGetItemKey as unknown) as PropGetItemKey<ITEM>,
Если задаться целью, то можно и без всевозможных приведений типов реализовать функциональность, просто нужно больше времени уделять типизации на проекте, а не избегать ее:

https://codesandbox.io/s/condescending-wescoff-knly4?file=/src/App.tsx

Вот каркас на основе которого лучше собрать требуемый Вам компонент, но тогда большая часть рефакторинга и не имела смысла так как переписывать придется почти все, и стало ли лучше от подобного рефакторинга не известно. Но часть связанная с изменением типов данных явно была проделана зря.

2021-06-24 15:38 UTC, al-fyodorov commented on src/components/Select/Select.tsx
> +    getItemKey = (defaultGetItemKey as unknown) as PropGetItemKey<ITEM>,
Можете оставить как есть, но ставить апрув в PR где в большинстве мест были просто приведены типы из-за того что так быстрее не собираюсь.

2021-06-25 08:48 UTC, gizeasy commented on src/common.d.ts
> +/* eslint-disable import/export */
добавил в конфиг линтера

2021-06-25 08:51 UTC, gizeasy commented on src/components/Select/Select.tsx
> +    getItemKey = (defaultGetItemKey as unknown) as PropGetItemKey<ITEM>,
в целом ни чего переписывать не пришлось)) спасибо за подсказку
поправил типы, теперь все супер гибко стало и TS теперь подсказывает что нужно прописать геттер если свойство которое необходимо геттеру отсутствует

2021-06-28 10:44 UTC, gizeasy commented on src/components/Combobox/helpers.ts
> +export function withDefaultGetters<
@al-fyodorov, если таким образом добавлять дефолтные гетеры, то в дальнейшем TS yне ругается на типы, но кажется это из-за большого количества перегрузок, и приведения типов помоему будет даже лучше, потому как явно видно будет. Возможно я ошибаюсь.

2021-07-05 16:18 UTC, al-fyodorov requested changes

2021-07-05 16:18 UTC, al-fyodorov commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  let index = -1;
```ts
const fabricIndex = (start: number = 0) => {
  let index: number = start
  
  return () => {
    index = index + 1
    
    return index
  }
}

const getIndex = fabricIndex(-1)
```

И потом вместо того чтобы мутировать переменную, а потом ее использовать можно сразу результат прокидывать в нужный метод:

```ts
{...getOptionProps({ index: getIndex(), item: group })}
```

На каждый новый рендер функция с замыканием будет пересоздаваться, что сбросит счетчик. Так хотябы ничего что находится внутри компонента не мутируется напрямую, а по методу более понятно как он работает.

2021-07-12 13:29 UTC, gizeasy commented on src/components/Combobox/helpers.ts
> +export function withDefaultGetters<
Описал так как сказал, вроде рабочий вариант

2021-07-13 05:17 UTC, al-fyodorov approved these changes

2021-07-13 09:52 UTC, merged