Feat/collapse group
gazprom-neft/consta-uikit pull request #1306
Opened 2021-06-24 15:07 UTC by Bright-Burn

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-06-28 10:24 UTC, gizeasy requested changes

2021-06-28 10:24 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +            iconPosition={iconPosition as 'left'}
Думаю можно обойтись без приведения типов

2021-06-28 10:24 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +  getKey: (item: ITEM) => string;
В текущей реализации, getKey лишнее свойство, если будем давай возможность указать какие именно открытые, то-есть состояние выносим за компонент. То тогда оно будет полезно, тогда свойство `expandedAll` будет не нужным. Так как с верху компонента возможно будет в свойство `opened` кинуть массив открытых элементов.

Для такой реализации можешь взять хук useChoseGroup, он как раз для того чтобы делать выборку из нескольких элементов, в данном случае все выбранные это открытые.

2021-06-28 10:58 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +  getKey: (item: ITEM) => string;
Оставить реализацию с сотоянием открытых внутри или дать возможность задавать это с верху, 
в целом с верху задавать какой открыть это удобно, к примеру когда нам необходимо развернуть определенный элемент из какогото внешнего контрола. Типа страница товара, есть кнопка отзывы, по ней скролимся к колапсу и разворачиваем отзывы.
Но с другой стороны при такой сложной функциональности проще взять `Collaps` и уже навертеть вокруг него все что хочешь.

Что сам думаешь, как считаешь лучше будет?

2021-07-20 08:06 UTC, gizeasy approved these changes

2021-07-20 11:03 UTC, kolebayev approved these changes

2021-07-21 14:23 UTC, nekitk requested changes

2021-07-21 14:23 UTC, nekitk commented on src/components/CollapseGroup/CollapseGroup.tsx
> +    multiple: !isAccordion as false,
почему `as false`?

2021-07-21 14:23 UTC, nekitk commented on src/components/CollapseGroup/CollapseGroup.tsx
> +    false,
смущает хардкод дженериков и большое количество приведений при использовании хука. стоило ли заводить кастомный хук useChoiceGroupIndexed, если его не получается нормально типизировать?

2021-07-21 14:23 UTC, nekitk commented on src/components/CollapseGroup/CollapseGroup.tsx
> +    isCanNullableValue: true,
зачем эта опция, если она всегда true?

2021-07-21 14:23 UTC, nekitk commented on src/components/CollapseGroup/CollapseGroup.tsx
> +            // привел к типам так как не хочется нагромождать условий, таких как:
комментарий должен быть над комментируем блоком кода

2021-07-21 14:23 UTC, nekitk commented on src/components/CollapseGroup/CollapseGroup.tsx
> +            // {...closeIcon ? {closeIcon} : {
кажется, проще и нагляднее будет нагромоздить условий в коде, чем всё равно писать их, но в комментарии. и это даже по количеству строк меньше будет.

2021-07-21 14:35 UTC, gizeasy commented on src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleView/CollapseGroupExampleView.tsx
> +import React from 'react';
в начале думал отразить это в документации потом подумал что в целом от обычного колапса это не отличается и забыл удалить

2021-07-21 14:36 UTC, gizeasy commented on src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleView/CollapseGroupExampleView.tsx
> +import React from 'react';
удалил

2021-07-21 14:37 UTC, gizeasy commented on src/hooks/useChoiceGroupIndexed/useChoiceGroupIndexed.ts
> +  isCanNullableValue?: boolean;
fix

2021-07-21 14:40 UTC, gizeasy commented on src/hooks/useChoiceGroupIndexed/useChoiceGroupIndexed.ts
> +export function useChoiceGroupIndexed<
да, планируется вынести его, отдельную задачку создал https://github.com/gazprom-neft/consta-uikit/issues/1362

2021-07-21 14:44 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +    multiple: !isAccordion as false,
привел к типам когда `multiple = false`.  если `isAccordion = true` то поведение `useChoiceGroupIndexed` должно быть `multiple = false`.

2021-07-21 14:55 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +    false,
Сам по себе он нормально типизирован. и если б не было isAccordion то типы возможно было и не прописывать. Привел ровно потому что TS не понимает что при `isAccordion = true` callBack будет удовлетворительного типа, и также при `isAccordion = false`. Конечно можно написать с верху условие где подсказать TSу какие реально типы будут, но кажется ради этого можно и приведение типов сделать, чтоб в райнтайме лишних операций не было.

2021-07-21 14:56 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +    isCanNullableValue: true,
в данном случае она true, но если нам нужна логика к в radio, когда нельзя оставить значение не выбранным, можно указать `false`

2021-07-21 15:11 UTC, gizeasy commented on src/components/CollapseGroup/CollapseGroup.tsx
> +            // {...closeIcon ? {closeIcon} : {
fix

2021-07-22 12:39 UTC, nekitk approved these changes

2021-07-22 12:39 UTC, nekitk commented on src/components/CollapseGroup/helpers.ts
> +type choiceGroupIndexedParams = {
Тип стоит с большой буквы назвать

2021-07-22 12:39 UTC, nekitk commented on src/components/CollapseGroup/helpers.ts
> +export const useChoice = <ITEM, IS_ACCORDION extends boolean>(
мб вынесем этот хук в отдельный одноимённый файл, чтобы хэлперы на раздувать?

2021-07-22 12:39 UTC, nekitk commented on src/components/CollapseGroup/CollapseGroup.tsx
> +  const { getChecked, getOnChange } = useChoice(props);
магия, конечно) зато компонент почище стал выглядеть

2021-07-22 13:34 UTC, merged