docs(Calendar): add docs & examples
gazprom-neft/consta-uikit pull request #1311
Opened 2021-07-02 11:15 UTC by arhayka

issue -  907

## Описание изменений

Написала документацию, добавила примеры. 

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-07-02 11:16 UTC, arhayka commented
Нужна помощь:
- не разобралась с обработчиками событий, и примеры календариков все неживые,
- не уверена, что правильно описала всё про даты, проверьте, плиз,
- нужно добавить пример использования в конце.

2021-07-09 11:54 UTC, gizeasy requested changes

2021-07-09 11:54 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +## Диапазон дат
Заголовок надо поменять, я когда читаю его кажется что речь пойдет о выборе диапазона, а тут про ограничение. Может что-то типа "Ограничение выбора", в дальнейшем сюда еще добавится указание массива которые нельзя выбрать.

2021-07-09 11:54 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +Указать текущую дату (чтобы подсветить её в календаре) можно в свойстве `currentVisibleDate`.
В данном случае указываеся сраница календаря))) о есть месяц который виден.
А когда читаю, кажется что речь идет о выборе дате `value`
Думаю заголовок надо понят на "Видимая страница календаря"
Можно указать дату с которой календарь откроется

2021-07-09 11:54 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +<Calendar locale={frLocale} />
укажи еще откуда взяли локализацию

```tsx
import frLocale from 'date-fns/locale/fr';
 
const CalendarExampleLocale = () => {
  return (
      <Calendar locale={frLocale} />
  );
};

2021-07-09 11:54 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +## Выбор даты
нужно еще добавить что в зависимости от свойства `type`
value принимает разные типы  смотреть в `CalendarPropValue` (ссылка на свойства)

также событие выбора даты тоже зависит от свойства `type` `CalendarPropOnChange`  (ссылка на свойства)

И написат что выбранную дату указываем в свойстве `value`

2021-07-14 09:24 UTC, arhayka commented
Поправила доку по замечаниям, немножко поменяла структуру, разделила и добавила примеры. @gizeasy помоги добавить пример использования, плиз.

2021-07-14 10:12 UTC, gizeasy commented
@arhayka @kolebayev кажется что пример использования в конце не нужен, так как примеров достаточно на странице

2021-07-14 10:49 UTC, gizeasy requested changes

2021-07-14 10:49 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +## Пример
Убери слово Пример

2021-07-14 11:54 UTC, gizeasy approved these changes

2021-07-14 12:16 UTC, kolebayev approved these changes

2021-07-14 12:16 UTC, gizeasy commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +## Пример
так договорились же что не надо?

2021-07-14 12:18 UTC, merged