feat(DatePicker): add DatePicker
gazprom-neft/consta-uikit pull request #1316
Opened 2021-07-09 09:29 UTC by gizeasy

issue -  #1166

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-07-20 11:08 UTC, kolebayev requested changes
в массиве `datePickerPropCalendarForm` в `brick` букву c пропустил

2021-07-20 11:11 UTC, kolebayev commented
@gizeasy в сторибуке контрол не реагирует на изменение separator'а

2021-07-20 14:06 UTC, gizeasy commented
> @gizeasy в сторибуке контрол не реагирует на изменение separator'а

Реагирует, его надо изменить вместе с изменением формата, 

```
format: 'dd.MM.yyyy'
separator: '.'
```

```
format: 'yyyy/MM/dd'
separator: '/'
```

В доке будет

2021-07-21 09:15 UTC, kolebayev approved these changes

2021-07-21 09:54 UTC, nekitk requested changes
слишком большой пр, чтобы ревьюить
стоит разбить на серию пр-ов поменьше

2021-12-01 14:33 UTC, closed without merging