feat(DragNDropField): added new component and examples
gazprom-neft/consta-uikit pull request #1329
Opened 2021-07-14 14:25 UTC by nekitk

issue -  #912

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-07-14 14:31 UTC, nekitk commented on .eslintrc.js
> +    '@typescript-eslint/no-use-before-define': 'off',
отключил, т.к. TS сам умеет отслеживать те места, где важно объявить переменную раньше

в остальных местах (например, с функциями) удобнее располагать их после использования. например, чтобы в начале файла шёл компонент, а под ним дочерние компоненты или хэлперы

2021-07-14 14:35 UTC, nekitk commented on src/components/DragNDropField/helpers.ts
> +const ERROR_CODES: Record<FileError['code'], string> = {
@kolebayev в этом файле находятся тексты ошибок

при желании мы можем расширить тексты ошибок подробностями — например, в ошибке о размере файла указать размер файла и предельное значение. но лучше это сделать в отдельном ишью/pr-е.

2021-07-20 08:27 UTC, gizeasy requested changes

2021-07-20 08:27 UTC, gizeasy commented on src/components/DragNDropField/__stories__/DragNDropField.docs.mdx
> +- [`accept`](#accept)
Некоторые ссылки не работают.
Напиши url с маленькой буквы.

2021-07-20 10:24 UTC, nekitk commented on src/components/DragNDropField/__stories__/DragNDropField.docs.mdx
> +- [`accept`](#accept)
поправил

2021-07-20 11:04 UTC, gizeasy approved these changes

2021-07-20 11:09 UTC, merged