docs(Select): edit docs
gazprom-neft/consta-uikit pull request #1347
Opened 2021-07-20 08:53 UTC by arhayka

issue -  1325

## Описание изменений

Вычитала документацию, поменяла структуру немножко.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-07-20 11:16 UTC, kolebayev approved these changes

2021-07-21 08:55 UTC, gizeasy requested changes

2021-07-21 08:55 UTC, gizeasy commented on src/components/Select/__stories__/Select.docs.mdx
> +Элементы выпадающего списка можно описать в массиве `items`. Тип свойства `items` по умолчанию равен [DefaultItem](#свойства)). Что внутри:
`[DefaultItem](#свойства))`
Последняя скобочка лишняя

2021-07-21 08:55 UTC, gizeasy commented on src/components/Select/__stories__/Select.docs.mdx
> +Чтобы разбить элементы списка на группы, передайте массив групп в свойство `groups`. Тип свойства `groups` по умолчанию равен [DefaultGroup](#свойства)). Что внутри:
`[DefaultGroup](#свойства))`

опять скобочка

2021-07-21 08:55 UTC, gizeasy commented on src/components/Select/__stories__/Select.docs.mdx
> +- `label` — название группы (в нём не нужна точка),
(в нём не нужна точка) - я вообще не понял

2021-07-21 08:55 UTC, gizeasy commented on src/components/Select/__stories__/Select.docs.mdx
> +    id: 3,
ID - должны быть уникальными, поставь дальше по очереди 4,5

2021-07-21 09:11 UTC, arhayka commented on src/components/Select/__stories__/Select.docs.mdx
> +- `label` — название группы (в нём не нужна точка),
ой, это откуда-то прилетело О_о, исправлю

2021-07-21 10:05 UTC, gizeasy approved these changes

2021-07-21 10:09 UTC, merged