feat(Tabs): added line position variants
gazprom-neft/consta-uikit pull request #1374
Opened 2021-07-23 15:47 UTC by nekitk

issue #1072

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-07-27 08:01 UTC, al-fyodorov approved these changes

2021-08-09 07:50 UTC, gizeasy requested changes

2021-08-09 07:50 UTC, gizeasy commented on src/components/Tabs/Tabs.css
> +      transition: transform 0.25s, width 0.25s, heigth 0.25s;
при вертикальной ориентации, высота меняется не плавно,  
поставил `transition: all 0.25s` стало плавно.
Может попробовать transition расписать не сокращенно...

2021-08-09 07:50 UTC, gizeasy commented on src/components/Tabs/Tabs.css
>    position: relative;
Нашел багу, давай тут поправим.
Если текста много он сжимает иконку
![image](https://user-images.githubusercontent.com/13190808/128673984-4b568b1a-dc8e-4413-a85f-2fda8ca8ba9c.png)

давай иконке зададим `flex: none;` тогда она перестанет сжиматся

2021-08-09 13:50 UTC, gizeasy requested changes

2021-08-09 13:50 UTC, gizeasy commented on src/components/Tabs/Tabs.tsx
> +const getTabsDirection = (linePosition: TabsPropLinePosition): 'horizontal' | 'vertical' =>
давай перенесем в хелперы

2021-08-10 10:34 UTC, nekitk commented on src/components/Tabs/Tabs.css
> +      transition: transform 0.25s, width 0.25s, heigth 0.25s;
Оказалось, тут опечатка в `height`, поправил

2021-08-10 10:46 UTC, gizeasy approved these changes

2021-08-13 11:19 UTC, merged