feat(Tabs): adapt tabs to available width by hiding unfitting tabs in dropdown
gazprom-neft/consta-uikit pull request #1383
Opened 2021-07-27 14:17 UTC by nekitk

BREAKING CHANGE:
Tabs' renderItem render prop doesn't provide key, ref and className anymore as they are no longer
needed. Just remove them from your render prop implementation.

issue -  #1126

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-07-28 09:09 UTC, nekitk commented on package.json
> +    "focus-trap-react": "8.7.0",
Добавил для возможности навигироваться с клавиаутуры по пунктам в поповере. Используется в `TabsMoreItems.tsx`

2021-08-06 09:04 UTC, al-fyodorov approved these changes

2021-08-09 13:49 UTC, gizeasy requested changes

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +          <Popover anchorRef={buttonRef} direction="downStartRight" offset={4}>
исходя из макета `offset`должен быть таким чтобы граница повпера лежала на линии табов.

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +          <Popover anchorRef={buttonRef} direction="downStartRight" offset={4}>
У поповера нет скруглений, поставь дефолтный

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +        <Button
отступы от кнопки не верный, получается что при размере `m`, item высотой 38px а item в которой кнопка 32px, надо отступ завязать на размер. чтоб одинаковые были, а то получается что если все пункты скрывается то высота компонента пляшет

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +        <Button
@kolebayev не нравиться поведение, когда открыто меню кликаем на кноку `...` то меню скрывается и тут же открывается, кажется лучше сделать просто закрытие.

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +          <Popover anchorRef={buttonRef} direction="downStartRight" offset={4}>
в некоторых случаях меню при открытии прыгает меню высчитывая позицию, думаю можно этого избежать сохраняя предудыщую удачную позицию, можно воспользоваться свойством поповера `onSetDirection`

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +          <Popover anchorRef={buttonRef} direction="downStartRight" offset={4}>
Еще можно сократить разрешенные направления разворота до
```
'downStartLeft',
'upStartLeft',
'downStartRight',
'upStartRight',
```

Тем самым сократим перебор направлений и предотвратим дерганье при открытии, возможно не будет необходимости сохранять удачную позицию разворота.

2021-08-09 13:49 UTC, gizeasy commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +        <Button
@kolebayev как думаешь стоит ли передвигать линию под кнопку `...` если выбран пункт за кнопкой?

2021-08-09 14:34 UTC, nekitk commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +        <Button
> @kolebayev как думаешь стоит ли передвигать линию под кнопку ... если выбран пункт за кнопкой?

Это уже уточнял, Илья сказал, что не надо: https://gazprom-neft.slack.com/archives/G0127HBBS04/p1627304189095800

2021-08-10 10:54 UTC, nekitk commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +        <Button
> отступы от кнопки не верный, получается что при размере `m`, item высотой 38px а item в которой кнопка 32px, надо отступ завязать на размер. чтоб одинаковые были, а то получается что если все пункты скрывается то высота компонента пляшет

Проблему понял, но решил иначе — делаю табы невидимыми, но на высоту контейнера они всё равно влияют.
На проп размера завязываться не стоит, т.к. табы могут быть кастомные через renderItem, их высоту мы не знаем.

2021-08-10 11:26 UTC, nekitk commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +          <Popover anchorRef={buttonRef} direction="downStartRight" offset={4}>
Прыжки оказались из-за переноса текста на новую строку в поповере. Запретил перенос и прыжки пропали.

2021-08-10 11:55 UTC, nekitk commented on src/components/Tabs/MoreItems/TabsMoreItems.tsx
> +        <Button
> @kolebayev не нравиться поведение, когда открыто меню кликаем на кноку `...` то меню скрывается и тут же открывается, кажется лучше сделать просто закрытие.

Поправил. Из-за focus-trap были проблемы с этим моментом, но разобрался.

2021-08-10 14:19 UTC, gizeasy commented
![image](https://user-images.githubusercontent.com/13190808/128882872-8d187387-b552-41d8-b0be-aa519de4dc2b.png)

при размере `s` текст в табах которые в дропдауне остается таким же как `m`
это связано с тем что модификатор применяется компоненту Tabs а далее распростроняется css переменными
думаю лучше будет завести пропс size у TabsTab и там же расчитывать размер иконки, чтоб все в одном месте было. ну и в рендерайтем проставить этот размер.

2021-08-10 15:13 UTC, gizeasy approved these changes

2021-08-13 10:14 UTC, merged