docs(Skeleton): edit docs
gazprom-neft/consta-uikit pull request #1385
Opened 2021-07-28 09:52 UTC by arhayka

issue -  1130

## Описание изменений

Отредактировала документацию.

2021-07-28 11:19 UTC, nekitk requested changes

2021-07-28 11:19 UTC, nekitk commented on src/components/Skeleton/__stories__/Skeleton.docs.mdx
> +В нашей дизайн-системе несколько скелетонов, с их помощью можно сделать плейсолдеры для разных компонентов. Например, на месте этого скелетона появятся аватарка и текст — когда загрузятся.
плейсолдеры — опечатка, буквы х не хватает

2021-07-28 11:19 UTC, nekitk commented on src/components/Skeleton/__stories__/Skeleton.docs.mdx
> +- [Прямогуольный скелетон](#прямоугольный-скелетон)
Прямогуольный — опечатка

2021-07-29 07:42 UTC, arhayka commented on src/components/Skeleton/__stories__/Skeleton.docs.mdx
> +В нашей дизайн-системе несколько скелетонов, с их помощью можно сделать плейсолдеры для разных компонентов. Например, на месте этого скелетона появятся аватарка и текст — когда загрузятся.
упс, спасибо)

2021-08-03 08:08 UTC, nekitk approved these changes

2021-08-09 13:54 UTC, gizeasy approved these changes

2021-08-10 10:08 UTC, kolebayev approved these changes

2021-08-10 10:49 UTC, merged