feat(Tabs): added new items fit mode - scroll
gazprom-neft/consta-uikit pull request #1399
Opened 2021-08-04 09:56 UTC by nekitk

issue -  #1305

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-08-10 07:32 UTC, gizeasy commented
![image](https://user-images.githubusercontent.com/13190808/128826608-f8b1c3e8-f583-494b-a9ca-2fadff591448.png)
@kolebayev может в дизайне отступы больше сделаем чтоб эффект фокуса не обрязался?

2021-08-10 07:52 UTC, gizeasy commented
![image](https://user-images.githubusercontent.com/13190808/128829179-d9704a59-0175-4c2a-8db1-9a90ea4d163d.png)

Нужно добавить зависисмости на пересчет размеров табов, сейчас они не пересчитываются если переключаешь `linePosition` и `onlyIcon`

2021-08-10 08:01 UTC, gizeasy requested changes
https://github.com/gazprom-neft/consta-uikit/pull/1399#issuecomment-895811785

2021-08-13 07:43 UTC, gizeasy approved these changes

2021-08-13 10:08 UTC, al-fyodorov approved these changes

2021-08-13 10:11 UTC, merged