feat(Calendar): edit API for onChange and value props
gazprom-neft/consta-uikit pull request #1422
Opened 2021-08-13 11:24 UTC by gizeasy

BREAKING CHANGE:
change Api component: onChange, value

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-08-20 08:14 UTC, al-fyodorov requested changes

2021-08-20 08:14 UTC, al-fyodorov commented on src/components/Calendar/helpers.ts
> +    type?: CalendarPropType;
Зачем оставляем `type`, с одним единственным вариантом? Кроме того сейчас по [API компонента](https://github.com/gazprom-neft/consta-uikit/pull/1422/files#diff-d425681de283ee42f320f30fb0460468864b4b35cfe290fda9703b370d5fafd6R183) он может вернуть только `Date | [Date?, Date?]`, но вот `[Date?, Date?]` он не возвращает, [а всегда только одну дату](https://github.com/gazprom-neft/consta-uikit/pull/1422/files#diff-44455fb2e87057d7ed04d494bd633092349900c42a65d1c431e6cba8eac1a70dR37). Точно ли мы хотим перебросить на внешних разработчиков логику определения какую дату выбрал пользователь?

Примеры как делают другие:
- [Material UI](https://next.material-ui.com/ru/components/date-range-picker/)
- [react-date-range](https://github.com/hypeserver/react-date-range#daterangepicker--daterange)
- [date-range-picker](https://rsuitejs.com/components/date-range-picker)
- [Ant Design](https://ant.design/components/date-picker/)
- [react-daterange-picker](https://github.com/wojtekmaj/react-daterange-picker)

Все кто предоставляет логику выбора двух дат, делает работу с этой функциональностью максимально удобной и упрощенной.

2021-08-20 09:24 UTC, gizeasy commented on src/components/Calendar/helpers.ts
> +    type?: CalendarPropType;
@al-fyodorov 

1) `type`- с одним вариантом
в следующих прах будут добавляться варианты `date-time`, `year`, `month`
2) Есть необходимость перебросить эту функциональность в `DatePicker`, в нем по типу `*-range` будет возвращаться `[Date?, Date?]`, а вот календаре необходимо возвращать только дату кликнутого элемента, так как выбор значения [Date?, Date?] будет проиходить из двух полей `DatePicker`: сначало в одном поле выбрали дату затем в другом, а тообразить надо ренджем в обоих.

2021-08-24 08:09 UTC, arhayka commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +<CalendarExamplePeriod />
У нас везде сначала пример, потом код. Давайте так же сделаем. Или нужно во всем документе поменять.

2021-08-24 08:15 UTC, arhayka commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +### Пример выбора периода дат
#### Пример с выбором периода

2021-08-24 08:17 UTC, arhayka commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +> Свойство `value` описан в [CalendarPropValue](#свойства)
описано

2021-08-24 08:17 UTC, arhayka commented on src/components/Calendar/__stories__/Calendar.docs.mdx
> +> Событие выбора даты описан в [CalendarPropOnChange](#свойства)
описано

2021-08-24 08:36 UTC, al-fyodorov commented on src/components/Calendar/helpers.ts
> +    type?: CalendarPropType;
А где сам компонент DatePicker, не могу в Storybook найти. Кроме того, если пользователь будет использовать только компонент календаря, и ему потребуется эта функциональность, то пусть городит портянку с определением какая дата первая, а какая последняя?

Если календарь публичный компонент и логика самого календаря отвечает за выбор нескольких дат, то он в методе onChange должен возвращать диапазон сразу.

2021-08-24 08:38 UTC, al-fyodorov requested changes
Оставил замечания. Кроме того не очень хорошая практика пока PR в работе в него сливать код из других веток. Надо было сделать ветку feature/calendar и направлять все туда, сейчас в PR мешанина из кучи других задач.

2021-09-01 06:03 UTC, al-fyodorov approved these changes

2021-09-07 07:06 UTC, al-fyodorov approved these changes

2021-09-10 08:02 UTC, arhayka approved these changes

2021-10-06 08:26 UTC, arhayka requested changes

2021-10-06 08:26 UTC, arhayka commented on src/components/DateTimeCanary/__stories__/DateTime.docs.mdx
> +## Настройка вывода времени
Переписала это.  @gizeasy как тебе?

## Выбор времени

В режиме выбора времени (`type="time"`) можно показать часы, минуты и секунды. 
За их настройки отвечают эти свойства:
- часы — `multiplicityHours`,
- минуты — `multiplicityMinutes`, 
- секунды — `multiplicitySeconds`.

По умолчанию значения всех свойств — 1 (выводятся 24 часа, 60 минут, 60 секунд).

Если нужно не показывать секунды или другие единицы, передайте `0` в соответствующем свойстве.

Если хотите ограничить интервал, в котором можно сделать выбор, передайте в соответствующем свойстве шаг между значениями. Например, если в `multiplicityHours` передать `2`, пользователь сможет выбрать только чётные часы — 0, 2, 4 и так далее. А если в `multiplicityMinutes` передать `15`, пользователь увидит только четверти часа.

2021-10-06 09:59 UTC, arhayka approved these changes

2021-10-06 10:58 UTC, merged