feat(Calendar): add CalendarTime
gazprom-neft/consta-uikit pull request #1440
Opened 2021-08-20 10:56 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-08-25 07:51 UTC, al-fyodorov requested changes

2021-08-25 07:51 UTC, al-fyodorov commented on src/components/Calendar/CalendarTime/CalendarTime.css
> +  max-height: 400px;
Есть уже задача, на то чтобы это временное решение выпилить? Если это только для тестирования проверки того как будет выглядеть на момент разработки, то кажется лучше от такой практики отказаться.

2021-08-25 07:51 UTC, al-fyodorov commented on src/components/Calendar/CalendarTime/CalendarTime.tsx
> +export const CalendarTime: React.FC<CalendarTimeProps> = (props) => {
Это скорее больше про выбор времени, а не даты, поэтому не особо понятно почему тут фигурирует календарь. Такой вопрос в привычных для людей календарях есть выбор времени? Скорее сам компонент представляет собой DateTime, потому что календарь больше про выбор года, месяца и дня.

2021-08-25 15:04 UTC, gizeasy commented on src/components/Calendar/CalendarTime/CalendarTime.tsx
> +export const CalendarTime: React.FC<CalendarTimeProps> = (props) => {
создал задачку на переименование
https://github.com/gazprom-neft/consta-uikit/issues/1457

2021-09-01 06:01 UTC, al-fyodorov approved these changes

2021-09-02 09:51 UTC, merged