Bug/textfield
gazprom-neft/consta-uikit pull request #1474
Opened 2021-08-31 16:11 UTC by N1MBER

issue - [#976](https://github.com/gazprom-neft/consta-uikit/issues/976)

## Описание изменений

* Изменен тип описания свойств для компонента TextField (введен запрет на совместное использование свойств rows / minRows&maxRows)
* Изменено описание вышеперечисленных свойств в документации

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-01 08:34 UTC, gizeasy requested changes

2021-09-01 08:34 UTC, gizeasy commented on src/components/Attach/__stories__/examples/AttachExampleBasics/AttachExampleBasics.tsx
> +    <div className={cnDocsDecorator('Section', [cnDocsExample()])}>
Смержись пожалуйста с девом, там все эти изменения есть, их не должно быть в ПРе

2021-09-01 14:43 UTC, gizeasy requested changes

2021-09-01 14:43 UTC, gizeasy commented on src/components/TextField/TextField.tsx
> +    (ref as React.RefObject<HTMLDivElement>) || (textFieldRef as React.RefObject<HTMLDivElement>),
передай туда `textFieldRef` а ниже где нужно `ref`ку на элемент кинуть кидай туда и `ref` который упал с верху компонента и `textFieldRef` через `useForkRef`

таким образом получится без приведений типов, их лучше избегать.

2021-09-01 14:43 UTC, gizeasy commented on src/components/TextField/TextField.tsx
> +  const handleFocus: React.FocusEventHandler<HTMLElement> = (e: React.FocusEvent<HTMLElement>) => {
`(e: React.FocusEvent<HTMLElement>)` можно не описывать тип евента, он сам вывелся из-за того что указал `handleFocus: React.FocusEventHandler<HTMLElement>`

2021-09-01 14:43 UTC, gizeasy commented on src/components/TextField/TextField.tsx
>      onFocus && onFocus(e);
давай заменим на более короткую запись `onFocus?.(e);`

2021-09-08 14:12 UTC, N1MBER commented on src/components/TextField/TextField.tsx
>      onFocus && onFocus(e);
Не понял, что ты имеешь ввиду?

2021-09-10 08:12 UTC, arhayka approved these changes

2021-09-13 08:06 UTC, gizeasy commented on src/components/TextField/TextField.tsx
>      onFocus && onFocus(e);
`onFocus && onFocus(e);` -> `onFocus?.(e);`

2021-09-13 11:21 UTC, N1MBER commented on src/components/TextField/TextField.tsx
>      onFocus && onFocus(e);
Внес изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1474/commits/d7fcddc94c5222d7a404a5ef8859a7a0226799cf)

2021-09-13 11:21 UTC, N1MBER commented on src/components/TextField/TextField.tsx
> +    (ref as React.RefObject<HTMLDivElement>) || (textFieldRef as React.RefObject<HTMLDivElement>),
Внес изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1474/commits/d7fcddc94c5222d7a404a5ef8859a7a0226799cf)

2021-09-13 11:23 UTC, N1MBER commented on src/components/TextField/TextField.tsx
> +  const handleFocus: React.FocusEventHandler<HTMLElement> = (e: React.FocusEvent<HTMLElement>) => {
👍

2021-09-15 12:03 UTC, gizeasy approved these changes

2021-09-15 12:18 UTC, merged