feat(Table): add onRowClick callback
gazprom-neft/consta-uikit pull request #1489
Opened 2021-09-01 12:49 UTC by N1KN

issue - #668

## Описание изменений
Добавил обработчик клика по строке. По клику возвращает id строки.
Обновил документацию и сторибук

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-01 13:42 UTC, gizeasy requested changes

2021-09-01 13:42 UTC, gizeasy commented on src/components/Table/__stories__/Table.docs.mdx
> +| [`onRowClick`](#выделить-строки)                    | `OnRowHover`                                        | -                                                 | Функция которая сработает при наведен
при клике

2021-09-01 14:55 UTC, N1KN commented on src/components/Table/__stories__/Table.docs.mdx
> +| [`onRowClick`](#выделить-строки)                    | `OnRowHover`                                        | -                                                 | Функция которая сработает при наведен
Исправил.

2021-09-03 09:03 UTC, gizeasy approved these changes

2021-09-06 11:36 UTC, merged