feat(Modal, SideBar): close by esc
gazprom-neft/consta-uikit pull request #1498
Opened 2021-09-02 14:02 UTC by N1KN

closes gazprom-neft/consta-uikit#915

## Описание изменений
Добавил колбэк в глобавльную область при открытии

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-03 09:39 UTC, gizeasy requested changes

2021-09-03 09:39 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +  }, [onEsc]);
Еще надо добавить в доку изменения
и кратенько описать то что onEsc должен быть меманизированным колбеком.

2021-09-03 09:39 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +  useEffect(() => {
Давай вынесем в отдельных хук useEsc (hooks/useEsc). Принимать на вход будет handler.

2021-09-10 07:56 UTC, arhayka reviewed
Поправила мелочи, в основном опечатки.

2021-09-10 07:56 UTC, arhayka commented on src/components/Modal/__stories__/Modal.docs.mdx
> +| `container?`                 | `HTMLDivElement, undefined`     | `window.document.body` | Родителький контейнер для модального окна                            |
Родительский — опечатка

2021-09-10 07:56 UTC, arhayka commented on src/components/Modal/__stories__/Modal.docs.mdx
> +| `rootClassName?`             | `string`                        | -                      | Дополнительный CSS-класс корневого DOM елемента                      |
DOM-элемента — опечатка

2021-09-10 07:56 UTC, arhayka commented on src/components/Sidebar/__stories__/Sidebar.docs.mdx
> +| `onEsc?`                     | `(e: KeyboardEvent) => void`       | -                      | Действие при нажатии кнопки **Escape**, когда сайдбар активен |
Действие при нажатии клавиши **Escape**, когда сайдбар открыт

2021-09-10 07:56 UTC, arhayka commented on src/components/Modal/__stories__/Modal.docs.mdx
> +| `onEsc?`                     | `(e: KeyboardEvent) => void`    | -                      | Действие при нажатии кнопки **Escape**, когда модальное окно активно |
Действие при нажатии клавиши **Escape**, когда модальное окно открыто

2021-09-10 07:56 UTC, arhayka commented on src/hooks/useGlobalKeys/__stories__/useGlobalKeys.stories.mdx
> +Этот хук может понадобиться в компонентах, где нужно перехватывать нажатия клавиш глобальной области
Этот хук может понадобиться в компонентах, где нужно перехватывать нажатия клавиш в глобальной области — за пределами компонента. 
Например, чтобы закрыть модальное окно [Modal](/?path=/story/components-modal--playground) по клавише **Esc**.

2021-09-10 10:12 UTC, gizeasy requested changes

2021-09-10 10:12 UTC, gizeasy commented on src/hooks/useGlobalKeys/useGlobalKeys.ts
> +      if (current) {
не нравятся куча условий, да и кажется `current` модно не проверять

может так опишем

```tsx
keyHandlersRef.current[e.code as KeyCode]?.(e);
```
 тогда сократиться все до

```tsx
useEffect(() => {
    const handler = (e: KeyboardEvent) => keyHandlersRef.current[e.code as KeyCode]?.(e);

    document.addEventListener(eventType, handler);

    return () => {
      document.removeEventListener(eventType, handler);
    };
  }, [eventType]);
```

2021-09-10 10:12 UTC, gizeasy commented on src/hooks/useGlobalKeys/useGlobalKeys.ts
> +      if (current) {
и давай еще добавим возможность по key указывать, кажется полезно когда нам не важно с какой стороны был нажат `alt`
![image](https://user-images.githubusercontent.com/13190808/132837809-a0211197-2c97-4eec-b3d6-0b2748308601.png)

тогда както так

```tsx
keyHandlersRef.current[e.code as KeyCode]?.(e);
keyHandlersRef.current[e.key as KeyCode]?.(e);
```

2021-09-10 10:12 UTC, gizeasy commented on src/components/Sidebar/__stories__/Sidebar.stories.tsx
> +  const handleEscPress = callbackWithSelector({ name: 'onEsc' }, () => {
можешь еще во все примеры добавить функцию закрытия модалки

2021-09-10 10:12 UTC, gizeasy commented on src/hooks/useGlobalKeys/useGlobalKeys.ts
> +import { KeyCode } from '../../utils/types/KeyCode';
Просмотрел типы, и увы там не все (((
Необходимо добавить любые клавиши, и кажется от красивой типизации придется отказаться, в угоду функционалу.

2021-09-10 12:07 UTC, gizeasy commented on src/components/Sidebar/__stories__/Sidebar.stories.tsx
> +  const handleEscPress = callbackWithSelector({ name: 'onEsc' }, () => {
В сторибуке есть примеры, добавь в компоненты этих примеров функционал, чтоб модалка закрывалась по esc

2021-09-10 13:58 UTC, gizeasy approved these changes
🔥🔥🔥

2021-09-10 14:00 UTC, merged