feat(TableNumberFilter): added className props
gazprom-neft/consta-uikit pull request #1502
Opened 2021-09-03 09:24 UTC by AntonS86

issue -  1235

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-03 09:49 UTC, gizeasy requested changes

2021-09-03 09:49 UTC, gizeasy commented on src/components/Table/FilterContainer/TableFilterContainer.tsx
> +    <div className={[cnTableFilterContainer('Content'), className].join(' ').trim()}>
cn функция умеет принимать в себя класснамы 
```tsx
cnTableFilterContainer('Content', [className])
```

еще заметил что элемент `Content` лучше не указывать 
сделай так плиз 

```tsx
cnTableFilterContainer(null, [className])
```

и в цсс стили из `Content` в рут перемести

2021-09-03 11:43 UTC, AntonS86 commented on src/components/Table/FilterContainer/TableFilterContainer.tsx
> +    <div className={[cnTableFilterContainer('Content'), className].join(' ').trim()}>
переделал

2021-09-06 11:44 UTC, merged

2021-09-06 11:45 UTC, gizeasy approved these changes