Feat/card
gazprom-neft/consta-uikit pull request #1508
Opened 2021-09-06 09:43 UTC by N1MBER

## Описание изменений

* Добавлен миксин для стилизации карточек
* Добавлен новый компонент Card
* Добавлена небольшая документация для компонента
* Добавлена песочница с кнобами

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-06 13:09 UTC, gizeasy requested changes

2021-09-06 13:09 UTC, gizeasy commented on src/components/Card/Card.tsx
> +    hasShadow = true,
давай уберем `has`

`has`, `is` - конечно нам подсказывают из названия тип, но у нас же TS)) Да и к тому же появится потом выбор из нескольких теней и придется переименовыйвать свойство.

2021-09-06 13:09 UTC, gizeasy commented on src/components/Card/__stories__/Card.docs.mdx
> +| `state`           | `string`                                                | -            | Состояние карточки, в зависимоти от состояния отрисовываются разные границы  |
'alert', 'success', 'warning'

2021-09-06 13:09 UTC, gizeasy commented on src/components/Card/Card.tsx
> +    verticalSpace = cardPropSizeDefault,
надо убрать значения по умолчанию у всего, пусть сами накидывают те свойства которые им нужны

2021-09-07 08:19 UTC, N1MBER commented on src/mixs/MixCard/MixCard.css
> +  &.MixCard_shadow {
Внес изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1508/commits/7e3e7ef864beaf325bb01c675a4966388df18292)

2021-09-07 08:19 UTC, N1MBER commented on src/mixs/MixCard/MixCard.tsx
> +type SizeMap = typeof sizeMap[number];
Внес изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1508/commits/7e3e7ef864beaf325bb01c675a4966388df18292)

2021-09-07 08:43 UTC, arhayka commented on src/components/Card/__stories__/Card.docs.mdx
> +| `state`           | `string`                                                | -            | Состояние карточки, в зависимоти от состояния отрисовываются разные границы  |
в зависимости — в этом слове опечатка

2021-09-07 08:45 UTC, arhayka commented on src/components/Card/__stories__/examples/CardExample/CardExample.tsx
> +      <Text>Something message</Text>
Кажется, это не совсем грамотно, но мы в любом случае договаривались писать примеры на русском. Давай поменяем на что-нибудь такое:

<Text>Здесь может быть ваш текст</Text>

2021-09-07 08:46 UTC, arhayka commented on src/components/Card/__stories__/Card.docs.mdx
> +  <Text>Something message</Text>
Ну и в примере нужно поменять сообщение:
<Text>Здесь может быть ваш текст</Text>

2021-09-07 08:52 UTC, arhayka commented on src/components/Card/__stories__/Card.docs.mdx
> +Карточка — небольшой компонент (в общем смысле) с большими возможностями. Все из-за многообразия вариаций
Хороший текст, поправила мелочи:

Карточка — небольшой компонент с большими возможностями. В него можно поместить что угодно:  таблицу или график, промо-карточку с иллюстрациями или обычный текст. 
Мы не стали стандартизировать наполнение — проекты разные, всем не угодишь. 
Вместо этого сделали карточку в виде «коробки», которая подчиняется правилам тематизации нашей дизайн-системы. В неё можно поместить любой контент —
главное, чтобы контент тоже подчинялся правилам тематизации.

2021-09-08 12:40 UTC, kolebayev commented on src/mixs/MixCard/MixCard.css
> +      border-radius: var(--control-radius);
давайте на бордер радиус

2021-09-08 14:07 UTC, N1MBER commented on src/mixs/MixCard/MixCard.css
> +      padding-bottom: var(--space-xs);
👍

2021-09-08 14:07 UTC, N1MBER commented on src/mixs/MixCard/MixCard.css
> +      padding-top: var(--space-xs);
👍

2021-09-08 14:07 UTC, N1MBER commented on src/mixs/MixCard/MixCard.css
> +      border-radius: var(--control-radius);
👍

2021-09-08 14:07 UTC, N1MBER commented on src/components/Card/Card.css
> +  position: relative;
👍

2021-09-08 14:07 UTC, N1MBER commented on src/components/Card/Card.tsx
> +    hasShadow = true,
👍

2021-09-08 14:07 UTC, N1MBER commented on src/components/Card/__stories__/Card.docs.mdx
> +| `state`           | `string`                                                | -            | Состояние карточки, в зависимоти от состояния отрисовываются разные границы  |
👍

2021-09-08 14:07 UTC, N1MBER commented on src/components/Card/Card.tsx
> +    verticalSpace = cardPropSizeDefault,
👍

2021-09-08 14:08 UTC, N1MBER commented on src/components/Card/__stories__/examples/CardExample/CardExample.tsx
> +      <Text>Something message</Text>
👍

2021-09-08 14:09 UTC, N1MBER commented on src/components/Card/__stories__/Card.docs.mdx
> +  <Text>Something message</Text>
👍

2021-09-08 14:09 UTC, N1MBER commented on src/components/Card/__stories__/Card.docs.mdx
> +Карточка — небольшой компонент (в общем смысле) с большими возможностями. Все из-за многообразия вариаций
👍

2021-09-08 15:33 UTC, gizeasy commented on src/mixs/MixCard/MixCard.css
> +  &_state {
_status

2021-09-08 15:33 UTC, gizeasy commented on src/mixs/MixCard/MixCard.css
> +  &.MixCard_state {
тут не пофиксил

2021-09-08 15:35 UTC, gizeasy requested changes

2021-09-08 15:35 UTC, gizeasy commented on src/components/Card/Card.tsx
> +      className={cnCard({}, [
`cnCard(null ...`

2021-09-08 16:02 UTC, gizeasy requested changes

2021-09-08 16:02 UTC, gizeasy commented on src/components/Card/Card.tsx
> +  } = usePropsHandler(cnCard(), props);
блин не заметил 
`usePropsHandler` тут его не надо, пока хендлер на компонент не напишут

2021-09-08 16:12 UTC, gizeasy requested changes

2021-09-08 16:12 UTC, gizeasy commented on src/mixs/MixCard/MixCard.css
> +
давай еще добавим такую штуку, кажется так лучше будет
```css
&[class*='_verticalSpace']{
   padding-top: var(--vertical-space) ;
   padding-bottom: var(--vertical-space) ;
}

&[class*='_horisontalSpase']{
   padding-left: var(--horisontal-space) ;
   padding-right: var(--horisontal-space) ;
}
```
ну и убрать:
```css
padding: var(--vertical-space, 0) var(--horizontal-space, 0);
border-radius: var(--border-radius, 0);
```

для бордер радиуса тоже самое

2021-09-08 16:13 UTC, gizeasy commented on src/mixs/MixCard/MixCard.css
> +
таким образом пользователь может не включая наши  отступы навешать своих без перепределения стилей

2021-09-08 16:16 UTC, gizeasy requested changes

2021-09-08 16:16 UTC, gizeasy commented on src/mixs/MixCard/MixCard.css
> +  &_status {
```css
&[class*='_status']{
    border: var(--control-border-width) solid var(--border-color);
}
&_status {
   &_alert {
      --border-color: var(--color-bg-alert);
    }
../../..
}
```

2021-09-08 17:03 UTC, merged