feat(Table): added ref to component parameters
gazprom-neft/consta-uikit pull request #1518
Opened 2021-09-07 10:42 UTC by AntonS86

issue -  #1159

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-08 15:03 UTC, gizeasy requested changes

2021-09-08 15:03 UTC, gizeasy commented on src/components/Table/Table.tsx
> +type TableProps<T extends TableRow> = PropsWithHTMLAttributesAndRef<Props<T>, HTMLDivElement>;
и можешь убрать `type Props` оставь только `TableProps` и далее везде его используй, и не чего страшного что там еще в пропсах `ref` будет, и так понятно что ref брать из второго аргумента

2021-09-10 08:13 UTC, arhayka approved these changes

2021-09-13 08:11 UTC, gizeasy requested changes

2021-09-13 08:11 UTC, gizeasy commented on src/components/Table/Table.tsx
> +export type TableProps<T extends TableRow> = PropsWithHTMLAttributesAndRef<
`HTMLAttributes` получается что атрибуты можно указать но они ни где не используются.

``` tsx
const {
    columns,
   ../../..
    isExpandedRowsByDefault = false,
    ...otherProps,
  } = props;

<div {...otherProps}></div>

```

2021-09-15 12:19 UTC, gizeasy approved these changes

2021-09-15 12:20 UTC, gizeasy commented
@AntonS86 Поправь плиз конфликты

2021-09-21 12:20 UTC, merged