feat(Table): Add getTagLabel props
gazprom-neft/consta-uikit pull request #1531
Opened 2021-09-08 15:10 UTC by N1KN

Closes #1190

## Описание изменений

Добавил возможность указать функцию генерирующую текст указанный в "тегах" фильтров.
Добавил это в документацию и привёл пример.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-10 08:41 UTC, arhayka requested changes
Немного поправила формулировки и опечатки. Возможно, часть этих опечаток были в исходном документе.

2021-09-10 08:41 UTC, arhayka commented on src/components/Table/__stories__/Table.docs.mdx
> +# Таблица!
Опс, а зачем тут восклицательный знак?))

2021-09-10 08:41 UTC, arhayka commented on src/components/Table/__stories__/Table.docs.mdx
> +| [`onRowHover`](#выделить-строки)                      | `OnRowHover`                                            | -                                                 | Функция которая сработает при н
Пропущена запятая: 
Функция, которая сработает при наведении на строку

2021-09-10 08:41 UTC, arhayka commented on src/components/Table/__stories__/Table.docs.mdx
> +| [`onRowClick`](#выделить-строки)                      | `OnRowHover`                                            | -                                                 | Функция которая сработает при к
Запятая:

Функция, которая сработает при клике на строку

2021-09-10 08:41 UTC, arhayka commented on src/components/Table/__stories__/Table.docs.mdx
> +### Функция именования тегов фильтрации
Так, немного тут всё поправила. 

### Переименование тегов в фильтрах

Если вы хотите поменять текст в тегах, которые выводятся при фильтрации, — например, чтобы вывести дату в текстовом виде или сократить слишком длинный тег — можно написать свою функцию-обработчик `getTagLabel`.

Он должен принимать 3 аргумента (обязательно в таком порядке):

| Имя аргумента | Тип      | Описание                                               |
| ------------- | -------- | ------------------------------------------------------ |
| `id`          | `string` | `id` фильтра, из которого получены два следующих аргумента  |
| `name`        | `string` | Имя, которое вы указывали в объекте фильтра            |
| `filterValue` | `any`    | Результат фильтрации, например, из кастомного элемента |

В ответ обработчик должен возвращать строку.

2021-09-13 08:40 UTC, gizeasy requested changes

2021-09-13 08:40 UTC, gizeasy commented on src/components/Table/SelectedOptionsList/TableSelectedOptionsList.tsx
> +  values: Array<{ id: string; name: string; value?: any }>;
`value: any`, хотя далее по коду иcпользуется в в функции где есть определенный тип `OptionValue`.
Поищи пожулуйста способы избавиться от any

2021-09-15 12:24 UTC, gizeasy approved these changes

2021-09-23 11:12 UTC, znl8 approved these changes

2021-09-27 14:51 UTC, merged