fix/table_apperance
gazprom-neft/consta-uikit pull request #1550
Opened 2021-09-13 15:05 UTC by AntonS86

## Описание изменений

issue - #871 

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-13 15:49 UTC, gizeasy requested changes

2021-09-13 15:49 UTC, gizeasy commented on src/components/Theme/_color/Theme_color_gpnDefault.css
> +  --color-bg-border: color($color-base-phantom l(-1) a(20%)); /* Цвет границ */
@AntonS86 я так понял в фигме другие цвета были?
@kolebayev где правда, какие цвета оставляем?

2021-09-13 15:49 UTC, gizeasy commented on src/components/Theme/_shadow/Theme_shadow_gpnDark.css
> +.Theme_shadow_gpnDark {
@kolebayev я так понимаю это косяк в фигме? 
Ну уж точно не надо добавлять новые модификаторы к теням

2021-09-13 15:52 UTC, AntonS86 commented on src/components/Theme/_color/Theme_color_gpnDefault.css
> +  --color-bg-border: color($color-base-phantom l(-1) a(20%)); /* Цвет границ */
@gizeasy я установил такие же как в фигме

2021-09-13 16:01 UTC, kolebayev commented on src/components/Theme/_shadow/Theme_shadow_gpnDark.css
> +.Theme_shadow_gpnDark {
@gizeasy у тени три модификатора, новые не надо. в чем тут проблема? не понял

2021-09-13 16:02 UTC, kolebayev commented on src/components/Theme/_color/Theme_color_gpnDefault.css
> +  --color-bg-border: color($color-base-phantom l(-1) a(20%)); /* Цвет границ */
исправление можно принять, давно исправляли, в код не внесли

2021-09-13 16:05 UTC, gizeasy commented on src/components/Theme/_shadow/Theme_shadow_gpnDark.css
> +.Theme_shadow_gpnDark {
тени разные в зависимости от цвета темы по этому добавили модификаторы для каждого отдельного цвета `gpnDark`, `gpnDisplay`

2021-09-15 08:01 UTC, gizeasy requested changes

2021-09-15 08:01 UTC, gizeasy commented on src/components/Theme/_shadow/Theme_shadow_gpnDark.css
> +.Theme_shadow_gpnDark {
вообщем делаем так:
1) в `_color` за водим переменную `$color-base-shadow: #002033;`
2) в `_color` создаем переменные
```css
/*_color_gpnDefault*/

--color-shadow-group-1: color($color-base-shadow a(2%))
--color-shadow-group-2: color($color-base-shadow a(16%))
--color-shadow-layer-1: color($color-base-shadow a(4%))
--color-shadow-layer-2: color($color-base-shadow a(12%))
--color-shadow-modal-1: color($color-base-shadow a(4%))
--color-shadow-modal-2: color($color-base-shadow a(12%))

цвета брать отсюда

https://www.figma.com/file/vNZFtFH6w0IjD2Twi5OXXE/Consta-Default-Colors?node-id=2667%3A45
https://www.figma.com/file/CjGnwm0kwWkW9wSgwPirJA/Consta-Display-Colors?node-id=1732%3A168
https://www.figma.com/file/NgRz8tesBgdad2Lv6kbWEe/Consta-Dark-Colors?node-id=984%3A10
```
2) в `_shadow` оставляем только одну модификацию теней.
```css
.Theme_shadow_gpnDefault {
  --shadow-group: 0 2px 2px var(--color-shadow-group-1), 0 2px 8px var(--color-shadow-group-2);
  --shadow-layer: 0 4px 4px var(--color-shadow-layer-1), 0 8px 24px var(--color-shadow-layer-2);
  --shadow-modal: 0 8px 8px var(--color-shadow-modal-1), 0 12px 28px var(--color-shadow-modal-2);
}
```

2021-09-16 10:19 UTC, gizeasy approved these changes

2021-09-21 09:12 UTC, znl8 approved these changes
Протестировано

2021-09-21 13:34 UTC, merged