feat(SnackBar): Add hideTimer props
gazprom-neft/consta-uikit pull request #1552
Opened 2021-09-14 12:14 UTC by N1KN

Closes #972

## Описание изменений
Добавил пропс для скрытия таймера. Обновил доки и пример.
Если использовать `hideTimer`, то таймер будет работать без визуального отображения, а иконка будет видна, как без `autoClose`.

Если не использовать `hideTimer`, то поведение будет таким-же, как и раньше.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-15 12:59 UTC, gizeasy requested changes

2021-09-15 12:59 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +          hidden={hideAutoCloseTimer}
Давай сверху условие поставим

2021-09-15 12:59 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +    hideTimer,
Не нравятся пропсы когда отключить = true
давай сделаем пропс timer, при его включении будет отображаться таймер, по умолчанию будет включен, в дальнейшем, и добавим предупреждение о том что в дальнейшем поменяется на false, и что лучше сейчас указывать это свойство.

2021-09-15 13:16 UTC, N1KN commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +    hideTimer,
Думал в рамках обратной совместимости, так будет правильно.

Но окей, поправлю

2021-09-15 13:17 UTC, N1KN commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +          hidden={hideAutoCloseTimer}
Не понял

2021-09-15 14:17 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +          hidden={hideAutoCloseTimer}
ну не в нутри компонента будем решать скрыть его или показать а сверху 
```
!hideAutoCloseTimer && <Component/>
```

2021-09-15 14:18 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +    hideTimer,
Да, но если сделать timer=true по умолчанию то тоже все будет хорошо

2021-09-17 09:17 UTC, znl8 approved these changes

2021-09-21 12:35 UTC, gizeasy approved these changes

2021-09-21 12:36 UTC, merged