feat(DateTime): add type month components
gazprom-neft/consta-uikit pull request #1553
Opened 2021-09-14 15:46 UTC by gizeasy

DateTimeTypeMonthViewSlider DateTimeTypeMountViewBook DateTimeTypeMountViewClassic

issue -  #1535 #1537 #1536

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-16 14:37 UTC, gizeasy commented
Нашел ошибку, неверно назвал некоторые компоненты
исправил в этом пре https://github.com/gazprom-neft/consta-uikit/pull/1568

2021-09-17 08:18 UTC, al-fyodorov requested changes

2021-09-17 08:18 UTC, al-fyodorov commented on src/components/DateTime/DateTimeTypeMountViewBook/DateTimeTypeMountViewBook.tsx
> +export const DateTimeTypeMountViewBook: DateTimeTypeViewComponent = React.forwardRef(
Надо подумать как можно объединить эти три вида календаря, book | classic | slider, кажется что наличием или отсутствием чего-то можно управлять через Props, и вроде как не должно слишком тяжело получится. А сейчас у нас примерно 3 компонента с похожим кодом для разных видов.

2021-09-17 08:44 UTC, gizeasy commented on src/components/DateTime/DateTimeTypeMountViewBook/DateTimeTypeMountViewBook.tsx
> +export const DateTimeTypeMountViewBook: DateTimeTypeViewComponent = React.forwardRef(
Я думал над этим и так как верстка в этих компонентах отличается, решил вынести хуки и стили (#1567) и собрать отдельные компоненты с разной версткой которые переиспользуют эти хуки и стили, так как не хотелось городить условий по верстке и делать не нужных пересчетов данных для второй странице календаря в случае с `classic`. Т.е. придется усложнять чтение компонента, а так как в целом `DateTime` большой, лучше максимально делать его простым в чтении (понимании).

Могу поэксперементировать, но пока вижу картину что немного проиграем в производительности и точно потеряем в понимании кода компонента.

2021-09-17 08:47 UTC, gizeasy commented on src/components/DateTime/DateTimeTypeMountViewBook/DateTimeTypeMountViewBook.tsx
> +export const DateTimeTypeMountViewBook: DateTimeTypeViewComponent = React.forwardRef(
@al-fyodorov Я думаю что такая декомпозиция только на пользу)))

2021-09-17 14:33 UTC, al-fyodorov commented on src/components/DateTime/DateTimeTypeMountViewBook/DateTimeTypeMountViewBook.tsx
> +export const DateTimeTypeMountViewBook: DateTimeTypeViewComponent = React.forwardRef(
Да, а сколько надо раз внести общее изменение в коде и верстке для всех компонентов? Как проследить что во все были внесены изменения? Насколько критично если при исправлении или добавлении новой фичи в текущий код что-то пойдет не так и в одном из компонентов что-то будет ломаться из-за того что забыли что-то в него добавить.

Декомпозицияя это очень здорово, но она должна быть правильной, когда у тебя появляются одинаковые кусочки кода, но с немного разной логикой, то надо подумать можно ли как-то эти кусочки объединить, чтобы сохранить и производительность и читаемость, и при этом не усложнять во много раз поддержку этих компонентов.

Сейчас уже компонентов очень уж много.

2021-09-24 07:17 UTC, al-fyodorov approved these changes

2021-09-24 07:21 UTC, merged