Feat/layout
gazprom-neft/consta-uikit pull request #1554
Opened 2021-09-14 19:43 UTC by N1MBER

## Описание изменений

* Добавлен новый компонент Layout
* Добавлена песочница
* Сделана первоначальная версия документации

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-15 11:42 UTC, gizeasy requested changes

2021-09-15 11:42 UTC, gizeasy commented on src/components/Layout/Layout.tsx
> +        maxWidth: stationing.width,
нужно style из пропсов развернуть сюда до твоих стилей

2021-09-15 11:42 UTC, gizeasy commented on src/components/Layout/Layout.tsx
> +  const handleScroll = () => {
и хук вынести const {fixed,top,left} = useFixed(ref);

2021-09-15 12:04 UTC, N1MBER commented on src/components/Layout/Layout.tsx
> +  const [isFixed, setIsFixed] = useState(false);
У нас отдельно есть пропс fixed, а этот стэйт определяет при fixed становится ли элемент фиксированным, если он находится в поле видимости

2021-09-21 12:24 UTC, N1MBER commented on src/components/Layout/Layout.tsx
> +  const handleScroll = () => {
Сделал изменения, последние [3 коммита](https://github.com/gazprom-neft/consta-uikit/pull/1554/commits/c7750de53a2694a29ff0b258495a1c2ee99cd69c)

2021-09-21 12:24 UTC, N1MBER commented on src/components/Layout/Layout.tsx
> +      handleScroll();
Сделал изменения, последние [3 коммита](https://github.com/gazprom-neft/consta-uikit/pull/1554/commits/c7750de53a2694a29ff0b258495a1c2ee99cd69c)

2021-09-21 14:02 UTC, gizeasy requested changes

2021-09-21 14:02 UTC, gizeasy commented on src/components/Layout/Layout.tsx
> +export const Layout = forwardRefWithAs<Props>((props, ref) => {
еще при быстром скролинге возникают артифакты в виде проявления белой области на долю секунды, кажется это можно избежать если на фековый элемент навешивать бэкгрануд  фиксированого элемента

2021-09-21 14:05 UTC, gizeasy requested changes

2021-09-21 14:05 UTC, gizeasy commented on src/components/Layout/Layout.css
> +  &-Mock {
думаю что лучше подходит fake

2021-09-22 16:28 UTC, N1MBER commented on src/components/Layout/Layout.tsx
> +export const Layout = forwardRefWithAs<Props>((props, ref) => {
Исправил в этом [коммите](https://github.com/gazprom-neft/consta-uikit/pull/1554/commits/421c1df249dcdd1705fa4ad3d59a4b3975223813)

2021-09-22 16:29 UTC, N1MBER commented on src/components/Layout/Layout.tsx
> +import { useFixed, UseFixedData } from '../../hooks/useFixed/useFixed';
Добавил тесты в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1554/commits/e23c153c5904329542db1b6ce805077f2fb75630)

2021-09-27 15:42 UTC, gizeasy requested changes

2021-09-27 15:42 UTC, gizeasy commented on src/components/Layout/Layout.tsx
> +import './Layout.css';
Переместить компонент в папку LayoutCanary

2021-09-27 15:42 UTC, gizeasy commented on src/components/Layout/Layout.tsx
> +                flex,
давай будем задавать css переменные 
```
['--layout-flex' as string]: flex
```

2021-09-27 15:42 UTC, gizeasy commented on src/components/Layout/Layout.tsx
> +            backgroundColor:
расчет backgroundColor вынеси выше `return` в константу

2021-09-27 15:42 UTC, gizeasy commented on src/components/Layout/useFixed.ts
> +              scrollContainerStationing.offsetHeight +
Думаю эти все условия можно вынести в отдельные функции и назвать их так чтобы по названию было понятно что конкретно проверяем

2021-09-28 07:29 UTC, gizeasy requested changes

2021-09-28 07:29 UTC, gizeasy commented on src/components/LayoutCanary/useFixed.ts
> +  const getHTMLElement: GetHTMLFunction = (element) => {
вытащи функцию за тело useFixed

2021-09-28 07:29 UTC, gizeasy commented on src/components/LayoutCanary/useFixed.ts
> +  const getStationingElement = (
вытащи функцию за тело useFixed

2021-09-28 07:29 UTC, gizeasy commented on src/components/LayoutCanary/Layout.tsx
> +export type Props = {
LayoutProps

2021-09-28 11:11 UTC, N1MBER commented on src/components/LayoutCanary/Layout.tsx
> +export type Props = {
Исправил в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1554/commits/77229ccc9e3ad32cfd51a5e65930226911155708)

2021-09-28 11:11 UTC, N1MBER commented on src/components/LayoutCanary/useFixed.ts
> +  const getHTMLElement: GetHTMLFunction = (element) => {
Исправил в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1554/commits/77229ccc9e3ad32cfd51a5e65930226911155708)

2021-09-29 09:09 UTC, gizeasy approved these changes

2021-09-29 09:10 UTC, merged