feat(Table): Add getComparisonValue function
gazprom-neft/consta-uikit pull request #1570
Opened 2021-09-16 21:32 UTC by N1KN

Closes #987

## Описание изменений
Добавил возможность указать свою функцию генерации значения которое сравнивается при объединении строк.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-17 15:12 UTC, gizeasy requested changes

2021-09-17 15:12 UTC, gizeasy commented on src/components/Table/__stories__/Table.stories.tsx
> +              getComparisonValue: (cell: string) => cell.toLowerCase(),
сделай посложнее пример
```tsx
rows: [ 
           {
              id: '1',
              randomCaseText: {
                type: 'check',
                value: true,
              },
            }, 
            {
              id: '2',
              randomCaseText: {
                type: 'check',
                value: true,
              },
            }, 
            {
              id: '3',
              randomCaseText: {
                type: 'check',
                value: false,
              },
            }
....

 getComparisonValue: ({type,value}) => `${type}-${value}`,
```

и в рендер функции отрендери checkBox

2021-09-20 13:11 UTC, N1KN commented
Исправил функцию `getTableCellProps`, т.к. в ней происходили лишние проходы цикла

2021-09-22 08:44 UTC, gizeasy approved these changes

2021-09-22 14:52 UTC, znl8 requested changes
При попытке в colomns указать "mergeCells": false возникает вот такая ошибка
![image](https://user-images.githubusercontent.com/90449435/134367016-c423cc83-d041-4b5a-b468-c921b5445126.png)

2021-09-24 09:10 UTC, gizeasy requested changes

2021-09-24 09:10 UTC, gizeasy commented on src/components/Table/__stories__/Table.docs.mdx
> +### Со своей функцией генерации признака объединения
Давай под примером оставим ссылку на пример в сторибуке, код и то что по ссылке должны быть одиноковые компоненты. В примере убери кнобы

2021-09-27 14:47 UTC, gizeasy approved these changes

2021-09-27 14:48 UTC, merged