feat(SnackBar): Adding the ability to pass a React component
gazprom-neft/consta-uikit pull request #1574
Opened 2021-09-17 14:21 UTC by N1KN

Closes #997

## Описание изменений
Добавлена возможность передать в качестве сообщения `ReactNode`

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-17 14:55 UTC, gizeasy requested changes

2021-09-17 14:55 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +В качестве значения можно передавать текст или реакт-компонент[`React.ReactNode`], например ссылку `<a href="#">Ссылка</a>`
ну не компонент же)))
напиши - разметку JSX[`React.ReactNode`]

2021-09-17 14:55 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.tsx
> +        {typeof message === 'string' || typeof message === 'number' ? (
возми из type-guards isNumber и добавь туда плиз isString

2021-09-22 07:21 UTC, znl8 approved these changes
Протестировано

2021-09-22 08:46 UTC, gizeasy approved these changes

2021-09-27 14:45 UTC, gizeasy approved these changes

2021-10-01 10:50 UTC, merged