Feat/choice group disable
gazprom-neft/consta-uikit pull request #1575
Opened 2021-09-20 08:12 UTC by AntonS86

issue - #434 

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-22 09:24 UTC, gizeasy requested changes

2021-09-22 09:24 UTC, gizeasy commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  &-Label.ChoiceGroup-Label_disabled {
Как то сложно для чтения стало.
Что если для каждого элемента и его сотояния заведем отделюную переменную
типа 
--choice-bg-color
--choice-bg-color-checked
--choice-bg-color-disabled
--choice-text-color
--choice-text-color-checked
--choice-text-color-disabled
отдельно переменные для разделителя

описать поведение без всяких css усилений на этих переменных
а переменные меняются в зависимости от модификатора

примерно как тут 
https://github.com/gazprom-neft/consta-uikit/blob/feat/reserch-api/src/components/DateTime/DateTimeItem/DateTimeItem.css

т.е. идея в том чтобы не параметры цсс переопределять а переменные.
а они уже будут присваиваться 

```css
.ChoiceGroup{
     &_view {
       &_primary {
          --choice-bg-color: var(...);
          --choice-bg-color-checked: var(...);
          --choice-bg-color-disabled: var(...);
       }

     ...//...//...
    
    &-Label{
       background-color: var(--choice-bg-color);
       &_checked{
           background-color: var(--choice-bg-color-checked);
       }
       &_disabled{
           background-color: var(--choice-bg-color-disabled);
       }
       
    }
}
```

2021-09-22 09:31 UTC, gizeasy commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  &-Label.ChoiceGroup-Label_disabled {
Пока ни чего не делай, дизайн подождем

2021-09-22 10:42 UTC, AntonS86 commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  &-Label.ChoiceGroup-Label_disabled {
ок, ждем дизайн

2021-09-27 09:14 UTC, gizeasy commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  &-Label.ChoiceGroup-Label_disabled {
@kolebayev нам нужен дизайн.

2021-09-29 10:06 UTC, kolebayev commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  &-Label.ChoiceGroup-Label_disabled {
@gizeasy https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=5156%3A79694

2021-10-01 11:04 UTC, gizeasy requested changes

2021-10-01 11:04 UTC, gizeasy commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  --choice-group-bg-color: transparent;
При выбранном item и задизейбленном не видно что элемент выбран
должно быть

![image](https://user-images.githubusercontent.com/13190808/135609206-ae4b071c-4502-416b-ae20-bc031733f789.png)

сейчас
![image](https://user-images.githubusercontent.com/13190808/135609283-cd14681d-cfd3-4e76-8b98-26379991234e.png)

при view secondary так
![image](https://user-images.githubusercontent.com/13190808/135609416-760a7acd-c236-43e2-bca5-86f9c72b85a8.png)

кажется что надо отдельный элемент для выбранного рендерить, и красить его отдельно.
Разделитель думаю тоже стоит отдельным элементом рендерить вне айтема

Время по задачки еще осталось?
кажется что это замечание тянет на рефакторинг

2021-10-01 11:09 UTC, AntonS86 commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  --choice-group-bg-color: transparent;
нужен цвет в кокой красить отдельный элемент, потому что когда мы дисаблим группу у нас происходит наложение цвета группы на выбранный, а когда дисаблим отдельно элемент, ты присваиваем цвет элементу

2021-10-01 11:34 UTC, gizeasy commented on src/components/ChoiceGroup/ChoiceGroup.css
> +  --choice-group-bg-color: transparent;
по этому я предлагаю отдельным элементом сверху закрашивать

2021-10-04 11:01 UTC, merged