feat(Sidebar): added property 'size'
gazprom-neft/consta-uikit pull request #1588
Opened 2021-09-21 15:26 UTC by AntonS86

remove property 'width' and 'height'

issue -  #1292

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-22 10:03 UTC, gizeasy requested changes

2021-09-22 10:03 UTC, gizeasy commented on src/components/Sidebar/Sidebar.tsx
> +  const size = React.useMemo(() => {
зачем мемонизировать результат такой простой функции? 
да и вообще кажется лишним доставать результат который равен ключу

2021-09-22 10:03 UTC, gizeasy commented on src/components/Sidebar/Sidebar.tsx
> +  '1-of-4': '1-of-4',
что думаешь если  переименуем `1-of-4` -> `1/4`

2021-09-22 10:17 UTC, gizeasy requested changes

2021-09-22 10:17 UTC, gizeasy commented on src/components/Sidebar/Sidebar.css
> +  --sidebar-width-min: var(--sidebar-size-s);
думаю не нужно описывать тут `--sidebar-width` `--sidebar-height` так как они постоянно будут перепрелделятся из-за модификатора size

2021-09-22 10:17 UTC, gizeasy commented on src/components/Sidebar/Sidebar.css
> +  --sidebar-width-min: var(--sidebar-size-s);
`--sidebar-width-min` и `--sidebar-height-min` вообще можно убрать так как его ни где не переопределяем и модно просто писать 100vh или 100vw

2021-09-22 10:43 UTC, AntonS86 commented on src/components/Sidebar/Sidebar.tsx
> +  '1-of-4': '1-of-4',
ок, давай переименуем

2021-09-24 09:19 UTC, znl8 approved these changes
Протестировано

2021-09-27 13:47 UTC, gizeasy requested changes

2021-09-27 13:47 UTC, gizeasy commented on src/components/Sidebar/Sidebar.css
> +        &.Sidebar-Window_size {
чтото мне не нравится запись 
&.Sidebar-Window_size кажется можно просто модификатор размера вне зависимости от позиции. А позиции применять ту или иную переменную.
```css
&_size{
    &_s {
            --sidebar-width: var(--sidebar-size-s);
            --sidebar-height: var(--sidebar-size-s);
     }
}
```

2021-09-28 08:25 UTC, AntonS86 commented on src/components/Sidebar/Sidebar.css
> +        &.Sidebar-Window_size {
ок переделал

2021-09-28 09:13 UTC, gizeasy approved these changes

2021-09-28 09:13 UTC, merged