Feat/field label
gazprom-neft/consta-uikit pull request #1606
Opened 2021-09-27 15:00 UTC by N1MBER

## Описание изменений

* Добавлены новые компоненты FieldLabel & FieldCaption
* Добавлены миксины (MixLabel, MixCaption) для стилизации компонентов использующих новые компоненты
* Дополнена документация для компонентов TextField, UserSelect, Select, Combobox
* Поправлены тестов для компонентов из выше идущего списка  

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-28 08:14 UTC, gizeasy requested changes

2021-09-28 08:14 UTC, gizeasy commented on src/components/Text/Text.tsx
> +export type Props = {
TextProps

2021-09-28 08:14 UTC, gizeasy commented on src/mixs/MixCaption/MixCaption.css
> +      margin-left: 7px;
скорее всего в фигме косяк и надо переделать на переменный space
и лучше такое делать через присвоение к переменной

2021-09-28 15:31 UTC, N1MBER commented on src/mixs/MixCaption/MixCaption.css
> +      margin-left: 7px;
@kolebayev У нас в дизайне отступы идут 7, 9, 11, 13px, можешь подсказать что из переменных стоит взять (похожей ранжировки не нашел)

2021-09-29 09:26 UTC, N1MBER commented on src/components/Combobox/Combobox.tsx
> +        <SelectContainer
Внес изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/d1302263babe63ccc00a12b4a8b79ab6d65f87db)

2021-09-29 09:26 UTC, N1MBER commented on src/components/Combobox/__stories__/Combobox.docs.mdx
> +| [`label?`](#лэйбл)                                        | `string`                                               | -                                                             | см. [TextField](
Внес изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/d1302263babe63ccc00a12b4a8b79ab6d65f87db)

2021-09-29 10:03 UTC, gizeasy requested changes

2021-09-29 10:03 UTC, gizeasy commented on src/components/Combobox/__stories__/examples/ComboboxExampleLabel/ComboboxExampleLabel.tsx
> +import React, { useState } from 'react';
В селекты в сторибук тоже добавь кнобы с лейблом и кепшном

2021-09-29 10:03 UTC, gizeasy commented on src/mixs/MixLabel/MixLabel.css
> +.MixLabel {
Подумал по поводу миксинов, вообще зачем они и тп.
Вообщем такие большие блоки не стоит выносить в миксины, из cn функции можно брать и из компонента
кажется с карточкой погоречились. Лучше в пиксинах оставлять такие штуки как просто добавление отступов и выравнивание и тп. 

Прибери этот код в компонент

2021-09-29 10:03 UTC, gizeasy commented on src/mixs/MixLabel/MixLabel.css
> +.MixLabel {
С кепшном тодже самое

2021-09-29 11:51 UTC, N1MBER commented on src/components/SelectComponents/Select.css
> +      & .FieldLabel {
Добавил в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/98391004ed26813f3e1f99107539a8708d310d9f)

2021-09-29 11:51 UTC, N1MBER commented on src/components/SelectComponents/Select.css
> +  &_labelAlign {
Добавил в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/98391004ed26813f3e1f99107539a8708d310d9f)

2021-09-29 11:51 UTC, N1MBER commented on src/components/SelectComponents/Select.css
> +        height: var(--field-label-height);
Добавил в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/98391004ed26813f3e1f99107539a8708d310d9f)

2021-09-29 12:03 UTC, gizeasy requested changes

2021-09-29 12:17 UTC, N1MBER commented on src/components/FieldLabel/FieldLabel.css
> +.FieldLabel {
Фикс в [ласт коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/da66d0cac3334d19594e3ba8ee99582ba7d5e69d)

2021-09-29 13:37 UTC, gizeasy requested changes

2021-09-29 13:37 UTC, gizeasy commented on src/components/FieldCaption/FieldCaption.css
> +.FieldCaption {
У `Text` есть модификатор view который умеет краситься в эти-же цвета.
тебе надо смапить `_status` в `_view`

2021-09-29 13:37 UTC, gizeasy commented on src/components/FieldCaption/FieldCaption.tsx
> +type FieldCaptionProps = Omit<TextProps, ExcludeProps> & {
Не совсем понял зачем наделять всеми пропсами компонента Text, нам нужно с него только его `_view` 
и то мапнутый под свой тип. В итоге: компонент должен принимать все что принимает его тэг и `_status`

2021-09-29 13:37 UTC, gizeasy commented on src/components/FieldLabel/FieldLabel.tsx
> +type FieldLabelProps = Omit<TextProps, ExcludeProps> & {
Также, не надо наделять всеми свойствами Text
тебе же нужен только размер и все свойства тега

2021-09-29 13:37 UTC, gizeasy commented on src/components/FieldLabel/FieldLabel.tsx
> +export const fieldLabelPropPosition = ['top', 'left'] as const;
`fieldLabelPropPosition` не используется в компоненте да и не нужен тут, в компоненте должны быть только те модификаторы которые влияют на его внутренности, позиционировать компонент мы всегда можем сверху.

2021-09-29 13:37 UTC, gizeasy commented on src/components/FieldCaption/FieldCaption.css
> +.FieldCaption {
то есть можно вообще стили удалить

2021-09-29 13:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
> +      --input-space: calc(var(--control-space-xs) * 0.5);
`--input-space` обьявлен дважды

2021-09-29 13:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
> +  &_position {
`_labelPositon`

2021-09-29 13:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
> +        margin-bottom: var(--space-xs);
оставил этот момент

2021-09-29 13:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
> +      & .Select-Label {
Теперь когда у тебя есть `-Label` ты можешь ему добавить модификатор который будет отвечать за его позиционирование, и без всяких сложных селекторов описать ему стили при разных позициях.

2021-09-29 13:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
> +  &-CaptionContainer {
странное название, может по простому?
Label
Body
Caption

2021-09-29 13:49 UTC, gizeasy requested changes

2021-09-29 13:49 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
>  export const WithRender = createStory(
Добавь пожалуйста дефолтные значения для `label` и `caption`

2021-09-29 13:49 UTC, gizeasy commented on src/components/SelectComponents/Select.css
>  .Select {
Заметил что у селектов нет поля `_state` давай добавим, пока это все трогаем или отдельным пром зашлем?

2021-09-29 14:54 UTC, N1MBER commented on src/components/Combobox/__stories__/Combobox.stories.tsx
>  export const WithRender = createStory(
Изменения в [этом коммите](https://github.com/gazprom-neft/consta-uikit/pull/1606/commits/f6e7e34da573d1f71b39dbd268fe807bf757beb2)

2021-09-29 15:37 UTC, gizeasy requested changes

2021-09-29 15:37 UTC, gizeasy commented on src/components/FieldCaption/FieldCaption.tsx
> +export const fieldCaptionPropStatusDefault: FieldCaptionPropStatus = 'alert';
`fieldCaptionPropStatusDefault` не используется в компоненте

2021-09-29 15:37 UTC, gizeasy commented on src/components/FieldLabel/FieldLabel.tsx
> +export const fieldLabelPropSizeDefault: FieldLabelPropSize = 'm';
`fieldLabelPropSizeDefault` не используется в компоненте

2021-09-29 15:37 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.docs.mdx
> +```ts
tsx

2021-09-29 15:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
>  .Select {
завел

2021-09-29 15:37 UTC, gizeasy commented on src/components/SelectComponents/Select.css
>  .Select {
в combobox и userSelect сломалось выравнивание
![image](https://user-images.githubusercontent.com/13190808/135301447-b05a65a0-67bf-4cd2-8256-091c4ea929ff.png)
![image](https://user-images.githubusercontent.com/13190808/135301552-127ef388-a4cb-4215-b3cb-d23843d42bbf.png)

2021-10-01 12:48 UTC, gizeasy approved these changes

2021-10-01 12:51 UTC, merged