Feat/progress step bar
gazprom-neft/consta-uikit pull request #1643
Opened 2021-10-06 12:22 UTC by N1MBER

## Описание изменений

* Добавлен новый компонент ProgressStepBar
* Добавлена документация для компонента, а также песочница

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-10-11 14:19 UTC, gizeasy requested changes

2021-10-11 14:19 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBar.tsx
> +            getItemContent={getItemContent}
В item лучше передавать уже готовые данные, чтоб он их просто рисовал, 
можешь сделать функцию на вход которой будут падать просы компонента и item, а результатом, будет готовый обьект с данными.

2021-10-11 14:19 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBar.tsx
> +      <div
А давай линию тоже в отдельный компонент приберем?

2021-10-11 14:19 UTC, gizeasy commented on src/components/ProgressStepBar/helpers.ts
> +export const defaultGetItemKey: PropGetItemKey<DefaultItem> = (item) => item.id;
А давай defaultGetItemKey будет возвращать index элемента по умолчанию, тогда типы надо будет поправить, убрать условие на id в элементе. Кажется так лучше всего будет и не навязываем проброс id и если надо то можно указать.

2021-10-11 14:19 UTC, gizeasy commented on src/components/ProgressStepBar/helpers.ts
> +  onClick?: React.EventHandler<React.MouseEvent>;
давай onClick вынесем в пропсы компонента, чтоб каждый раз не пересобирать массив items,

onItemClick({ e, item, index }) => void

2021-10-11 14:19 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBar.tsx
> +function ProgressStepBarRender<ITEM = DefaultItem>(
![image](https://user-images.githubusercontent.com/13190808/136806065-61616e10-9544-437e-bc43-8e126878a3f7.png)

при указании контента, верстка поехала

2021-10-12 14:00 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +export const ProgressStepBarItem = forwardRef(ProgressStepBarItemRender) as StepComponent;
Так как компонент стал без дженериков можно отказаться от этого приведения и просто завернуть компонент в forwardRef

2021-10-12 14:01 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +          spareDirection={direction === 'horizontal' ? 'upCenter' : 'rightUp'}
Кажется что тултип надо показывать как при наведении на точку так и при наведении на заголовок

2021-10-12 14:03 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +        {step.point?.toString()[0]}
А смысл в этой записи если мы типами запретили?

2021-10-19 10:12 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.css
> +    & .ProgressSpin {
`& .ProgressSpin`
А это зачем? Без него плавно крутиться

2021-10-19 10:14 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +          className={cnProgressStepBarItem('Point', {
давай накрутим еще cnMixFocus()
чтоб при фокусе наше выделение было, а не стандартное браузерное

2021-10-19 10:17 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +  const [isContentHidden, setIsContentHidden] = useState<boolean>(true);
не совсем понял зачем `isContentHidden`

2021-10-19 10:17 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +        <button
Давай использовать `button` толко тогда когда указан `onItemClick`

2021-10-19 10:18 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +    onItemClick,
тут оточнение onItemClick лишнее можно просто оставить onClick

2021-10-19 10:35 UTC, gizeasy commented on src/components/ProgressStepBar/__stories__/ProgressStepBar.docs.mdx
> +  lineStatus?: 'normal' | 'success' | 'alert' | 'warning';
кажется что lineStatus лишнее, кажется что линия должна окрашиваться в цвет статуса точки
и что точка должна принимать статус только в том случае если она активная, в остальных случаях она серая

@kolebayev что думаешь?

2021-10-19 10:41 UTC, gizeasy commented on src/components/ProgressStepBar/helpers.ts
> +  point?: PointNumbersMap | SVGElement;
point -> label
думаю что лучше label будет

в макете есть строгие размеры к иконке, поэтому думаю лучше использовать `React.FC<IconProps>` то есть наши иконки.

2021-10-20 11:06 UTC, N1MBER commented on src/components/ProgressStepBar/ProgressStepBar.css
> +.ProgressStepBar {
Исправил в последнем коммите

2021-10-20 11:06 UTC, N1MBER commented on src/components/ProgressStepBar/helpers.ts
> +  point?: PointNumbersMap | SVGElement;
Исправил в последнем коммите

2021-10-20 14:44 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +        className={cnProgressStepBarItem('Point-Text')}
у элемента не может быть элемента
они все элементы одного блока
ProgressStepBarItem-PointText
```css
.ProgressStepBarItem{
&-PointText{
}
}
```

2021-10-20 14:45 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +const getPointContent = (
renderPointContent

2021-10-20 14:47 UTC, gizeasy commented on src/components/ProgressStepBar/ProgressStepBarItem/ProgressStepBarItem.tsx
> +          <button type="button" {...pointButtonProps} {...pointProps} />
надо указывать пропсы в одном месте
либо все что оносится к `button` укажи в разметрке либо все в `pointButtonProps`

2021-10-20 18:50 UTC, merged