Custom params
gazprom-neft/consta-uikit pull request #1724
Opened 2021-11-09 10:21 UTC by RuWolf

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-11-10 11:23 UTC, gizeasy requested changes

2021-11-10 11:23 UTC, gizeasy commented on src/components/Button/Button.tsx
> +  customAnalyticsData?: {
Когда мы планировали интеграцию Аналитики в конста, мы договорились что не будем менять Api компонентов, и если что потребуется будем использовать дата-атрибуты, в этом Пре есть изменение Api.
Давайте пойдем обговоренным путем:
Вы будете использовать дата атрибуты

```tsx
<Button
  label="Кнопка"
  data-analitic-name="хеш кнопки"
  data-analitic-type="тип кнопки"
  data-analitic-value="значение кнопки"
/>
```

А в `useButtonEventHandler` прокинуть эти поля в клик или куда еще необходимо
```tsx
newProps.onClick = (...onClickArgs) => {
    const [e] = onClickArgs;
    const value = {
      component: COMPONENT_NAME,
      event: e.type,
      options: {
        text: (e.currentTarget as HTMLButtonElement).innerText,
        pageURL: e.currentTarget.baseURI,
        DOMRef: ref?.current,
       /// тут пробросить кастомные поля в клик
       dataAnalitic: {
         name: props['data-analitic-name'],
         type: props['data-analitic-type'],
         type: props['data-analitic-value'],
       },
      },
    };
    handler!(value);

    return props.onClick?.(...onClickArgs);
  };
```

для описания дата атрибутов можете создать отдельный тип
и прибавить его к типам компонентов где это необходимо

2021-11-10 11:23 UTC, gizeasy commented on src/components/Button/__stories__/Button.docs.mdx
> +type PropCustomAnalyticsData = {
В документации не указываем пропсы аналитики, в дальнейшем выпустим отдельную доку для этого

2021-11-11 11:36 UTC, gizeasy requested changes

2021-11-11 11:36 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/useButtonEventHandler.tsx
> +        dataAnalyticAttributes: getDataAnalyticsAttribute(newProps),
Мы тут еще подумали как лучше будет. И решили просто вообще все пропсы прокидывать. 
Извини, сразу не подумали ((
Так же если вам удобнее по другому то вы всегда можете кинуть своих функций в EventInterceptorProvider в свойство `map`

2021-11-11 11:58 UTC, RuWolf commented on src/components/EventInterceptor/propsHandlers/useButtonEventHandler.tsx
> +        dataAnalyticAttributes: getDataAnalyticsAttribute(newProps),
Т.е не отбирать пропсы дата атрибутов, а передавать все?
Пример
```
const value = {
      component: COMPONENT_NAME,
      event: e.type,
      options: {
        text: (e.currentTarget as HTMLButtonElement).innerText,
        pageURL: e.currentTarget.baseURI,
        DOMRef: ref.current,
        props: newProps,
      },
    };
```
А по поводу прокидывания своих функций в EventInterceptorProvider в свойство map. Не совсем понятно, т.е если у нас 60 клиентов, то придется всем внедрять кастомный eventInterceptorMap?

2021-11-11 12:27 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/useButtonEventHandler.tsx
> +        dataAnalyticAttributes: getDataAnalyticsAttribute(newProps),
1) да
2) да, вы можете сделать npm пакет для своих клиентов и внедрить уже везде

2021-11-12 08:33 UTC, gizeasy approved these changes

2021-11-15 09:33 UTC, merged