Feat/slider
gazprom-neft/consta-uikit pull request #1726
Opened 2021-11-09 11:53 UTC by N1MBER

## Описание изменений

issue - #1694 

Добавлены:
* Компонент Slider  c его элементами SliderLine & SliderPoint
* Добавлены два хука для работы компонента:
1. useSlider - отвечает за логику работы слайдера
2. useSliderStationing - отвечает за получение параметров для отрисовки компонента
* Добавлена документация с рядом примеров

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-11-11 13:06 UTC, gizeasy requested changes

2021-11-11 13:06 UTC, gizeasy commented on src/components/Slider/SliderLine/SliderLine.css
> +        border-radius: var(--control-radius);
создай переменную отвечающую за радиус и ее меняй
и саму переменную укажи в `SliderLine-Line`

при `_default` можешь не на элементы кинуть бордеры а блок с оферфлоу хиден

2021-11-11 13:06 UTC, gizeasy commented on src/components/Slider/SliderPoint/SliderPoint.css
> +    z-index: 2;
А нужен z-index? кажется без него можно обойтись

2021-11-11 13:06 UTC, gizeasy commented on src/components/Slider/SliderPoint/SliderPoint.css
> +    z-index: 2;
Пропиши стили для плавного перемещения тултипа

2021-11-18 12:27 UTC, gizeasy requested changes

2021-11-18 12:27 UTC, gizeasy commented on src/components/Slider/SliderPoint/SliderPoint.tsx
> +  const tooltipThemeClassNames = generateThemeClassNames(tooltipTheme);
можешь `tooltipThemeClassNames` и `tooltipTheme` в обном месте описать, а то сейчас разнесено. может вообще отделный хук создать который просто возвращает готовую тему

2021-11-18 12:27 UTC, gizeasy commented on src/components/Slider/Slider.css
> +  width: 100%;
![image](https://user-images.githubusercontent.com/13190808/142414197-98fe0f34-dc2a-4b81-a410-5d429b209e69.png)
при изменение в инпуте, полосочка не меняется

2021-11-18 12:27 UTC, gizeasy commented on src/components/Slider/Slider.css
> +  width: 100%;
![image](https://user-images.githubusercontent.com/13190808/142414349-16e7479b-c859-489d-a9ca-e60ff5535fe9.png)
косяк с позиционированием тултипа остался

2021-11-18 12:27 UTC, gizeasy commented on src/components/Slider/Slider.tsx
> +    return () => stopListening();
return stopListening;

или даже можешь в хуке `useSlider` это оставить, пусть в одном месте и подписка и отписка будет

2021-11-18 12:27 UTC, gizeasy commented on src/components/Slider/helper.ts
> +  rightSide?: React.FC<IconProps> | 'input';
давай справа только иконку, Илюха говорит толко слева можно инпут

2021-11-18 13:46 UTC, N1MBER commented on src/components/Slider/SliderInput/SliderInput.tsx
> +  const [currentValue, setCurrentValue] = useState<string | null>();
Состояние необходимо, так как мы с тобой договорились что положение ползунка изменяется только на блюре, а  отслеживать value нужно так как мы можем изменить значение через ползунок, а в инпукте оно не поменяется

2021-11-19 08:15 UTC, N1MBER commented on src/components/Slider/Slider.css
> +  width: 100%;
Исправил в последнем кормите

2021-11-19 08:16 UTC, N1MBER commented on src/components/Slider/SliderPoint/SliderPoint.tsx
> +  const tooltipThemeClassNames = generateThemeClassNames(tooltipTheme);
👍

2021-11-29 11:33 UTC, gizeasy requested changes

2021-11-29 11:33 UTC, gizeasy commented on src/components/Slider/Slider.css
> +  width: 100%;
> 

при изменении в инпуте полосочка не изменяется

2021-11-29 11:33 UTC, gizeasy commented on src/components/Slider/Slider.css
> +  width: 100%;
при указании не верного значения в инпут, либо не входит в допустимый диапазон либо не кратный шагу, не происходит авто фикса значения

2021-11-29 11:33 UTC, gizeasy commented on src/components/Slider/Slider.css
> +    display: inline-flex;
https://disk.yandex.ru/i/82dBpyB3uhjWVw

очень странно ведет себя полосочка
1) если тяну кружечек мышкой, начинает меняться и другая сторона полосочки, также меняется ширина серой области
2) если перестаю тянуть и просто вожу мышкой то все равно значение меняется
3) если сначала тяну один кружочек потом переключаюсь на другой то первый тоже меняется.

2021-12-01 14:32 UTC, gizeasy requested changes

2021-12-01 14:32 UTC, gizeasy commented on src/components/Slider/Slider.css
> +  &_size {
нет возможности стереть поле ввода, от этого нельзя указать отрицательное значение

также в последнем коммите пропал функционал выделение точки по клику и потом управлять стрелочками

2021-12-02 07:32 UTC, N1MBER commented on src/components/Slider/Slider.css
> +  &_size {
Исправил в последне кормите

2021-12-08 17:19 UTC, gizeasy approved these changes

2021-12-08 17:19 UTC, merged