feat(ContextMenu): add onClick properties
gazprom-neft/consta-uikit pull request #1787
Opened 2021-11-21 16:56 UTC by N1MBER

Add onClick properties and also add getOnItemClick instead of getOnClick

closes #1729

## Описание изменений

* Добавлено новое свойство onClick
* Добавлено свойство getOnItemClick с загадкой на то что оно заменит getOnClick

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-11-29 11:16 UTC, gizeasy requested changes

2021-11-29 11:16 UTC, gizeasy commented on src/components/ContextMenu/helpers.tsx
> +    getOnItemClick?: ContextMenuPropGetOnItemClick<ITEM>;
переименуй 
`getOnItemClick` -> `getItemOnClick`
`onClick` -> `onItemClick`

2021-11-29 11:16 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
> +                    if (typeof getOnItemClick === 'function') {
тут логика ограничивает использовать события вместе, сделай так чтобы все события срабатывали

2021-11-30 09:32 UTC, N1MBER commented on src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
> +                    if (typeof getOnItemClick === 'function') {
Исправил в ласт кормите

2021-12-01 13:24 UTC, gizeasy approved these changes

2021-12-01 13:24 UTC, merged