feat(components): added getConditionalClassName prop to Table
gazprom-neft/consta-uikit pull request #1789
Opened 2021-11-23 08:56 UTC by ndrzhn

added getConditionalClassName prop to Table to change styles depending on the data in column or row

closes #1788

## Описание изменений
Компоненту Table добавлено свойство `getConditionalClassName`, это функция, на вход которой приходят два аргумента `column` и `row`, функция должна возвращать название css-класса, который нужно применить к ячейке в зависимости от данных, содержащихся в `column` и/или `row`.
На основе issue #1788 

## Чек-лист

- [x] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [x] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [x] Верстка: используются [переменные](../src/components/Theme)
- [x] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-11-29 11:46 UTC, gizeasy commented on src/components/Table/__stories__/Table.docs.mdx
> +Функция должна возвращать название css-класса типа `string`. При этом класс должен быть потомком класса `TableCell` и иметь свойство `&:not(&_isActive)`.
Хотя с другой стороны если мы стилизуем ячейку и она станет активной то желаемый класс просто не применится, может тогда в колбек возвращать еще и признак активности?

2021-11-29 11:47 UTC, gizeasy commented on src/components/Table/__stories__/Table.docs.mdx
> +Функция должна возвращать название css-класса типа `string`. При этом класс должен быть потомком класса `TableCell` и иметь свойство `&:not(&_isActive)`.
Но однозначно так это оставлять не стоит

2021-11-29 14:11 UTC, SergeyKatugin commented on src/components/Table/__stories__/Table.docs.mdx
> +Функция должна возвращать название css-класса типа `string`. При этом класс должен быть потомком класса `TableCell` и иметь свойство `&:not(&_isActive)`.
`!important` в своих проектах, как вариант еще.

2021-11-29 14:12 UTC, SergeyKatugin commented on src/components/Table/__stories__/Table.docs.mdx
> +Функция должна возвращать название css-класса типа `string`. При этом класс должен быть потомком класса `TableCell` и иметь свойство `&:not(&_isActive)`.
> 

Можно тогда передавать по типу `force:bool`, которая будет отвечать, за применение класса в зависимости от `isActive`

2021-11-29 21:59 UTC, ndrzhn commented on src/components/Table/__stories__/Table.docs.mdx
> +Если вам нужно добавить какой-либо стиль в зависимости от данных, которые содержатся в строке или колонке, вы можете добавить его как css-класс. Для этого надо задать таблице свойство `getConditional
Поправила

2021-11-29 22:01 UTC, ndrzhn commented on src/components/Table/__stories__/Table.docs.mdx
> +Функция должна возвращать название css-класса типа `string`. При этом класс должен быть потомком класса `TableCell` и иметь свойство `&:not(&_isActive)`.
Добавила в коллбэк аргумент isActive, с помощью которого можно будет определять активность ячейки (строки). При этом в стилях пришлось применить !important, без этого стиль не применяется.

2021-11-29 22:02 UTC, ndrzhn commented on src/components/Table/Table.tsx
> +                      className={getConditionalClassName?.(column, row)}
добавила isActive в коллбэк

2021-12-07 12:32 UTC, gizeasy requested changes

2021-12-07 12:49 UTC, gizeasy requested changes

2021-12-07 12:49 UTC, gizeasy commented on src/components/Table/Table.css
> +.darkBackground {
Тут это лишнее, в компонент не нужно добавлять стили которые исползуются только в примерах
Посмотри как организованы примеры в `Attachment` там на каждый пример есть отдельная папка с компонетом и стилями.
```

2021-12-07 12:49 UTC, gizeasy commented on src/components/Table/__mock__/data.mock.tsx
> +    !isActive && row.type === 'Нефтяное' && !column.mergeCells ? 'darkBackground' : '',
Давай те в стили описывать по БЭМ
возмите функцию `cn` из `utils/bem`

Ну и к примеру напишите такое:
```tsx
const cnCastomCell = cn('CastomCell')
../../..
getConditionalClassName: ({column, row, isActive}) => cnCastomCell({darked: !isActive && row.type === 'Нефтяное' && !column.mergeCells})
```
в стилях описать что-то вроде такого

```css
.CastomCell {
    &_darked {
        background-color: var(--color-bg-ghost);
    }
}
```

всесто того чтобы использовать `!important;` подумай как можно усилить класс

к примеру `.TableCell.CastomCell`

2021-12-07 20:03 UTC, ndrzhn commented on src/components/Table/Table.tsx
> +  getConditionalClassName?: (column: TableColumn<T>, row: T, isActive: boolean) => string;
исправила

2021-12-07 20:03 UTC, ndrzhn commented on src/components/Table/Table.css
> +.darkBackground {
добавила отдельный компонент и его стили `WithAdditionalClassName`

2021-12-07 20:04 UTC, ndrzhn commented on src/components/Table/__mock__/data.mock.tsx
> +    !isActive && row.type === 'Нефтяное' && !column.mergeCells ? 'darkBackground' : '',
поправила

2021-12-08 08:51 UTC, merged