feat(ProgressStepBar): change example on playground and also change label prop to optional
gazprom-neft/consta-uikit pull request #1816
Opened 2021-11-30 10:20 UTC by N1MBER

closes #1697

## Описание изменений

* Свойство `label` сделано опциональным
* Изменен пример в песочнице

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-12-01 14:43 UTC, gizeasy requested changes

2021-12-01 14:43 UTC, gizeasy commented on src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
> +          {label && (
контент ведь тоже не обязательный, давай туда условие тоже добавим

2021-12-01 14:43 UTC, gizeasy commented on src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
>            <div {...pointProps} {...pointDivButton} />
Еще заметил что точка всегда cursor pinter, давай только тогда когда есть событие клика на точке

2021-12-01 14:43 UTC, gizeasy commented on src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
> +  if (!point) return null;
что-то я подзабыл в каких моментах у нас может не прейти точка? и почему она не обязательная?

2021-12-02 05:27 UTC, N1MBER commented on src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
> +          {label && (
Так если его нет (undefined || null) он и так не будет рендерится, там же никакой элемент его не оборачивает. Или ты имеешь ввиду что не нужно рендерит контейнер в случае отсутствия label & content?

2021-12-02 12:37 UTC, N1MBER commented on src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
>            <div {...pointProps} {...pointDivButton} />
Исправил в последнем коммите

2021-12-08 08:52 UTC, merged