Feat/combobox 2
gazprom-neft/consta-uikit pull request #349
Opened 2020-08-19 13:53 UTC by c1n1k

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://ui-kit.gpn.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-08-31 15:26 UTC, hitmanet approved these changes

2020-08-31 15:26 UTC, hitmanet commented on src/components/BasicSelect/__tests__/BasicSelect.test.tsx
> +    fireEvent.mouseDown(block);
а почему не клик?

2020-08-31 15:26 UTC, hitmanet commented on src/components/BasicSelect/__tests__/BasicSelect.test.tsx
> +    fireEvent.mouseDown(block);
потому что див?

2020-08-31 15:26 UTC, hitmanet commented on src/components/Combobox/Combobox.tsx
> +  options: T[];
А нельзя как-то переиспользовать типы BasicSelect и наследоваться от них?

2020-08-31 15:26 UTC, hitmanet commented on src/components/Combobox/Combobox.tsx
> +  const handleInputFocus = (e: React.FocusEvent<HTMLElement>): void => {
А все эти обработчики нельзя опять же как-нибудь из BasicSelect перенести?

2020-08-31 15:26 UTC, hitmanet commented on src/components/Combobox/Combobox.tsx
> +  const handleInputFocus = (e: React.FocusEvent<HTMLElement>): void => {
А то вроде одинаковые

2020-08-31 15:26 UTC, hitmanet commented on src/components/Combobox/Combobox.tsx
> +                const isOptionForCreate = 'optionForCreate' in option;
Может вынести в отдельный компонент?

2020-08-31 16:37 UTC, ilchukovaolga approved these changes

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/BasicSelect/__stories__/BasicSelect.mdx
> +BasicSelect — компонент реализующий элемент управления меню опций (нативного `<select>`).
```suggestion
BasicSelect — компонент, реализующий элемент управления меню опций (нативного `<select>`).
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/BasicSelect/__stories__/BasicSelect.mdx
> +| width?         | `full | default`                                  | `default`    | Cвойство определяет какую ширину будет занимать компонент. `default` ширина согласно содержимому         |
```suggestion
| width?         | `full | default`                                  | `default`    | Cвойство определяет, какую ширину будет занимать компонент. `default` — ширина по размеру содержимого         |
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/BasicSelect/__stories__/BasicSelect.mdx
> +| placeholder?   | `string`                                          | -            | Placeholder — текст, который будет отображаться в качестве подсказки в поле значения, при его отсутствии |
```suggestion
| placeholder?   | `string`                                          | -            | Placeholder — текст, который отобразится в качестве подсказки в пустом поле |
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/BasicSelect/__stories__/BasicSelect.mdx
> +| getOptionLabel | `(arg: T) => string`                              | -            | Функция для получения текста опции, он будет отображаться в поле для выбранного значения                 |
```suggestion
| getOptionLabel | `(arg: T) => string`                              | -            | Функция для получения текста опции, который будет отображаться в поле для выбранного значения                 |
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/Combobox/__stories__/Combobox.mdx
> +Combobox — компонент реализующий элемент управления меню опций с полем для фильтрации.
```suggestion
Combobox — компонент, реализующий элемент управления меню опций с полем для фильтрации.
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/Combobox/__stories__/Combobox.mdx
> +| width?           | `full | default`                                  | `default`    | Cвойство определяет какую ширину будет занимать компонент. `default` ширина согласно содержимому         |
```suggestion
| width?           | `full | default`                                  | `default`    | Cвойство определяет, какую ширину будет занимать компонент. `default` — ширина по размеру содержимого         |
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/Combobox/__stories__/Combobox.mdx
> +| placeholder?     | `string`                                          | -            | Placeholder — текст, который будет отображаться в качестве подсказки в поле значения, при его отсутствии |
```suggestion
| placeholder?     | `string`                                          | -            | Placeholder — текст, который отобразится в качестве подсказки в пустом поле |
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/Combobox/__stories__/Combobox.mdx
> +| getOptionLabel   | `(arg: T) => string`                              | -            | Функция для получения текста опции, он будет отображаться в поле для выбранного значения                 |
```suggestion
| getOptionLabel   | `(arg: T) => string`                              | -            | Функция для получения текста опции, который будет отображаться в поле для выбранного значения                 |
```

2020-08-31 16:37 UTC, ilchukovaolga commented on src/components/SelectComponents/__tests__/SelectContainer.test.tsx
> +  it('должен рендерится без ошибок', () => {
```suggestion
  it('должен рендериться без ошибок', () => {
```

2020-08-31 22:09 UTC, fooontic approved these changes

2020-09-01 07:40 UTC, Yankovsky approved these changes

2020-09-01 07:40 UTC, Yankovsky commented on src/hooks/useDebounce/useDebounce.tsx
> +  const ref = React.useRef<ReturnType<typeof setTimeout> | null>(null);
Зачем timeout и function в ref оборачивать?

2020-09-01 08:27 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +  options: T[];
исправил

2020-09-01 08:28 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +  const handleInputFocus = (e: React.FocusEvent<HTMLElement>): void => {
я не вижу особого смысла

2020-09-01 08:30 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +                const isOptionForCreate = 'optionForCreate' in option;
пока нет

2020-09-01 08:58 UTC, c1n1k commented on src/hooks/useDebounce/useDebounce.tsx
> +  const ref = React.useRef<ReturnType<typeof setTimeout> | null>(null);
чтобы перерисовка никак не влияла

2020-09-03 06:02 UTC, gizeasy requested changes

2020-09-03 10:33 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +export const Combobox: ComboboxType = (props) => {
пока не могу, не знаю как пробросить дженерик, пробовал как в ChoiceGroup, но так теряется тип

2020-09-03 10:33 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +export interface ComboboxSelectProps<T> extends SimpleSelectProps<T> {
переделал

2020-09-03 10:33 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +        <Popover
вынес

2020-09-03 10:33 UTC, c1n1k commented on src/components/Combobox/__stories__/Combobox.mdx
> +| size?            | `s | m | l`                                       | `m`          | Размер компонента                                                                                     |
исправил

2020-09-03 10:33 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +type ComboboxType = <T>(props: ComboboxSelectProps<T>) => React.ReactElement | null;
заменил

2020-09-03 10:33 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +                          + Добавить «<b>{inputData.value}</b>»
добавил

2020-09-04 15:51 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +import '../SelectComponents/Select.css';
перенёс

2020-09-07 11:56 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +export const Combobox: ComboboxType = (props) => {
создал ишшью, потом потом подумаем как сделать

2020-09-07 12:01 UTC, gizeasy approved these changes

2020-09-08 07:09 UTC, merged