docs(Table): edit text and structure
gazprom-neft/consta-uikit pull request #357
Opened 2020-08-24 21:39 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://ui-kit.gpn.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-08-28 10:58 UTC, arhayka commented
@fooontic не разобралась, как добавить примеры в доку. посмотри, плиз, так сойдет или без примеров непонятно?

2020-09-01 08:39 UTC, fooontic requested changes

2020-09-01 08:39 UTC, fooontic commented on src/components/Table/__stories__/Table.mdx
> +`withoutPadding` — убирает отступы.
Зачем это нужно? хотелось бы пояснить в каких случаях не нужны отступы и о каких отступах идёт. Я вот так сходу не очень понял.

2020-09-01 08:39 UTC, fooontic commented on src/components/Table/__stories__/Table.mdx
> +`filterer`
Что это за перечисления без пояснений? нужна помощь по ним?

2020-09-20 15:51 UTC, arhayka commented on src/components/Table/__stories__/Table.mdx
> +`filterer`
Ага, вообще не поняла, как работают фильтры и где их задавать.

2020-09-20 15:52 UTC, arhayka commented on src/components/Table/__stories__/Table.mdx
> +`withoutPadding` — убирает отступы.
А я тоже не поняла. А сформировать пример у меня не получается. Поясните, плиз

2020-10-23 11:21 UTC, gizeasy commented on src/components/Table/__stories__/Table.mdx
> +`withoutPadding` — убирает отступы.
`withoutPadding` задает `padding:0` всему столбцу
это нужно когда я чеку таблицы помещаем компонент у которого есть свои отступы или нужно чтоб компонент стал по всей ширине ячеки. Также и в шапке в заголовке этой колонки `padding:0`

2020-10-23 11:21 UTC, gizeasy commented on src/components/Table/__stories__/Table.mdx
> +`filterer`
описал

2020-10-23 11:22 UTC, gizeasy commented on src/components/Table/__stories__/Table.mdx
> +`withoutPadding` — убирает отступы.
думаю можно обойтись без примеров в песочницы все потыкать можно

2020-11-26 09:03 UTC, fooontic approved these changes

2020-11-26 09:36 UTC, merged