docs(SnackBar): add description and examples
gazprom-neft/consta-uikit pull request #358
Opened 2020-08-25 07:53 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://ui-kit.gpn.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-08-28 10:56 UTC, arhayka commented
@fooontic здесь не разобралась, как корректно добавить примеры. если сделаешь один, я добавлю такие же)

2020-09-01 08:50 UTC, fooontic requested changes

2020-09-01 08:50 UTC, fooontic commented on src/components/SnackBar/__stories__/SnackBar.mdx
> +всё еще идет, используйте Informer.
Надо добавить ссылку на Информер

2020-09-01 08:50 UTC, fooontic commented on src/components/SnackBar/__stories__/SnackBar.mdx
> +всё еще идет, используйте Informer.
Также хочется немножко расширить описание. Снэкбар нужен как инструмент мгновенных уведомлений. В отличии от Информера, он выносится как бы на отдельный «слой» интерфейса за счёт того, что всегда перекрывает основное содержимое. Он сопровождается анимацией, что также привлекает бóльшее внимание к нему. Если кратко — информер в контексте, снэкбар — вне контекста.

2020-09-01 08:50 UTC, fooontic commented on src/components/SnackBar/__stories__/SnackBar.mdx
> +
Во-первых, хочется пример. Во-вторых надо добавить, что таймер нужен для «времени на передумать». Например в сценарии, когда пользователь что-то удалил, и вместо подтверждающего попапа, можно снизу тихонько вывести Снэкбар, в котором есть обратный таймер и кнопка возврата удалённого элемента.

2020-09-01 08:50 UTC, fooontic commented on src/components/SnackBar/__stories__/SnackBar.mdx
> +Например, отменить его или куда-то перейти.
Примерчик бы

2020-09-20 15:35 UTC, arhayka commented on src/components/SnackBar/__stories__/SnackBar.mdx
> +
добавила, дописала

2020-09-20 15:35 UTC, arhayka commented on src/components/SnackBar/__stories__/SnackBar.mdx
> +Например, отменить его или куда-то перейти.
добавила

2020-10-23 09:13 UTC, fooontic approved these changes

2020-11-26 09:36 UTC, merged