docs(Header): add docs for Header
gazprom-neft/consta-uikit pull request #369
Opened 2020-08-28 11:36 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://ui-kit.gpn.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-08-30 20:52 UTC, fooontic commented
@gizeasy надо посмотреть примеры и понять, почему там некоторые модули глючат. Сама дока — огонь вообще @arhayka!

2020-08-30 20:53 UTC, fooontic requested changes
@gizeasy надо посмотреть примеры и понять, почему там некоторые модули глючат. Сама дока — огонь вообще @arhayka!

2020-10-23 09:14 UTC, fooontic commented
@gizeasy ап!

2020-10-23 09:15 UTC, fooontic requested changes
@gizeasy Нужно посмотреть примеры

2020-10-23 12:00 UTC, gizeasy commented
> @gizeasy Нужно посмотреть примеры

посмотрел все разехалось из-за `.UiKit--DocsDecorator` видимо все-таки надо оставить отступы на месте, или конкретнее указать селекторы

2020-11-11 20:01 UTC, merged