Feat/MultiCombobox
gazprom-neft/consta-uikit pull request #380
Opened 2020-09-03 13:35 UTC by c1n1k

# Мержить после #349 

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-04 12:32 UTC, hitmanet commented on src/components/SelectComponents/Select.css
> +    z-index: 1;
а для чего?

2020-09-04 12:32 UTC, hitmanet commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  onCreate?(): void;
может стоит в onCreate передавать новое значение? Или оно уже передается?

2020-09-04 12:32 UTC, hitmanet commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +                          return JSON.stringify(val) === JSON.stringify(menuOption);
может лучше по id сделать?

2020-09-08 07:11 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +type ComboboxType = <ITEM>(props: ComboboxSelectProps<ITEM>) => React.ReactElement | null;
1. для единообразия
2. через FC какая-то ошибка с типизацией была

2020-09-08 07:12 UTC, c1n1k commented on src/components/MultiCombobox/MultiCombobox.tsx
> +  const inputWidth = getInputWidth();
да, содержимое же поля меняется, ширину надо обновить

2020-09-08 07:13 UTC, c1n1k commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +                          return JSON.stringify(val) === JSON.stringify(menuOption);
?

2020-09-08 10:19 UTC, c1n1k commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +  onCreate?(): void;
исправил

2020-09-08 10:22 UTC, c1n1k commented on src/components/SelectComponents/Select.css
> +    z-index: 1;
уже не надо, удалил

2020-09-08 10:44 UTC, c1n1k commented on src/components/Combobox/Combobox.tsx
> +    scrollIntoView(elements[index], optionsRef.current);
исправил

2020-09-08 10:44 UTC, c1n1k commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +    // options = [...options, (getGroupOptions ? {label: 'Пользовательская', items:[...options[options.length - 1].items, { label: v, value: v }])];
удалил

2020-09-08 10:46 UTC, c1n1k commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    scrollIntoView(elements[index], optionsRef.current);
я пока не знаю куда выность, потому что это относится к элементу, у каждого ведь списка может измениться механизм прокрутки, например в надо будет что-то пропускать в списке

2020-09-09 21:03 UTC, fooontic requested changes
Ситуация:
1. Выбрать несколько опций. 
2. Скинуть фокус (нажав вне селекта, например)
3. Удалять опции нажимая на крестик в тэгах. В таком случае откроется выпадашка. 
4. Если продолжить и удалить следующий тэг, выпадашка закроется. 
5. Если удалить ещё один тэг — выпдашка снова раскроется. И так по кругу. 

Надо по нажатию на тэги не аффектить выпадашку.

2020-09-11 11:21 UTC, gizeasy requested changes
Мне не нравится что высота рутового контейнера разная при пустом и заполненном поле, в макетах не так.

2020-09-11 11:25 UTC, c1n1k commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    ...restProps
> Мне не нравится что высота рутового контейнера разная при пустом и заполненном поле, в макетах не так.

это проблема в переменных, Вадиму об этом писал

2020-09-11 13:11 UTC, c1n1k commented on src/components/MultiCombobox/MultiCombobox.tsx
> +            <button
добавил

2020-09-11 13:19 UTC, c1n1k commented on src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
> +      <MultiCombobox
обернул, нашёл баг, исправил :)

2020-09-11 13:19 UTC, c1n1k commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    size = 'm',
заменил

2020-09-14 09:34 UTC, gizeasy commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    ...restProps
Обойти проблему можно так убрать у `Select-ControlValue` 
```
padding-top: calc(var(--tag-space) - (var(--tag-space) / 4));
padding-bottom: 0
```
и у тэга `margin-bottom: calc(var(--tag-space) - (var(--tag-space) / 4));`

2020-09-15 22:45 UTC, fooontic requested changes

2020-09-15 22:45 UTC, fooontic commented on src/components/SelectComponents/Select.css
> +      --tag-space: calc(var(--space-m) / 2);
Здесь и во всех остальных размерах надо заменить на `calc(var(--space-m) / 2 - var(--control-border-width));` чтобы избежать скачка высоты между пустым и заполненным видом.

2020-09-15 22:46 UTC, fooontic commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    ...restProps
Вот тут https://github.com/gazprom-neft/consta-uikit/pull/380#discussion_r489041801 написал, как это можно решить.

2020-09-22 09:15 UTC, gizeasy commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    ...restProps
![image](https://user-images.githubusercontent.com/13190808/93862210-5ce00500-fcca-11ea-9c55-b123484ca26d.png)
на размере xs не решилась проблема, 
если верхний отступ поставить  1px норм все

2020-09-22 09:26 UTC, fooontic commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    size = 'm',
xs не нужен

2020-09-22 09:31 UTC, fooontic commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    size = 'm',
@c1n1k Сорри, только сейчас заметил. Нам не нужен размер xs в multiCombobox. У нас для этого ни тэгов нет, ни задач. Этот компонент не нужен в таком мелком размере. Он уже не читаемый будет.

2020-09-22 12:44 UTC, gizeasy commented on src/components/Combobox/Combobox.tsx
> +type ComboboxType = <ITEM>(props: ComboboxSelectProps<ITEM>) => React.ReactElement | null;
есть задача на добавления рефов, этот момент перепишется

2020-09-23 12:14 UTC, merged