feat(Table): add modifier zebraStriped
gazprom-neft/consta-uikit pull request #386
Opened 2020-09-07 11:39 UTC by gizeasy

added modifier zebraStriped, remove isZebraStriped

BREAKING CHANGE:
remove prop isZebraStriped

issue -  #360

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-08 06:55 UTC, c1n1k commented on src/components/Table/Table.css
> +    .Table_zebraStriped_obb .Table-CellsRow:nth-child(2n + 1):not(:hover) &:not(&_isActive) {
`_obb` если это модификатор для чётных номеров, то этодолжно быть odd

2020-09-08 06:59 UTC, c1n1k approved these changes

2020-09-09 20:40 UTC, fooontic requested changes

2020-09-09 20:40 UTC, fooontic commented on src/components/Table/Table.css
> +    .Table_zebraStriped_obb .Table-CellsRow:nth-child(2n + 1):not(:hover) &:not(&_isActive) {
`_odd` — опечатка

2020-09-09 20:41 UTC, fooontic commented on src/components/Table/Table.tsx
> -  isZebraStriped?: boolean;
а тут никак нельзя обойтись без удаления старого пропса? ну типа, чтобы ничего не сломалось у тех, кто уже использует.

2020-09-10 09:08 UTC, gizeasy commented on src/components/Table/Table.tsx
> -  isZebraStriped?: boolean;
думаю ни чего страшного, при обновлении поправят один пропс.
Мне не нравится идея оставить 2 пропса, так как новые пользователи будут не понимать почему их тут 2 и зачем вообще `isZebraStriped` если есть `zebraStriped`

2020-09-10 09:39 UTC, gizeasy commented on src/components/Table/Table.css
> +    .Table_zebraStriped_obb .Table-CellsRow:nth-child(2n + 1):not(:hover) &:not(&_isActive) {
fix

2020-09-10 09:41 UTC, gizeasy commented on src/components/Table/Table.css
> +    .Table_zebraStriped_obb .Table-CellsRow:nth-child(2n + 1):not(:hover) &:not(&_isActive) {
fix и теперь сделал на классах, была обнаружена ошибка когда применяешь фильтр не верно зебра отрисовывалась

2020-09-10 14:03 UTC, fooontic approved these changes

2020-09-11 07:34 UTC, merged