Added Modal component
gazprom-neft/consta-uikit pull request #390
Opened 2020-09-08 07:24 UTC by karpovfv-nedra

## Описание изменений

Создан компонент Modal. Написаны тесты, обновлён сторибук, добавлено описание.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-09 14:32 UTC, c1n1k reviewed
почему не использовал Popover?

2020-09-09 20:01 UTC, fooontic commented
Спасибо большое за ПР! 👍

2020-09-09 20:16 UTC, fooontic requested changes

2020-09-09 20:16 UTC, fooontic commented on src/components/Modal/Modal.tsx
> +  hasCloseButton?: boolean;
Лучше не делать кнопку закрытия. Хочется, чтобы модалка была максимально независимой от контент вообще. В разных проектах кнопка закрытия может быть разная. Она омжет быть как внутри, так и вне модалки, она может быть частью какой-то единой шапки в модалке. Поэтому оставим это на усмотрения пользователей Консты.

2020-09-09 20:16 UTC, fooontic commented on src/components/Modal/Modal.css
> +  &-Root {
Я бы переименовал элемент в Window

2020-09-09 20:16 UTC, fooontic commented on src/components/Modal/Modal.tsx
> +  children?: React.ReactNode;
Нужно ещё добавить пропс ширины. По умолчанию он должен быть 'auto' и тогда его можно не указывать, при этом он будет равен тому, как сделано у вас. Но в будущем нам важно заложить возможность выбора ширины из какого-то предустановленного списка. Списка пока нет, но фундамент под него лучше заложить уже сейчас.

2020-09-09 20:16 UTC, fooontic commented on src/components/Modal/Modal.tsx
> +  children?: React.ReactNode;
Также нужно заложить пропс с указанием позиции самой модалки. Пока кажется, что может быть два варианта: `center` (как у вас сейчас сделано) и `top` (60px сверху).

2020-09-09 21:05 UTC, hitmanet commented
А почему не подходит модалка та, что есть в vega-ui? Чисто теоретически мы ее можем перетащить сюда

2020-09-10 08:21 UTC, gizeasy requested changes
Мне кажется нужно

2020-09-10 08:21 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +    <PortalWithTheme preset={theme} container={window.document.body}>
давайте дадим пользователям самим указывать `container`, по умолчанию `window.document.body`

2020-09-10 08:21 UTC, gizeasy commented on src/components/Modal/Modal.css
> +  @keyframes animatebg {
название анимации лучше писать с префиксом `Animate--` и дальше по БЭМ название блока или элемента и если надо то с модификаторами
В данном случае так:
`Animate--Modal-Overlay`

если разные анимации на закрытие и открытие то будет так 
`Animate--Modal-Overlay_open` и `Animate--Modal-Overlay_close`

2020-09-11 10:56 UTC, karpovfv-nedra commented
> почему не использовал Popover?

Немного не понял вопроса. В том смысле, что использовать поповер в качестве основы для модалки? Или конкретно на проекте подпилить его до модалки?

2020-09-11 10:56 UTC, karpovfv-nedra commented on src/components/Modal/Modal.css
> +    background: rgba(0, 0, 0, 0.5);
Спасибо, использовал её

2020-09-11 10:56 UTC, karpovfv-nedra commented on src/components/Modal/Modal.css
> +    box-shadow: 0 9px 24px rgba(0, 0, 0, 0.05), 0 9px 24px rgba(0, 0, 0, 0.1);
Спасибо, взял их

2020-09-11 10:56 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +  hasCloseButton?: boolean;
Убрал совсем кнопку закрытия

2020-09-11 10:57 UTC, karpovfv-nedra commented on src/components/Modal/Modal.css
> +  &-Root {
Сделал 👍

2020-09-11 10:58 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +  children?: React.ReactNode;
добавил пропс `width` с дефолтным значением `'auto'`

2020-09-11 10:58 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +  children?: React.ReactNode;
Сделал. Добавлен пропс `position` с дефолтным значением `center`

2020-09-11 11:00 UTC, karpovfv-nedra commented
> А почему не подходит модалка та, что есть в vega-ui? Чисто теоретически мы ее можем перетащить сюда

Мы приняли решение, что будем делать модалку, которую потом через PR отправим в общую дизайн систему.

2020-09-11 11:01 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +  children?: React.ReactNode;
так же добавлен пропс `hasOverlay` со значением по дефолту в `true`

2020-09-11 11:01 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +        <div className={cnModal('Root', [className])} ref={ref} {...rest}>
использовал react-transition-group в итоге

2020-09-11 11:02 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +    <PortalWithTheme preset={theme} container={window.document.body}>
Сделано 👍

2020-09-11 11:02 UTC, karpovfv-nedra commented on src/components/Modal/Modal.css
> +  @keyframes animatebg {
Спасибо за инфу!
в итоге использовал `react-transition-group` для анимации

2020-09-16 07:17 UTC, gizeasy commented
@karpovfv-nedra тесты не прошли

2020-09-16 07:18 UTC, gizeasy commented
ветку нужно направить в dev

2020-09-16 07:18 UTC, gizeasy commented
проходите чеклист Пра, чтоб ничего не забыть

2020-09-16 07:56 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +        <div className={cnModal('Root', [className])} ref={ref} {...rest}>
@fooontic  анимацию появления довольно сложно сделать без `react-transition-group`.
Шаги у анимации такие:

Появление в дом:
1) Отсутствует в дом
2) Появляется в дом с классом 'init' (к примеру)
3) Тут - же меняется `init` на `opening`
4) Через заданное время менятся с `opening` на `opened`(этот пункт не всегда используется)

Удаление из дом:
1) добавить класс `closing`
2) через время меняем класс на `closed`
3) убираем елемент из дом

чтоб не городить свои костыли с таймаутами проще сделать на `react-transition-group.

2020-09-16 08:49 UTC, gizeasy requested changes

2020-09-16 08:49 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +  useClickOutside({
Сейчас стал странно выглядеть интерфейс.
есть onClose который сработает только случае когда `closeByClickOnOverlay = true` при клике по оверлею
думаю логичнее сделать так:

`onOverlayClick` - сработает по клику по оверлею
`onClose` - сработает при смене isOpen на false
`onOpen` - сработает при смене isOpen на true

2020-09-17 10:46 UTC, nedradigital commented on src/components/Modal/Modal.tsx
> +  useClickOutside({
Поправил

2020-09-17 11:52 UTC, c1n1k commented on src/components/Modal/Modal.css
> +        transform: translate(-50%, -50%);
раньше при такой способе центрирования, в некоторых браузерах, если не ошибаюсь в ff, могли «мылится» тексты

2020-09-17 11:59 UTC, c1n1k commented on src/components/Modal/Modal.tsx
> +      onOpen?.();
`?.` не нужно же, ты уже проверяешь наличие функции в условии `if`

2020-09-17 12:03 UTC, c1n1k commented on src/components/Modal/Modal.tsx
> +type TModalPropPosition = 'center' | 'top';
переделай согласно https://github.com/gazprom-neft/consta-uikit/pull/398, чтобы потом не переделывать

2020-09-17 14:53 UTC, nedradigital commented on src/components/Modal/Modal.tsx
> +type TModalPropPosition = 'center' | 'top';
done

2020-09-17 14:54 UTC, nedradigital commented on src/components/Modal/Modal.css
> +        transform: translate(-50%, -50%);
переделал на флексы

2020-09-17 14:54 UTC, nedradigital commented on src/components/Modal/Modal.tsx
> +      onOpen?.();
не, в условии флажок, а внутри необязательный колбэк

2020-09-21 09:14 UTC, gizeasy requested changes

2020-09-21 09:14 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +type TModalPropPosition = typeof modalPropPosition[number];
без префикса `T`

2020-09-21 09:14 UTC, gizeasy commented on src/components/Modal/Modal.tsx
> +type TModalPropWidth = typeof modalPropWidth[number];
без префикса `T`
и дальше где будет он, тоже поправь

2020-09-21 09:14 UTC, gizeasy commented on src/components/Modal/__stories__/Modal.stories.tsx
> +        className="myClassName"
замени на cnModalStories('Modal') - как элемент блока стори, ну и в CSS тоже поправь. Обязательно 1 блок - 1 css файл

2020-09-21 09:46 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +type TModalPropPosition = typeof modalPropPosition[number];
поправил

2020-09-21 09:47 UTC, karpovfv-nedra commented on src/components/Modal/Modal.tsx
> +type TModalPropWidth = typeof modalPropWidth[number];
убрал везде этот префикс, где был поставлен

2020-09-21 09:47 UTC, karpovfv-nedra commented on src/components/Modal/__stories__/Modal.stories.tsx
> +        className="myClassName"
сделал

2020-09-21 09:49 UTC, gizeasy approved these changes

2020-09-21 09:53 UTC, c1n1k approved these changes

2020-09-21 10:08 UTC, merged