docs(start): add docs start
gazprom-neft/consta-uikit pull request #393
Opened 2020-09-09 11:22 UTC by gizeasy

closes  #383

## Описание изменений
Добавлена документация подключения дизайн системы

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-09 12:25 UTC, gizeasy commented
@arhayka @fooontic стоит ли тут указывать про:
Для поддержки темизации по всему приложению необходимо использовать переменные из ui-kit при описании стилей.

или в другом месте гденибуть указать

2020-09-09 20:22 UTC, fooontic commented
> @arhayka @fooontic стоит ли тут указывать про:
> Для поддержки темизации по всему приложению необходимо использовать переменные из ui-kit при описании стилей.
> 
> или в другом месте гденибуть указать

Мне кажется не стоит. Быстрый старт на то и быстрый старт =)

2020-09-09 20:24 UTC, fooontic requested changes

2020-09-09 20:24 UTC, fooontic commented on docs/common/start.mdx
> +yarn add @consta/uikit
надо добавить ещё npm

2020-09-10 07:20 UTC, arhayka commented
> @arhayka @fooontic стоит ли тут указывать про:
> Для поддержки темизации по всему приложению необходимо использовать переменные из ui-kit при описании стилей.
> 
> или в другом месте гденибуть указать

мне кажется, это важно, и люди будут в этом месте ошибаться. поэтому я бы прямо там написала

но можно сделать так:
- написать таки нормальную доку про темы
- в ней в первых строчках выделить, что темы работают только с переменными из ui-kit
- и дать ссылку на доку про темы из быстрого старта

2020-09-10 09:01 UTC, gizeasy commented on docs/common/start.mdx
> +yarn add @consta/uikit
fix

2020-09-10 14:10 UTC, fooontic approved these changes

2020-09-11 07:33 UTC, merged