feat(Popover): added spareDirection
gazprom-neft/consta-uikit pull request #432
Opened 2020-09-21 09:01 UTC by gizeasy

добавлено запасное направление в которое развернется поповер если не будет места для разворота в доступные направления.

closes #313

## Описание изменений

## Чек-ли
- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-21 14:54 UTC, nekitk requested changes

2020-09-21 14:54 UTC, nekitk commented on src/components/Popover/Popover.tsx
> +    spareDirection = 'downStartLeft',
стоит проверить, что spareDirection есть в списке possibleDirections

иначе может получиться ситуация, что поповер будет разворачиваться в неподдерживаемое положение, для которого нормальных стилей не предусмотрено

2020-09-21 14:54 UTC, nekitk commented on src/components/Popover/__tests__/helpers.test.ts
> +          viewportSize: { width: 500, height: 500 },
почему этот тест так сильно пришлось поменять?

2020-09-22 09:54 UTC, gizeasy commented on src/components/Popover/Popover.tsx
> +    spareDirection = 'downStartLeft',
тоже думал об этом, но показалось лишним,
1) если пользователь не указывает `spareDirection ` то разворот в `downStartLeft`, если ни одна из сторон указанных в possibleDirections не подошла. `downStartLeft` - это лучшая позиция для разворота, так как по вертикали и по горизонтали появится скрол. 
2) Если пользователь указывает, то он уже сам несет ответственность за это и может сам указать порядок этого направления в `possibleDirections`
3) И в целом это довольно редкий кейс, и обход его сейчас нормально рабочий, думаю добавление условий только усложнит интерфейс

2020-09-22 10:24 UTC, gizeasy commented on src/components/Popover/__tests__/helpers.test.ts
> +          viewportSize: { width: 500, height: 500 },
показалось что тест, не рабочий. либо я не понял как он работает
`viewportSize` был шириной 50
а `contentSize` 100
и получалось что он всяко не входит и от этого всегда возвращал `direction: 'upCenter',`
то есть даже то что было banned не могло поместиться в viewport, 
я поменял так чтобы banned направления помещались во viewport, и соответственно была возможность проверить работает ли логика исключения.

2020-09-22 12:19 UTC, nekitk approved these changes

2020-09-23 09:58 UTC, c1n1k approved these changes

2020-09-23 11:11 UTC, merged