feat(DatePicker): add DatePicker
gazprom-neft/consta-uikit pull request #433
Opened 2020-09-21 10:43 UTC by oceandrama

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-22 11:27 UTC, gizeasy requested changes

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +        Укажите дату в промежутке {formatOutOfRangeDate(minDate)} - {formatOutOfRangeDate(maxDate)}
нужно добавить возможность задавать текст сверху компонента

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +const DateOutOfRangeTooptipContent: React.FC<DateLimitProps> = ({ minDate, maxDate }) => {
Думаю стоит вынести DateOutOfRangeTooptipContent в отдельный компонент

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +const defaultRenderSingleControl: RenderControls<Date> = (props) => {
вынести defaultRenderSingleControl в отдельный компонент

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +const defaultRenderRangeControls: RenderControls<DateRange> = (props) => {
вынести defaultRenderRangeControls в отдельный компонент

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +    <div>
`div` можно убрать

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +        className={cnDatePicker('Controls')}
Нет Блока `DatePicker`, может укажем его здесь и сюда же накинем `className` который сверху будет падать - `cnDatePicker(null,[className])`

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +export const DatePicker: React.FC<Props> = (props) => {
нужно добавить возможность получения `ref` через `forwardRef`

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/MonthsSliderWrapper/MonthsSliderWrapper.tsx
> +const MovePeriodButton: React.FC<{
Вынести MovePeriodButton в отдельный компонент

2020-09-22 11:27 UTC, gizeasy commented on src/components/DatePicker/MonthsSliderWrapper/MonthsSliderWrapper.tsx
> +    <div className={cnDatePicker('Slider')}>
название блока не совпадает с название компонента

2020-09-22 11:36 UTC, gizeasy commented
Общее замечание по Пру:
Нужно придерживаться правилу 1 блок - 1 компонент, во избежании пересечения css классов внутри компонента. Название компонента должно совпадать с названием Блока. Есть файлы в которых несколько компонентов, в целом их можно разделить.

https://consta-uikit.vercel.app/?path=/docs/%D1%81ommon-file-structure-components--page

2020-09-22 11:37 UTC, gizeasy commented
До конца не досмотрел, в начале хочется видеть структуру которой стараемся придерживаться.

2020-09-28 12:48 UTC, gizeasy requested changes

2020-09-28 12:48 UTC, gizeasy commented on src/components/DatePicker/helpers.ts
> +export const useCombinedRefs = <T>(...refs: Ref<T>[]) => {
можно использовать этот хук
https://github.com/gazprom-neft/consta-uikit/blob/29bca98ed078164aa221954c9fbce21d11fc250a/src/hooks/useForkRef/useForkRef.tsx#L8

2020-09-28 12:48 UTC, gizeasy commented on src/components/DatePicker/helpers.ts
> +export const useCombinedRefs = <T>(...refs: Ref<T>[]) => {
можно использовать 
https://github.com/gazprom-neft/consta-uikit/blob/29bca98ed078164aa221954c9fbce21d11fc250a/src/hooks/useForkRef/useForkRef.tsx#L8

2020-09-28 12:49 UTC, gizeasy commented
компонент не соответсвует требованиям файловой структуре
https://consta-uikit.vercel.app/?path=/docs/%D1%81ommon-file-structure-components--page

2020-09-30 11:53 UTC, c1n1k reviewed
![]( http://s.csssr.ru/UC5KAQ32R/2020-09-30-12-52-47-rezh4.png)

2020-10-20 12:33 UTC, typeetfunc commented on src/components/DatePicker/helpers.ts
> +export const useCombinedRefs = <T>(...refs: Ref<T>[]) => {
этот хук использует refcallback(кстати почему? коллбэки вроде как устаревший вариант) и не подходит по типам к Popover
2 варианта:
1) обновить этот хук и переписать его на refObj
2) исправить типизацию на Popover.anchorRef на более общий Ref<T>

2020-10-20 12:39 UTC, typeetfunc commented
@gizeasy привел файловую структуру в соотвествие с докой
@c1n1k если ты про лишнюю обводку то предлагаю баги сделать в отдельной задаче - тут и так многовато получается 
вынесу сюда https://jira.csssr.io/browse/GDC-769

2020-10-23 12:49 UTC, gizeasy commented
@typeetfunc объедини все коммиты и подлей новый дев пожалйста, смотреть изменения проще будет

2020-10-23 13:03 UTC, gizeasy commented
Составили доработки:

1. Датапикер и календарь должны быть разными компонентами. Календарь может использоваться отдельно в интерфейсе.

2. Валидация не должна визуально отображаться, только не давать выбирать
![image](https://user-images.githubusercontent.com/13190808/97006106-045d8b00-1548-11eb-9bda-fefc0553d9a2.png)

3. Кнопку “выбрать” убрать

4. Вместо “1кв 2020” должна быть возможность указывать свои периоды также в виде кнопок
![image](https://user-images.githubusercontent.com/13190808/97006789-08d67380-1549-11eb-91f4-dedbddbe029a.png)

5. В Датапикер должна быть возможность проброса кастомного ипута

6. Календарь должен быть в теме родителя, не в инверсной

7. Убрать стилизацию фокуса с выбора месяца
![image](https://user-images.githubusercontent.com/13190808/97006560-b9904300-1548-11eb-8316-42e7a235a331.png)

2020-10-27 19:11 UTC, typeetfunc commented
завел на баги(https://jira.csssr.io/browse/GDC-769) и доработки(https://jira.csssr.io/browse/GDC-978) отдельные задачи 
я тогда сделаю их в отдельных ветках отведенных из этой и PR направлю сюда потому

2020-11-02 17:04 UTC, typeetfunc commented
@gizeasy 
3. кнопку выбрать убрать. А сделать ли так чтобы календарь сам закрывался после выбора даты? сейчас закрывается только по клику в свободном месте
4. Что это значит? всмысле разбивка на периоды должна быть захардкожена не на кварталы а передаватся через пропсы?

2020-11-03 12:50 UTC, typeetfunc commented
@gizeasy 
7. это стандартный аутлайн которые браузеры накладывают для повышения доступности. Его очень очень очень нежелательно убирать. Насколько он мешает?

2020-11-03 15:03 UTC, gizeasy commented
> @gizeasy
> 3. кнопку выбрать убрать. А сделать ли так чтобы календарь сам закрывался после выбора даты? сейчас закрывается только по клику в свободном месте
> 4. Что это значит? всмысле разбивка на периоды должна быть захардкожена не на кварталы а передаватся через пропсы?

3. тогда просто убрать кнопку
4. сейчас есть возможность показать только кварталы, есть желание иметь возможность добавлять кнопки со своими периодами дат

2020-11-05 10:46 UTC, gizeasy commented
> @gizeasy
> 7. это стандартный аутлайн которые браузеры накладывают для повышения доступности. Его очень очень очень нежелательно убирать. Насколько он мешает?

Думаю что в данном случае можно, так как у нас визуальное выдиление и так есть
@fooontic ?

2020-11-09 13:45 UTC, typeetfunc commented
@gizeasy @c1n1k @fooontic исправил все в отдельном пр
https://github.com/gazprom-neft/consta-uikit/pull/593
если есть желание посмотреть все сразу то просто подмержьте сюда - я решил не раздувать ПР

2021-07-09 09:23 UTC, closed without merging