Pr to consta sidebar
gazprom-neft/consta-uikit pull request #449
Opened 2020-09-23 15:32 UTC by karpovfv-nedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-24 07:46 UTC, gizeasy requested changes

2020-09-24 07:46 UTC, gizeasy commented on src/components/Sidebar/Sidebar.css
> +  &_animate {
не работает анимация вхождения при position_top

2020-09-24 08:01 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.css
> +  &_animate {
пофиксил

2020-09-24 09:39 UTC, gizeasy approved these changes

2020-09-25 07:36 UTC, c1n1k commented on src/components/Sidebar/Sidebar.css
> +              transform: translate(0, 0);
`translate3D`? нет осообого профита?

2020-09-25 07:41 UTC, c1n1k reviewed
при открытии сайдбара есть визуальные артефакты в виде появляющихся скроллов (горизонтальный и вертикальный) страницы

2020-09-25 07:50 UTC, gizeasy commented
> при открытии сайдбара есть визуальные артефакты в виде появляющихся скроллов (горизонтальный и вертикальный) страницы

видимо только на винде

2020-09-25 07:55 UTC, karpovfv-nedra commented on src/components/Sidebar/Sidebar.css
> +              transform: translate(0, 0);
изменил `translate` на `translate3d`, судя по devtools performance - есть крохотный прирост в производительности

2020-09-25 07:56 UTC, karpovfv-nedra commented
> при открытии сайдбара есть визуальные артефакты в виде появляющихся скроллов (горизонтальный и вертикальный) страницы

прочекал с записью анимации в devtools, никаких артефактов у себя не обнаружил

2020-09-25 08:06 UTC, c1n1k commented
http://s.csssr.ru/UC5KAQ32R/2020-09-25-11-05-18-7u79t.mp4

2020-09-25 08:07 UTC, c1n1k commented
![](http://s.csssr.ru/UC5KAQ32R/2020-09-25-11-06-54-fxxj4.png)

2020-09-25 08:48 UTC, karpovfv-nedra commented
> http://s.csssr.ru/UC5KAQ32R/2020-09-25-11-05-18-7u79t.mp4

спасибо!
пофиксил, сейчас скроллы не появляются

2020-09-25 09:20 UTC, c1n1k approved these changes

2020-09-25 09:23 UTC, merged