docs(Combobox): add docs
gazprom-neft/consta-uikit pull request #467
Opened 2020-09-29 09:27 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-09-29 09:31 UTC, arhayka commented
@gizeasy помоги, плиз, с примерами для групп и onCreate, что-то у меня не срослось

2020-09-29 13:15 UTC, fooontic requested changes

2020-09-29 13:15 UTC, fooontic commented on src/components/Combobox/__stories__/Combobox.mdx
> +Напечатайте любое слово в этом поле и нажмите **Добавить**.
Вот тут нужен пример. Если нужна помощь @gizeasy поможет

2020-09-30 07:05 UTC, arhayka commented on src/components/Combobox/__stories__/Combobox.mdx
> +Напечатайте любое слово в этом поле и нажмите **Добавить**.
ага, добавили

2020-09-30 07:08 UTC, arhayka commented
> @gizeasy помоги, плиз, с примерами для групп и onCreate, что-то у меня не срослось

а можешь еще проверить примеры в тексте Combobox.mdx? я опиралась на них, и там явно были ошибки

2020-09-30 08:40 UTC, gizeasy approved these changes

2020-09-30 08:59 UTC, fooontic approved these changes

2020-09-30 11:43 UTC, merged