feat(Tabs): added renderItem
gazprom-neft/consta-uikit pull request #477
Opened 2020-10-01 12:00 UTC by gizeasy

## Описание изменений

* added renderItem
* added tests for renderItem
* added example to the documentation

closes #448

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-07 13:20 UTC, c1n1k approved these changes

2020-10-21 10:03 UTC, al-fyodorov requested changes

2020-10-21 10:03 UTC, al-fyodorov commented on src/components/Tabs/Tabs.tsx
> +  type Item = typeof items[number];
Какого либо положительного эффекта мы от этого не получаем так как при приведении типов значение `Item` будет всегда `any`. Либо стоит заморочится и переписать с использованием generic-а или просто убрать эту часть и везде где использовался тип `Item` перейти на `unknown`.

2020-10-22 11:51 UTC, gizeasy commented on src/components/Tabs/Tabs.tsx
> +  type Item = typeof items[number];
fix, заморочился поправил типы,
Только в `renderItemDefault`  пришлось использовать as, но там не критично
В остально все с типами ок стало

2020-10-28 09:01 UTC, al-fyodorov commented on src/components/Tabs/Tabs.tsx
> +  type Item = typeof items[number];
А вот чего не понимаю, почему не сделать через вывод типов до тела функции? Зачем выводить тип в теле функции, очень странным образом маскируя это все типом `Tabs` который как раз ровно это и делает, потом мы в коде получаем тип `type ITEMELEMENT = ITEMELEMENT extends null | undefined ? never : ITEMELEMENT`, который вообще ни о чем не говорит.

Ровно с тем же успехом можно везде вместо типа `ITEMELEMENT` указать `unknown`, и для внешнего пользователя ничего не изменится. В рамках самого компонента есть какая-то странная логика вывода типа которая ничем не помогает в разработке и только путает.

2020-10-28 09:02 UTC, al-fyodorov requested changes

2020-10-28 09:02 UTC, al-fyodorov commented on src/components/Tabs/Tabs.tsx
> +  type ITEMELEMENT = NonNullable<Parameters<typeof renderItem>[0]['ref']['current']>;
А вот чего не понимаю, почему не сделать через вывод типов до тела функции? Зачем выводить тип в теле функции, очень странным образом маскируя это все типом `Tabs` который как раз ровно это и делает, потом мы в коде получаем тип `type ITEMELEMENT = ITEMELEMENT extends null | undefined ? never : ITEMELEMENT`, который вообще ни о чем не говорит.

Ровно с тем же успехом можно везде вместо типа `ITEMELEMENT` указать `unknown`, и для внешнего пользователя ничего не изменится. В рамках самого компонента есть какая-то странная логика вывода типа которая ничем не помогает в разработке и только путает.

2020-10-28 12:03 UTC, gizeasy commented on src/components/Tabs/Tabs.tsx
> +  type ITEMELEMENT = NonNullable<Parameters<typeof renderItem>[0]['ref']['current']>;
fix

2020-11-05 05:58 UTC, al-fyodorov approved these changes

2020-11-05 05:58 UTC, al-fyodorov commented on src/components/Tabs/Tabs.tsx
> +) as Tabs;
[note]
А точно тогда в проекте нужен TypeScript, раз при любом неудобном случае его стараются отключить или заглушить приведением типов? В крайнем случае можно было в сборку проекта положить отдельный `d.ts` файл с описаниями пропсов.

2020-11-05 06:00 UTC, al-fyodorov commented on src/components/Tabs/Tabs.tsx
> +  type ITEMELEMENT = NonNullable<Parameters<typeof renderItem>[0]['ref']['current']>;
Так как у нас все равно осталось приведение типов, так как не смогли справится с типизацией говорит только о том, что на самом деле мы не понимаем какой тип туда может прийти, так что это не особо фикс проблемы. Надо максимально запретить ставить приведение типа в коде, так как сейчас это только скрытие проблем, а не их решение.

2020-11-11 09:52 UTC, merged