feat(Table): added multilevel headers
gazprom-neft/consta-uikit pull request #484
Opened 2020-10-05 10:57 UTC by karpovfv-nedra

## Описание изменений

Добавлена возможность использования многоуровневых заголовков в компоненте Table

https://github.com/gazprom-neft/consta-uikit/issues/396
https://github.com/gazprom-neft/consta-uikit/issues/425

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-05 16:46 UTC, gizeasy requested changes

2020-10-05 16:46 UTC, gizeasy commented on src/components/Table/__stories__/Table.stories.tsx
> +const getKnobs = (replacedProps?: Partial<Props<TableRow>> | any): Props<TableRow> => {
убрать `any`

2020-10-05 16:46 UTC, gizeasy commented on src/components/Table/__tests__/helpers.test.ts
> +    const result = transformColumns(COLUMNS as any, getMaxLevel(COLUMNS as any));
убрать `any`

2020-10-05 16:46 UTC, gizeasy commented on src/components/Table/Cell/TableCell.css
> +    .Table-HeaderCell_groupTitle:hover & {
`HeaderCell` элемент блока `Table`, стоит описывать стили элемента в в его блоке.

2020-10-05 16:46 UTC, gizeasy commented on src/components/Table/Table.tsx
> +  const headers = transformColumns(columns, getMaxLevel(columns));
думаю нужно вынести в функцию которая вернет все нужные параметры для построения хедера.
чтоб переменные `headers, headerRowsRefs, headerColumnsHeights, headerRowsHeights, lowHeaders` возвращались из нее.

2020-10-06 09:42 UTC, c1n1k commented on src/components/Table/Cell/TableCell.css
> +    .Table-HeaderCell_groupTitle:hover & {
`groupTitle` странное значение модификатора, не понятно какую роль он несёт

2020-10-06 09:49 UTC, gizeasy commented
замечания от дизайнера:
1) горизонтальные подчеркивания только на последнем уровне
2) заголовок последнего уровня шапки всегда 10px, то есть если в шапке 3 уровня то все заголовки 3го уровня 10px
3) `borderBetweenColumns` включает вертикальные бордеры
4) `isResizable` линия не должна перекрывать заголовок родителя
5) `stickyColumns` закрепление колонки происходит по верхнему уровню шапки

2020-10-12 11:17 UTC, gizeasy requested changes

2020-10-12 11:17 UTC, gizeasy commented on src/components/Table/Header/TableHeader.css
> +    &_noHover {
не понятное название модификатора, следует избегать приставок no, not
 я так понял что эти стили нужны только на последнем уровне шапки
может тогда и назвать его `_lastLevel`

2020-10-12 11:17 UTC, gizeasy commented on src/components/Table/Header/TableHeader.css
> +    &_withSmallText {
`_withSmallText` - тоже появляется на последнем уровне заголовков, думаю стоит добавить в `_lastLevel`

2020-10-12 11:17 UTC, gizeasy commented on src/components/Table/Table.tsx
> +  } = useHeaderData(columns);
по названиям переменных не понятно какие конкретно данные возвращаются, стоит подумать над названием и/или добавить описание к хуку

2020-10-12 11:17 UTC, gizeasy commented on src/components/Table/helpers.ts
> +export const useHeaderData = <T extends TableRow>(columns: Array<TableColumn<T>>) => {
нет типов результата функции, понятно что тип сам выводится, но думаю стоит описать заранее ожидаемый результат, чтобы в дальнейшем избегать ошибок.

2020-10-13 07:49 UTC, karpovfv-nedra commented on src/components/Table/helpers.ts
> +  colArr: any[] = [],
сделано

2020-10-13 07:49 UTC, karpovfv-nedra commented on src/components/Table/__tests__/helpers.test.ts
> +    const result = transformColumns(COLUMNS as any, getMaxLevel(COLUMNS as any));
сделано

2020-10-13 07:50 UTC, karpovfv-nedra commented on src/components/Table/Cell/TableCell.css
> +    .Table-HeaderCell_groupTitle:hover & {
перенёс это всё в TableHeader. имя модификатора поменял

2020-10-13 07:50 UTC, karpovfv-nedra commented on src/components/Table/Table.tsx
> +  const headers = transformColumns(columns, getMaxLevel(columns));
сделано

2020-10-13 07:51 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +}: any): React.ReactElement => {
это было временное решение, убрал any

2020-10-13 07:51 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +// @ts-ignore
убрал его

2020-10-13 07:52 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
дев спулил. если про `overflow-wrap: break-word;` то да, этот стиль присутствует

2020-10-13 07:53 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.css
> +    &_noHover {
это нужно для того, чтобы заголовки высокого уровня (родительские) не давали эффекта никакого при наведении. судя по макету, что я видел, при наведении на такую ячейку бэкграунд никак не меняется.

2020-10-13 07:53 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.css
> +    &_noHover {
назвал `_highLevel`

2020-10-13 07:54 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.css
> +    &_withSmallText {
тут назвал `_lowLevel`, потому что на заголовках последнего уровня у нас должен быть текст сайз 10 пикселей

2020-10-13 07:54 UTC, karpovfv-nedra commented on src/components/Table/Table.tsx
> +  } = useHeaderData(columns);
описал типы, написал doc block

2020-10-13 07:54 UTC, karpovfv-nedra commented on src/components/Table/helpers.ts
> +export const useHeaderData = <T extends TableRow>(columns: Array<TableColumn<T>>) => {
описал типы

2020-10-15 09:32 UTC, gizeasy commented
Пожалуйста делай ребейз на ветку, одна задача - один комит. Так просматривать изменения удобнее

2020-10-15 10:26 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
добавиь пожалуйста в `TableCell_isResized` `word-break: break-word;`
я помоему ошибся с `overflow-wrap: break-word;` - не работает
и нужно прокидывать в ячеки шапки `_isResized` чтоб там тоже текст переносился

2020-10-15 10:28 UTC, gizeasy commented on src/components/Table/Header/TableHeader.css
> +    &_noHover {
давай еще доработаем))
сделаем модификатор `level` со значениями `high` и `low`

2020-10-15 11:42 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
сделал

2020-10-15 11:42 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.css
> +    &_noHover {
сделал

2020-10-16 08:40 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
не ко всем ячейкам заголовков применяется `_isResized`
![image](https://user-images.githubusercontent.com/13190808/96236010-28e3c100-0fa4-11eb-8629-2885d02ae095.png)

Применяется только в `Cell_level_low`, нужно чтобы если применяется `_isResized` к ребенку то и к родителю тоже применять

2020-10-16 11:16 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
спасибо! обновил

2020-10-16 11:46 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
![image](https://user-images.githubusercontent.com/13190808/96254179-89cbc300-0fbd-11eb-90da-652c5f457790.png)
сейчас ширина колонок при первом рендере подстраивается по контент `Cell_level_low`, нужно предусмотреть кейс когда заголовок выше имеет большую ширину чем его дети в ютом случае добавить к ширинам колонок это недостающее расстояние. 
К примеру если дети (3 шт) занимают 100 пикселей а родитель 130, то добавить по 10 пикселей к каждому ребенку.
Понимаю что кейс редкий но все-таки думаю стоит предусмотреть

2020-10-16 11:51 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
https://photos.app.goo.gl/VaMKnzziMViq5hRs8

в видео показано 2 варианта ресайза

1) ресайт происзодит по `Cell_level_low` и отрабатывает все верно, все родители выше получают модификатор `_isResized `
2) ресайз происходит по второму уровню заголовка и в том слачае родитель не получает модификатор `_isResized`

2020-10-21 08:04 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
@karpovfv-nedra ?

2020-10-21 08:10 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
@gizeasy `_isResized` я пофиксил, сейчас при ресайзе колонки этот модификатор получают все родители. изменения пока у меня локально лежат.
По поводу расширения родительского заголовка относительно детей при первом рендере: есть предложение создать ишью как импрувмент на это, потому что на данный момент как это сделать мыслей нет. что скажешь?

2020-10-21 08:13 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
@karpovfv-nedra Да давай так и поступим, кейс думаю редким будет.

2020-10-21 08:17 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +export const TableHeader = ({
@gizeasy хорошо. изменения по выставлению модификатора `_isResized` запушил

2020-10-21 08:36 UTC, gizeasy commented
@karpovfv-nedra конфликты вылезли, поправь плиз

2020-10-21 09:02 UTC, karpovfv-nedra commented
> @karpovfv-nedra конфликты вылезли, поправь плиз

@gizeasy сделал

2020-10-21 13:52 UTC, c1n1k approved these changes

2020-10-23 07:44 UTC, gizeasy approved these changes

2020-10-23 07:45 UTC, merged