test(PortalWithTheme): added tests
gazprom-neft/consta-uikit pull request #489
Opened 2020-10-06 12:03 UTC by gizeasy

issue -  #412

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-07 07:20 UTC, c1n1k approved these changes

2020-10-07 07:49 UTC, nekitk requested changes

2020-10-07 07:49 UTC, nekitk commented on src/components/PortalWithTheme/__tests__/PortalWithTheme.test.tsx
> +      expect(getRender()).toHaveTextContent(JSON.stringify(presetGpnDefault));
думаю, лучше проверять не на дефолтном пресете, а на каком-нибудь другом. чтобы убедиться, что правильный пресет наследуется, а не берётся дефолтный.

2020-10-07 07:51 UTC, al-fyodorov requested changes

2020-10-07 07:51 UTC, al-fyodorov commented on src/components/PortalWithTheme/__tests__/PortalWithTheme.test.tsx
> +  props: Omit<PortalWithThemeProps, 'preset'> & { preset?: PortalWithThemeProps['preset'] },
Кажется что достаточно было удалить preset из типа Props, так как в текущих тестах нет проверки переключения темы, и во всех тестах используется `presetGpnDefault`, лучше убрать из теста неиспользуемое условие и удалить расширения типа.

2020-10-07 13:24 UTC, gizeasy commented on src/components/PortalWithTheme/__tests__/PortalWithTheme.test.tsx
> +      expect(getRender()).toHaveTextContent(JSON.stringify(presetGpnDefault));
готово

2020-10-07 13:25 UTC, gizeasy commented on src/components/PortalWithTheme/__tests__/PortalWithTheme.test.tsx
> +  props: Omit<PortalWithThemeProps, 'preset'> & { preset?: PortalWithThemeProps['preset'] },
теперь нужен, в тестах используется `presetGpnDark`

2020-10-07 13:38 UTC, nekitk approved these changes

2020-10-08 09:22 UTC, al-fyodorov approved these changes

2020-10-08 09:46 UTC, merged