Chore/chromatic actions
gazprom-neft/consta-uikit pull request #517
Opened 2020-10-14 12:03 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-16 08:58 UTC, c1n1k approved these changes

2020-10-16 14:43 UTC, al-fyodorov requested changes

2020-10-16 14:43 UTC, al-fyodorov commented on .gitignore
> +.yarn/
А зачем потребовалось добавлять файлы настроек `yarn` в игнорирование git-ом? Вроде тут `yarn` и не коммитится.

2020-10-16 18:22 UTC, gizeasy commented on .gitignore
> +.yarn/
При билде через gitHub actions появлялись эти файлы. И далее скрипт cromatic не мог работать так не все изменения в комм
ите.

2020-10-21 09:18 UTC, al-fyodorov commented on .gitignore
> +.yarn/
Не очень хорошее решение, так как в `.yarnrc` могут появится какие-нибудь общие настройки.

2020-10-21 09:18 UTC, al-fyodorov approved these changes

2020-10-21 11:50 UTC, merged