feat(Table): added onRowHover props
gazprom-neft/consta-uikit pull request #524
Opened 2020-10-15 13:51 UTC by evless

issue -  523

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-16 08:23 UTC, al-fyodorov approved these changes

2020-10-16 08:23 UTC, al-fyodorov commented on src/components/Table/Table.tsx
> +              onMouseEnter={() => onRowHover && onRowHover(rowIdx)}
[note]
Возможно было бы удобнее работать не с индексом строки, а с ее идентификатором `row.id` так как он обязательный для таблицы и используется при указании активной строки.

2020-10-16 08:52 UTC, gizeasy commented
[note] я бы всетаки сделал не onHoverRow а прокидывал из компонента в компонент ячеки состояние `rowHover`, кажется так быстрее работать будет, перерендоривать не всю таблицу а только строку. 
Текущую реализацию оставим если будет потребность в другой то доработаем проброс компонента ячейки через рендер пропс где в него будет падать сотояние rowHover

2020-10-16 08:54 UTC, gizeasy approved these changes

2020-10-16 09:32 UTC, evless commented
Да, помню это предложение, но кажется это можно смотреть если и правда будут случаи падения оптимизации в таких сценариях

2020-10-16 10:10 UTC, c1n1k commented on .github/CODEOWNERS
> +* @tsvetta @gizeasy @c1n1k @al-fyodorov
`@tsvetta` тоже можно удалить

2020-10-16 10:12 UTC, c1n1k approved these changes

2020-10-16 10:14 UTC, c1n1k commented
дёргания  http://s.csssr.ru/UC5KAQ32R/2020-10-16-13-13-19-wxzto.mp4

2020-10-16 10:15 UTC, c1n1k requested changes
есть артефакты

2020-10-16 10:37 UTC, gizeasy commented
> есть артефакты

ну да можно стори поправить

2020-10-16 23:41 UTC, gizeasy approved these changes

2020-10-16 23:41 UTC, gizeasy commented on .github/CODEOWNERS
> +* @tsvetta @gizeasy @c1n1k @al-fyodorov
можно вообще убрать эти изменения, отдельный ПР есть

2020-10-19 08:12 UTC, gizeasy requested changes

2020-10-19 08:12 UTC, gizeasy commented on src/components/Table/Table.tsx
> +              onMouseEnter={() => onRowHover && onRowHover(row.id)}
Было не плохо event из колбека получить, к примеру чтоб взять позицию и спозиционировать тултип на строку.

2020-10-19 12:19 UTC, evless commented
Пофиксил замечания

2020-10-19 15:34 UTC, gizeasy requested changes

2020-10-19 15:34 UTC, gizeasy commented on src/components/Table/Table.tsx
> +              onMouseLeave={(event) => onRowHover && onRowHover(undefined, event)}
сделай объектом onRowHover({id, event})}

2020-10-20 09:10 UTC, evless commented on src/components/Table/Table.tsx
> +              onMouseLeave={(event) => onRowHover && onRowHover(undefined, event)}
did it

2020-10-20 12:55 UTC, gizeasy approved these changes

2020-10-21 08:33 UTC, merged