test(Combobox): added tests
gazprom-neft/consta-uikit pull request #536
Opened 2020-10-19 15:32 UTC by gizeasy

issue - #407

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-20 07:09 UTC, c1n1k approved these changes

2020-10-21 12:44 UTC, al-fyodorov requested changes

2020-10-21 12:44 UTC, al-fyodorov commented on src/components/Combobox/__mocks__/ResizeObserver.ts
> +class ResizeObserver {
Стоит вынести в общие моки для тестов.

2020-10-21 12:44 UTC, al-fyodorov commented on src/components/Combobox/__tests__/Combobox.test.tsx
> +    it(`изменение value c верху`, () => {
Не очень характеризует тест, кажется что-то вроде "изменение value вне компонента Combobox", сейчас звучит как изменения значения которое находится выше текущего выбранного.

2020-10-26 10:37 UTC, gizeasy commented on src/components/Combobox/__mocks__/ResizeObserver.ts
> +class ResizeObserver {
fix

2020-10-26 10:37 UTC, gizeasy commented on src/components/Combobox/__tests__/Combobox.test.tsx
> +    it(`изменение value c верху`, () => {
fix

2020-10-27 10:48 UTC, c1n1k approved these changes

2020-10-28 09:30 UTC, al-fyodorov approved these changes

2020-10-29 12:59 UTC, merged