feat(Choicegroup): added width_full
gazprom-neft/consta-uikit pull request #550
Opened 2020-10-21 10:32 UTC by Miocene

closes #549 

## Описание изменений
Добавляет модификатор width_full, растягивающий группу кнопок на всю ширину родителя.
Также добавлено обрезание слишком длинного текста во всех размерах, если группа кнопок не влезает в родителя.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-21 11:07 UTC, fooontic requested changes

2020-10-21 11:07 UTC, fooontic commented on src/components/ChoiceGroup/ChoiceGroup.css
> +    flex-shrink: 1;
нужно ли указывать flex-shrink? по умолчанию он и так равен 1

2020-10-21 11:07 UTC, fooontic commented on src/components/ChoiceGroup/__stories__/ChoiceGroup.mdx
> +Не рекомендуется использовать в одной группе **больше шести** кнопок.
Я бы ещё добавил, что если контент не влезает, он уходит за многоточие

2020-10-21 11:44 UTC, gizeasy requested changes

2020-10-21 11:44 UTC, gizeasy commented on src/components/ChoiceGroup/__stories__/ChoiceGroup.mdx
> +Используется для поддержания области формы или отделения наследуемых частей формы от основных.
Нужно добавить какое свойство компонента отвечает за это, выше есть пример

2020-10-21 11:45 UTC, gizeasy commented
В таблицу свойств нужно добавить описание нового c указанием ссылки на `Группа кнопок в ширину блока`

2020-10-21 13:34 UTC, fooontic approved these changes

2020-10-22 12:09 UTC, gizeasy approved these changes

2020-10-22 12:10 UTC, merged