docs(Icon): add docs
gazprom-neft/consta-uikit pull request #552
Opened 2020-10-21 11:27 UTC by gizeasy

issue -  #545

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-23 09:17 UTC, fooontic requested changes
@kolebayev сможешь помочь с докой по иконкам? надо бы добавить общее описание иконок.

2020-10-27 11:40 UTC, kolebayev commented
@gizeasy @fooontic закинул общее описание иконок

2020-10-29 13:27 UTC, fooontic requested changes

2020-10-29 13:27 UTC, fooontic commented on src/icons/Icon/__stories__/Icon.mdx
> +Взглянув на иконку, нужно однозначно понимать какой посыл она несет.
@kolebayev хорошая вводная часть. Можно тебя попросить ещё нечто подобное добавить https://www.figma.com/file/Xf4HX23ULkEQnJoiyNmUkM/How-to-start?node-id=74%3A6 Тут много полезного про создание своих иконок и как их контрибьютить. Нам это тоже здесь важно.

2020-10-29 13:30 UTC, fooontic commented on src/icons/Icon/__stories__/Icon.mdx
> +Компоненты **CONSTA** принимают иконки определенного типа. Чтобы ваши иконки совпадали этому типу,
Давайте не писать Consta большими буквами

2020-10-30 10:47 UTC, kolebayev commented on src/icons/Icon/__stories__/Icon.mdx
> +Взглянув на иконку, нужно однозначно понимать какой посыл она несет.
![изображение](https://user-images.githubusercontent.com/24884175/97696085-14301e80-1ab6-11eb-8198-4572b5fc7c2d.png)
@fooontic Рекомендации, которые касаются отрисовки иконок (дизайнеров), добавлю на соседнюю страницу в раздел Icons. Сторибук все-таки для разработчиков больше, не хочу мешать теплое с мягким

2020-11-01 12:01 UTC, kolebayev commented on src/icons/Icon/__stories__/Icon.mdx
> +Взглянув на иконку, нужно однозначно понимать какой посыл она несет.
отбой, в доку иконок просто добавлю дополнительный раздел

2020-11-11 08:51 UTC, fooontic commented on src/icons/Icon/__stories__/Icon.mdx
> +Взглянув на иконку, нужно однозначно понимать какой посыл она несет.
@kolebayev сторибук у нас для всех. Не только для разработчиков, так что можешь прямо туда. В перспективе код будет скрыт по умолчанию, чтобы как раз не отпугивать остальных

2020-11-11 08:52 UTC, fooontic commented on src/icons/Icon/__stories__/Icon.mdx
> +Взглянув на иконку, нужно однозначно понимать какой посыл она несет.
Но предлагаю текущий вариант доки уже залить, остальное уже потом драбатывать

2020-11-12 08:33 UTC, merged