feat(Table): added possibility to render large rows count
gazprom-neft/consta-uikit pull request #555
Opened 2020-10-23 11:29 UTC by karpovfv-nedra

## Описание изменений

Добавлена возможность отображения большого количества строк в таблице.

https://github.com/gazprom-neft/consta-uikit/issues/442

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-26 09:56 UTC, gizeasy commented
Нужно чтоб сверху при скроле в низ, вместо контента добавлялся отступ размером этого контента.

2020-10-26 10:06 UTC, nedradigital commented
> Нужно чтоб сверху при скроле в низ, вместо контента добавлялся отступ размером этого контента.

А что делать при ресайзе окна или таблицы? это ведь уже будет неверный отступ

2020-10-26 10:09 UTC, gizeasy commented
> > Нужно чтоб сверху при скроле в низ, вместо контента добавлялся отступ размером этого контента.
> 
> А что делать при ресайзе окна или таблицы? это ведь уже будет неверный отступ

Точно. Ну тогда не надо.

2020-10-26 10:14 UTC, gizeasy requested changes

2020-10-26 10:14 UTC, gizeasy commented on src/components/Table/helpers.ts
> +  enabled: boolean,
Не совсем понял зачем параметр `enabled`?
Кажется что лишний, и хук вызывать можно только когда `lazyLoad = true`

2020-10-26 10:28 UTC, karpovfv-nedra commented on src/components/Table/helpers.ts
> +  enabled: boolean,
Мы постарались по максимуму вынести эту функциональность в хук, для того, чтобы не нагромождать код в Table.tsx и не писать многих условий, таких как: слайсить ли данные, проставлять ли рефы.

2020-10-26 10:31 UTC, gizeasy commented on src/components/Table/helpers.ts
> +  enabled: boolean,
👌

2020-10-26 10:32 UTC, gizeasy commented
В коммит добавте номер ишью

2020-10-26 10:32 UTC, gizeasy approved these changes

2020-10-26 10:37 UTC, karpovfv-nedra commented
> В коммит добавте номер ишью

готово

2020-10-27 09:46 UTC, c1n1k approved these changes

2020-10-27 10:09 UTC, merged