feat(withTooltip): added HOC withTooltip
gazprom-neft/consta-uikit pull request #564
Opened 2020-10-28 10:14 UTC by gizeasy

issue -  #462

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-10-28 10:29 UTC, fooontic approved these changes
Надо бы в документацию по кнопке добавить, что с помощью ХОКа можно добавить тултип

2020-10-28 10:29 UTC, fooontic commented on src/hocs/withTooltip/__stories__/withTooltip.mdx
> +# HOC withTooltip
Не уверен, что этот раздел надо называть HOC. Надо подумать над каким-то более человечным названием раздела. Может «Утилиты»?

2020-10-28 10:29 UTC, fooontic commented on src/hocs/withTooltip/__stories__/withTooltip.mdx
> +# HOC withTooltip
И кстати читается, как Нос =)

2020-10-28 10:43 UTC, gizeasy commented on src/hocs/withTooltip/__stories__/withTooltip.mdx
> +# HOC withTooltip
Компонент высшего порядка (Higher-Order Component, HOC)

2020-10-28 11:52 UTC, al-fyodorov requested changes

2020-10-28 11:52 UTC, al-fyodorov commented on src/hocs/withTooltip/withTooltip.tsx
> +export function withTooltip<COMPONENT_PROPS extends ComponentProps>(hocProps?: TooltipProps) {
Вот пример когда тип выводится автоматически дженериком для компонента который был указан:
```tsx
export function withTooltip(params?: TooltipProps) {
  return function<Props extends {}>(Component: React.ComponentType<Props>) {
    return React.forwardRef<HTMLElement, WithToltipProps<Props>>((props, ref) => {
      return <Component ref={ref} {...props} />;
    });
  };
}
```

Использование:
```tsx
// Props вывелись на основе переданного компонента.
const ButtonWithTooltip = withTooltip()(Button);
```

Сейчас опять какая-то странная проблема с выводом типа в теле функции, и кроме того заставляет пользователя указывать тип `Props` для передаваемого компонента, что добавляет дополнительную работу, которой можно избежать если правильно воспользоваться generic-ами. Стоит исправить такие моменты.

2020-10-28 11:53 UTC, al-fyodorov commented on src/hocs/withTooltip/withTooltip.tsx
> +export function withTooltip<COMPONENT_PROPS extends ComponentProps>(hocProps?: TooltipProps) {
Ну и кроме того убирает костылизацию в виде:
```ts
as unknown) as ComponentProps extends { as?: keyof JSX.IntrinsicElements }
      ? ComponentWithAs<WithToltipProps<ComponentProps>>
      : React.ComponentType<WithToltipProps<ComponentProps>>;
```

2020-10-28 12:55 UTC, gizeasy commented on src/hocs/withTooltip/withTooltip.tsx
> +export function withTooltip<COMPONENT_PROPS extends ComponentProps>(hocProps?: TooltipProps) {
спасибо попробую

2020-10-28 13:06 UTC, gizeasy commented on src/hocs/withTooltip/withTooltip.tsx
> +export function withTooltip<COMPONENT_PROPS extends ComponentProps>(hocProps?: TooltipProps) {
все равно костыль нужен в таком случае, теряются параметры дженерика компонента
![image](https://user-images.githubusercontent.com/13190808/97439689-89c1b080-1937-11eb-8439-746a6de19580.png)

еще подумаю как можно сделать

2020-10-28 20:58 UTC, gizeasy commented on src/hocs/withTooltip/__stories__/withTooltip.mdx
> +# HOC withTooltip
убрал из названия

2020-10-28 21:04 UTC, gizeasy commented on src/hocs/withTooltip/withTooltip.tsx
> +export function withTooltip<COMPONENT_PROPS extends ComponentProps>(hocProps?: TooltipProps) {
поправил, теперь не надо с верху указывать тип пропсов компонента
костыль в виде `as unknown) as` пришлось оставить, переписав на `as unknown) as COMPONENT_TYPE | React.ComponentType<WithToltipProps<COMPONENT_PROPS>>;`  теперь но возвращает тип прокинутого компонета с сохранением дженериков 
еще есть момент
```ts
COMPONENT_TYPE extends
      | React.ComponentType<ComponentProps>
      | ((props: ComponentProps) => React.ReactElement | null),
```

`((props: ComponentProps) => React.ReactElement | null),` в дальнейшем вырежу, как поправлю типы компонентов которые завернуты в `forwardRefWithAs`

2020-11-05 06:46 UTC, c1n1k approved these changes
я бы добавил ещё пример тултипа с иконкой

2020-11-05 07:04 UTC, al-fyodorov requested changes

2020-11-05 07:04 UTC, al-fyodorov commented on src/hocs/withTooltip/withTooltip.tsx
> +    }) as unknown) as COMPONENT_TYPE | React.ComponentType<WithToltipProps<COMPONENT_PROPS>>;
Может заложим в эту задачу больше времени? Кажется, что стоит сразу разобраться как лучше реализовывать подобные вещи, чтобы потом не возвращаться к ним снова. К тому же эту функциональность пока можно реализовать снаружи и без этого хока.

Еще бы посмотрел в сторону полного запрещения приведения типов, и использования `any` в проекте, так как тут нет обработки огромного массива данных, и все данные довольно примитивные, так что кажется приводить типы тут и не следует.

2020-11-24 09:31 UTC, gizeasy commented on src/hocs/withTooltip/withTooltip.tsx
> +    }) as unknown) as COMPONENT_TYPE | React.ComponentType<WithToltipProps<COMPONENT_PROPS>>;
не получается не приводя к типам:
пробовал:
```tsx
return function<
    COMPONENT_TYPE extends
      | React.ComponentType<ComponentProps>
      | ((props: ComponentProps) => React.ReactElement | null)
  >(Component: COMPONENT_TYPE) {
    type COMPONENT_PROPS = React.ComponentProps<COMPONENT_TYPE>;
    return React.forwardRef<Element, WithToltipProps<COMPONENT_PROPS>>((props, ref) => {
```

и да тип выводится но теряются пропсы компонента которые зависят от Тэга компонента `As extends keyof JSX.IntrinsicElements = Tag`, они вообще всегда теряются как только в любой хок заворачиваешь компонент. Вариант каждый хок наделять джененриком выводящий пропсы по тэгу не подходит, так как не каждый компоненту это надо. Вот я принял решение отдавать ровно тот тип компонента который мы прокинули в хок + пропсы которыми расширился компонент. Другого решения не увидел, может у тебя есть идеи? 

Текущее решение в целом не ломает ни чего: типы в хоке также нормально выводятся, при использовании хока также с типами все в порядке. Я согласен с тем что приводить типы это не лучшая затея, но я лучше не придумал.

2020-12-10 15:46 UTC, dmitriykorsakovnedra commented on src/hocs/withTooltip/withTooltip.tsx
> +export function withTooltip(hocProps?: TooltipProps) {
Есть ощущение что отказ от HOC в пользу обычного компонента все сильно упростит :)

2020-12-21 12:07 UTC, gizeasy commented
Сейчас если `mode = mouseover` и уводим курсор в сторону тулитпа, то тултип скрывается, надо поправить

2020-12-25 13:10 UTC, dmitriykorsakovnedra approved these changes

2020-12-30 11:01 UTC, merged