feat(Table): added smart sorting
gazprom-neft/consta-uikit pull request #577
Opened 2020-10-30 12:50 UTC by karpovfv-nedra

## Описание изменений

Добавлена умная сортировка. (добавлен новый компонент SmartSorting).
https://github.com/gazprom-neft/consta-uikit/issues/447

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-11-02 09:24 UTC, gizeasy requested changes

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +  onUpdate: (o: Array<OrderedOption>) => void;
onChange думаю понятнее будет

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +  initialValues: Array<OrderedOption>;
может просто value, понятно что это значение сортировки, которое всегда нужно указывать.

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +  const [sortedOptions, setSortedOptions] = React.useState<OrderedOption[]>(initialValues);
еще нужно добавить обновление sortedOptions если value обновился, на случай изменения состояния сверху

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +const orderOptions = [
сделай чтоб можно было указать компоненту парамерты сортировки, по умолчанию этот массив.

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +        Умная сортировка
Нужно иметь возможность указать Title
и все слова в компоненте ниже

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +export const SmartSortingWindow: React.FC<SmartSortingWindowProps> = ({
SmartSortingWindow -> SmartSorting
название компонента должно совпадать с названием файла

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +    <Modal isOpen={isOpen} className={cnSmartSortingWindow(null, [className])} hasOverlay={false}>
cnSmartSortingWindow -> cnSmartSorting

2020-11-02 09:24 UTC, gizeasy commented on src/components/SmartSorting/SmartSorting.tsx
> +
Добавь пожалуйста в доку таблицы пример добавления умной сотировки, сначала код потом пример работы компонента.

2020-11-02 10:34 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +  onUpdate: (o: Array<OrderedOption>) => void;
согласен, поправил

2020-11-02 10:34 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +  initialValues: Array<OrderedOption>;
поменял на `value`

2020-11-02 10:34 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +  const [sortedOptions, setSortedOptions] = React.useState<OrderedOption[]>(initialValues);
сделал

2020-11-02 10:35 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +const orderOptions = [
добавил

2020-11-02 10:36 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +        Умная сортировка
сделал для заголовка самого окна, заголовка опций для сортировки и для параметров сортировки. по дефолту прежние значения

2020-11-02 10:36 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +export const SmartSortingWindow: React.FC<SmartSortingWindowProps> = ({
переименовал

2020-11-02 10:36 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +    <Modal isOpen={isOpen} className={cnSmartSortingWindow(null, [className])} hasOverlay={false}>
сделал

2020-11-02 10:36 UTC, karpovfv-nedra commented on src/components/SmartSorting/SmartSorting.tsx
> +
обновил доку

2020-11-03 08:59 UTC, fooontic commented
@karpovfv-nedra ребят, мы же когда это обсуждали, я же говорил, что данная фича это антипаттерн и не должно быть частью таблицы и вообще в дизайн-системе, так пока верим, что это решение не должны часто использовать.

2020-11-03 09:03 UTC, karpovfv-nedra commented
> @karpovfv-nedra ребят, мы же когда это обсуждали, я же говорил, что данная фича это антипаттерн и не должно быть частью таблицы и вообще в дизайн-системе, так пока верим, что это решение не должны часто использовать.

@fooontic , Принял. Мы таблицу не трогали вообще, окно умной сортировки создали отдельным компонентом, и показали как можно им пользоваться на примере таблицы

2020-11-03 10:26 UTC, dmitriykorsakovnedra commented
> @karpovfv-nedra ребят, мы же когда это обсуждали, я же говорил, что данная фича это антипаттерн и не должно быть частью таблицы и вообще в дизайн-системе, так пока верим, что это решение не должны часто использовать.

Видимо недопонимание, мы поняли что это просто не должно быть частью таблицы, и сделали отдельный компонент умной сортировки, на таблицу он не завязан, он принимает поля по которым можно сортировать и отдает порядок и направление сортировок. Использоваться может с чем угодно.

Нам убрать пример с таблицей? Или вообще в проект полностью перенести компонент?

2020-11-05 06:53 UTC, fooontic commented
> Нам убрать пример с таблицей? Или вообще в проект полностью перенести компонент?

Давайте пока оставим ПР висеть. Пришла в голову мысль, чтобы ваш пример уж не пропадал, запихнуть его в конец документации по таблице, как альтернативный сценарий.

2021-09-14 12:06 UTC, arhayka approved these changes

2021-11-29 12:40 UTC, closed without merging