feat(Selects): added form modifier for dropdown
gazprom-neft/consta-uikit pull request #592
Opened 2020-11-09 11:24 UTC by gizeasy

issue -  #531

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-11-11 08:25 UTC, fooontic requested changes

2020-11-20 10:06 UTC, c1n1k approved these changes

2020-11-23 13:22 UTC, gizeasy commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.css
> +      border-radius: calc(var(--input-height) / 2);
@fooontic fix

2020-11-23 13:25 UTC, fooontic approved these changes

2020-11-23 13:48 UTC, merged