GDC-978: Доработки по DatePicker
gazprom-neft/consta-uikit pull request #593
Opened 2020-11-09 13:43 UTC by typeetfunc

issue -  https://jira.csssr.io/browse/GDC-978
## Описание изменений
- исправил ошибки
- добавил возможность делать кастомизацию заговленных периодов выбора в датапикере в режиме выбора периода

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x ] PR: назначен исполнитель PR и указаны нужные лейблы
- [x ] PR: проверен diff, ничего лишнего в PR не попало
- [x] PR: прилинкованы затронутые issue и связанные PR
- [x ] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [x ] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [x] Верстка: используются [переменные](../src/components/Theme)
- [x] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [x] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-11-11 11:16 UTC, gizeasy commented
нет документации хотя-бы маломальской с таблицей пропсов. В идеале с примерами

2020-11-11 11:35 UTC, gizeasy commented
перенаправил ветку в дев, чтоб было видно все изменения, проще писать коментарии

2020-11-11 14:19 UTC, gizeasy requested changes

2020-11-11 14:19 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +      renderControls: props.renderControls,
Сейчас сделано так что если `type: 'date-range'`для каждой из дат попадет контрол из `props.renderControls`, надо чтоб просто рисовался `props.renderControls` и в него уже падали value и прочие значения, чтоб была возможность допустим иметь одну кнопку и по ней уже выбирать диапазон дат

2020-11-11 14:19 UTC, gizeasy commented on src/components/DatePicker/DatePicker.tsx
> +    options: { date: Date } & MinMaxDate,
давай `date` переименуем в более понятное visibleDate ?

2020-11-11 14:19 UTC, gizeasy commented on src/components/DatePicker/DatePickerMonthsSliderRange/DatePickerMonthsSliderRange.tsx
> +export const DatePickerMonthsSliderRange: React.FC<RenderSliderProps<DateRange>> = ({
Заметил такую штуку, если указать двухстолетний период в доступных датах (min-max) то появляются сильные лаги, думаю нужно оптимизировать пересчеты через useMemo и добавить что-то вроде виртуального скрола, чтоб реально отображались элементы только за 3 года, если мы рискуем потерять анимацию слайдера при изменении даты через инпут, то и ладно, оставить ее только по кнопочкам сладера.

2020-11-12 11:52 UTC, gizeasy commented
предыдущие обсуждения https://github.com/gazprom-neft/consta-uikit/pull/433

2020-11-26 15:42 UTC, graberzz commented on src/components/DatePicker/DatePicker.tsx
> +  let dateControls;
сюда записывается результат renderRangeControls/renderSingleControls

2020-11-26 15:48 UTC, graberzz commented
[Отдельным коммитом](https://github.com/gazprom-neft/consta-uikit/pull/593/commits/531c542b1a6a5230f378361ee892b5f17a26f914) добавил mdx, также поправил небольшие реквесты, помеченные "👍".
Остальное вынес в issues, доступные выше ⏫, просьба глянуть.

2020-11-30 09:37 UTC, gizeasy requested changes

2020-11-30 09:37 UTC, gizeasy commented on src/components/DatePicker/__stories__/DatePicker.mdx
> +| renderControls?       | `{ value?: Dateб [Date?, Date?]; onChange: (value?: Date, [Date?, Date?]) => void; isInvalid?: boolean; tooltipContent?: React.ReactNode; isCalendarOpened?: boolean;,  size?
Dateб опечатка

2020-11-30 09:37 UTC, gizeasy commented on tsconfig.json
> +    "downlevelIteration": true,
что дает?

2020-12-01 10:15 UTC, graberzz commented on src/components/DatePicker/__stories__/DatePicker.mdx
> +| renderControls?       | `{ value?: Dateб [Date?, Date?]; onChange: (value?: Date, [Date?, Date?]) => void; isInvalid?: boolean; tooltipContent?: React.ReactNode; isCalendarOpened?: boolean;,  size?
Поправил

2020-12-01 10:15 UTC, graberzz commented on tsconfig.json
> +    "downlevelIteration": true,
Кажется без этой опции все ОК, убрал

2021-07-13 15:48 UTC, closed without merging