Table: объединение ячеек
gazprom-neft/consta-uikit pull request #601
Opened 2020-11-13 09:49 UTC by karpovfv-nedra

## Описание изменений

Добавлена возможность объединения ячеек в таблице (https://github.com/gazprom-neft/consta-uikit/issues/499)

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-11-30 09:21 UTC, gizeasy requested changes

2020-11-30 09:21 UTC, gizeasy commented on src/components/Table/Table.tsx
> +      if (column.mergeCells) style.gridRowEnd = `span ${rowSpan}`;
предлагаю задавать тут переменную `--row-span`
и в css ее использовать `grid-row-end: span var(--row-span);`

2020-11-30 09:21 UTC, gizeasy commented
Поправить конфликты

2020-11-30 09:29 UTC, gizeasy commented on src/components/Table/Table.tsx
> +      if (column.mergeCells) style.gridRowEnd = `span ${rowSpan}`;
пример можно посмотреть в компоненте Avatar

2020-11-30 10:33 UTC, karpovfv-nedra commented on src/components/Table/Table.tsx
> +      if (column.mergeCells) style.gridRowEnd = `span ${rowSpan}`;
обновил, спасибо

2020-12-01 13:01 UTC, gizeasy approved these changes

2020-12-04 08:21 UTC, c1n1k approved these changes

2020-12-04 09:32 UTC, merged