feat(RadioGroup): added RadioGroup component
gazprom-neft/consta-uikit pull request #612
Opened 2020-11-23 09:17 UTC by karpovfv-nedra

## Описание изменений

Добавлен компонент RadioGroup

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-11-23 10:10 UTC, gizeasy requested changes

2020-11-23 10:12 UTC, gizeasy requested changes

2020-11-23 10:12 UTC, gizeasy commented on src/components/RadioGroup/RadioGroup.css
> +      .Radio:not(:last-child) {
Нужно добавить класс элемента `.RadioGroup-Item` и на него уже навесить стили.

2020-11-23 10:46 UTC, gizeasy approved these changes

2020-11-23 10:46 UTC, gizeasy commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
я исправил баг с типом в useChoseGroup 
https://github.com/gazprom-neft/consta-uikit/pull/614

после принятия надо будет пофиксить тип onChange

можешь апрувнуть мою прку и она пролезет в дев быстрее))

2020-11-23 10:47 UTC, gizeasy requested changes
1

2020-11-24 08:07 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +export const RadioGroup: RadioGroup = (props: Props<any>) => {
спасибо! реф добавил

2020-11-24 08:07 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +  className?: string;
сделал

2020-11-24 08:07 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +  disabled?: boolean;
тут пока ничего не менял

2020-11-24 08:07 UTC, karpovfv-nedra commented on src/components/RadioGroup/__stories__/RadioGroup.stories.tsx
> +const items = [
сделал

2020-11-24 08:07 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.css
> +      .Radio:not(:last-child) {
поправил, спасибо!

2020-11-24 08:08 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
аппрувнул, ждём мержа и поправлю тип в текущем пр

2020-11-25 07:48 UTC, gizeasy commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
вмержил

2020-11-25 07:52 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
ага, сейчас внесу изменения. мы оставим сейчас возможность дизейбла всей группы, или будем дизейблить конкретные айтемы в группе?

2020-11-25 08:00 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
тип обновил

2020-11-25 09:14 UTC, gizeasy requested changes

2020-11-25 09:14 UTC, gizeasy commented on src/components/RadioGroup/RadioGroup.tsx
> +type Props<ITEM = any> = PropsWithHTMLAttributesAndRef<CommonProps<ITEM>, HTMLDivElement>;
any не нравиться((
сделай по аналогии с
https://github.com/gazprom-neft/consta-uikit/pull/618

2020-11-25 09:16 UTC, gizeasy commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
сделай возможность дисеблить и так и так, лишним точно не будет

2020-11-25 11:23 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +  onChange: (props: { e: React.ChangeEvent<HTMLInputElement>; value: ITEM | null }) => void;
добавил

2020-11-25 11:23 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +type Props<ITEM = any> = PropsWithHTMLAttributesAndRef<CommonProps<ITEM>, HTMLDivElement>;
готово

2020-11-25 13:26 UTC, gizeasy requested changes

2020-11-25 13:26 UTC, gizeasy commented on src/components/RadioGroup/RadioGroup.tsx
> +          disabled={disabled || item.disabled}
сдейлай через функцию как `getLabel(item)` так как не обязательно `disabled` будет в item, может другое свойство или вообще своя хитрая логика.

2020-11-25 13:49 UTC, karpovfv-nedra commented on src/components/RadioGroup/RadioGroup.tsx
> +          disabled={disabled || item.disabled}
сделал через функцию `getDisabled(item)`

2020-12-01 12:07 UTC, gizeasy requested changes

2020-12-01 12:07 UTC, gizeasy commented on src/components/RadioGroup/__tests__/RadioGroup.test.tsx
> +const getItems = () => getRender().querySelectorAll('.Radio');
querySelectorAll(`.${cnRadioGroup('Item')}`);
 - таким образом даже если у компонента Radio поменяется класс то тест не ляжет, да и работать луче с элементами компонента а не с компонентами которые импортим

2020-12-01 12:07 UTC, gizeasy commented on src/components/RadioGroup/__tests__/RadioGroup.test.tsx
> +  });
Добавь пожалуйста проверку disable и onChange

2020-12-01 12:07 UTC, gizeasy commented on src/components/Theme/__stories__/examples/ThemeExampleColors/ThemeExampleColors.css
> +    width: 100%;
Это не случайно сюда попало?

2020-12-02 07:15 UTC, karpovfv-nedra commented on src/components/RadioGroup/__tests__/RadioGroup.test.tsx
> +const getItems = () => getRender().querySelectorAll('.Radio');
спасибо, понял) обновил

2020-12-02 07:15 UTC, karpovfv-nedra commented on src/components/RadioGroup/__tests__/RadioGroup.test.tsx
> +  });
добавил

2020-12-02 07:16 UTC, karpovfv-nedra commented on src/components/Theme/__stories__/examples/ThemeExampleColors/ThemeExampleColors.css
> +    width: 100%;
это отработал линтер --fix на прекоммите. тут правило сработало у стайл линта order/properties-order

2020-12-04 08:13 UTC, c1n1k approved these changes

2020-12-04 09:40 UTC, gizeasy approved these changes

2020-12-04 09:41 UTC, merged