Исключить value из selects
gazprom-neft/consta-uikit pull request #620
Opened 2020-11-25 12:25 UTC by c1n1k

## Описание изменений

- добавил передачу класса для выпадающего блока
- исключил value из внутреннего состояния
- добавил передачу ref для выпадающего блока, необходимо для решения проблемы с кликами по опциям в случае, когда select располгается в модальном окне

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [x] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-11-25 14:35 UTC, gizeasy requested changes

2020-11-25 14:35 UTC, gizeasy commented on src/components/BasicSelect/BasicSelect.tsx
> +  const defaultOptionsRef = useRef<HTMLDivElement | null>(null);
кажется что в типе null можно убрать
оставить useRef<HTMLDivElement>

2020-11-25 14:35 UTC, gizeasy commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
>        <div className={cnSelect('List', { size, form })} ref={optionsRef}>
получается что optionsRef это все-таки реф списка а не каждого элемента рефы, давай переназавем его в dropdownRef, так понятнее будет. и кажется что можно накинуть его конкретно на Popover, кажется что также все работать будет

2020-11-25 14:35 UTC, gizeasy commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +  const val = useMemo(() => (value !== undefined ? value : props.value), [props.value, value]);
не понял зачем тут useMemo, разве сильно выигрываем от этого?

2020-11-25 14:35 UTC, gizeasy commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    onChange?(v: ITEM[] | undefined | null): void;
давай не будем в колбэке возращать `undefined`, если ни чего не выбрано то возвращай `null`.

2020-11-25 14:35 UTC, gizeasy commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +      isInteractive
`isInteractive` по умолчанию true

2020-11-25 14:59 UTC, c1n1k commented on src/components/BasicSelect/BasicSelect.tsx
> +  const defaultOptionsRef = useRef<HTMLDivElement | null>(null);
без `null` сыпятся ошибки

2020-11-25 15:14 UTC, c1n1k commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
>        <div className={cnSelect('List', { size, form })} ref={optionsRef}>
переименовал, на `Popover` не вешается

2020-11-25 15:17 UTC, c1n1k commented on src/components/Combobox/__stories__/Combobox.stories.tsx
> +  const val = useMemo(() => (value !== undefined ? value : props.value), [props.value, value]);
убрал

2020-11-25 15:18 UTC, c1n1k commented on src/components/MultiCombobox/MultiCombobox.tsx
> +    onChange?(v: ITEM[] | undefined | null): void;
убрал

2020-11-25 15:18 UTC, c1n1k commented on src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
> +      isInteractive
убрал

2020-11-25 15:22 UTC, gizeasy approved these changes

2020-11-25 16:14 UTC, maksim-kononov-csssr approved these changes

2020-11-26 08:00 UTC, gizeasy requested changes

2020-11-26 08:00 UTC, gizeasy commented on src/components/SelectComponents/types.ts
> +  classNameDropdown?: string;
classNameDropdown -> dropdownClassName

2020-11-26 08:00 UTC, gizeasy commented on src/components/SelectComponents/types.ts
> +  classNameDropdown?: string;
и добавить в доку

2020-11-26 10:09 UTC, merged