feat(Pagination): added Pagination component
gazprom-neft/consta-uikit pull request #643
Opened 2020-11-30 13:27 UTC by karpovfv-nedra

## Описание изменений

Добавлен компонент Pagination

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-02 08:44 UTC, gizeasy approved these changes

2020-12-02 08:44 UTC, gizeasy commented on src/components/Pagination/Pagination.tsx
> +  onChangePage: (pageNumber: number) => void | null;
думаю можно оставить просто onChange.
добавь в параметры колбека event
'(props:{pageNumber: number, e: event}) => void'
зачем `| null`, может просто не обязательность свойства сделать?

2020-12-02 08:44 UTC, gizeasy commented on src/components/Pagination/Pagination.tsx
> +type Props = {
в Props добавь все из HTMLDIVELEMENT через PropsWithHTMLAttributes

2020-12-02 08:44 UTC, gizeasy commented on src/components/Pagination/Pagination.tsx
> +export const Pagination: Pagination = (props) => {
добавь React.forwardRef

2020-12-02 11:43 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.tsx
> +  onChangePage: (pageNumber: number) => void | null;
да, спасибо, обновил

2020-12-02 11:43 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.tsx
> +type Props = {
сделал

2020-12-02 11:43 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.tsx
> +export const Pagination: Pagination = (props) => {
сделал

2020-12-03 15:10 UTC, c1n1k reviewed
добавь хотя бы title
![image](https://user-images.githubusercontent.com/420945/101047181-b306d980-3592-11eb-9a63-8096fa50c94c.png)

2020-12-04 05:39 UTC, karpovfv-nedra commented
> добавь хотя бы title
> ![image](https://user-images.githubusercontent.com/420945/101047181-b306d980-3592-11eb-9a63-8096fa50c94c.png)

добавил

2020-12-04 08:21 UTC, fooontic requested changes
Привет!
У нас появились изменения со стороны дизайна. Сейчас их опишу. У нас Фигма временно залочена из-за просроченного платежа, поэтому пока все изменения на другой странице: https://www.figma.com/file/xTrDSUNC8sYTo3iR2yduyX/%D0%9F%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0%D1%86%D0%B8%D1%8F-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8?node-id=1%3A300

1. Изменяется цвета кнопок. В состоянии покоя у кнопки нет фонового цвета, а цвет текста `--color-control-typo-ghost`. При ховере цвет фона становится `--color-control-bg-ghost-hover`, а текст `--color-control-typo-ghost-hover`. В состоянии активной страницы фон `--color-control-bg-ghost`, текст `--color-control-typo-ghost`
2. Кнопки назад и вперёд обрастают лейблами «Назад» и «Вперёд» соответсвенно.
3. В дефолтном модификации кнопки Назад и Вперёд всегда видны, если в них есть есть необходимость. Есть есть куда листать назад — кнопка Назад есть. Если листать некуда, кнопки Назад нет. Именно физически нет. Под неё не надо резервировать место. Аналогично с кнопкой Вперёд.
4. Под кнопками появляется подпись с указанием горячих клавиш. По умолчанию это Alt →/ Alt ←. По факту сама пагинация должна только ловить нажатия на эти кнопки и переключать страницы. Также надо оставить возможность изменить комбинацию клавиш и подписи, на случай если нужно будет переопределить.   
5. Сам контейнер для пагинации теперь должен занимать 100% ширины. Исходя из этого также появляются доп. модификации на выравнивание: слева, по центру, справа. 
6. Появляется новая модификация minified. В ней кнопки Назад и Вперёд появляются только по ховеру и место под них зарезервировано (они скрыты только визуально). Подписей с горячими клавишами у минифицированной версии нет. 

Вроде все изменения. Если что-то неясно, можем созвониться

2020-12-04 08:26 UTC, karpovfv-nedra commented
> Привет!
> У нас появились изменения со стороны дизайна. Сейчас их опишу. У нас Фигма временно залочена из-за просроченного платежа, поэтому пока все изменения на другой странице: https://www.figma.com/file/xTrDSUNC8sYTo3iR2yduyX/%D0%9F%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0%D1%86%D0%B8%D1%8F-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8?node-id=1%3A300
> 
> 1. Изменяется цвета кнопок. В состоянии покоя у кнопки нет фонового цвета, а цвет текста `--color-control-typo-ghost`. При ховере цвет фона становится `--color-control-bg-ghost-hover`, а текст `--color-control-typo-ghost-hover`. В состоянии активной страницы фон `--color-control-bg-ghost`, текст `--color-control-typo-ghost`
> 2. Кнопки назад и вперёд обрастают лейблами «Назад» и «Вперёд» соответсвенно.
> 3. В дефолтном модификации кнопки Назад и Вперёд всегда видны, если в них есть есть необходимость. Есть есть куда листать назад — кнопка Назад есть. Если листать некуда, кнопки Назад нет. Именно физически нет. Под неё не надо резервировать место. Аналогично с кнопкой Вперёд.
> 4. Под кнопками появляется подпись с указанием горячих клавиш. По умолчанию это Alt →/ Alt ←. По факту сама пагинация должна только ловить нажатия на эти кнопки и переключать страницы. Также надо оставить возможность изменить комбинацию клавиш и подписи, на случай если нужно будет переопределить.
> 5. Сам контейнер для пагинации теперь должен занимать 100% ширины. Исходя из этого также появляются доп. модификации на выравнивание: слева, по центру, справа.
> 6. Появляется новая модификация minified. В ней кнопки Назад и Вперёд появляются только по ховеру и место под них зарезервировано (они скрыты только визуально). Подписей с горячими клавишами у минифицированной версии нет.
> 
> Вроде все изменения. Если что-то неясно, можем созвониться

@fooontic , привет!
Вроде всё понятно по изменениям. Если у меня возникнут вопросы во время реализации, я обязательно обращусь)

2020-12-08 12:29 UTC, karpovfv-nedra commented
обновил

2020-12-10 08:19 UTC, gizeasy commented
подтяни дев в ветку, там теперь стори по другому стали называться

2020-12-10 08:39 UTC, gizeasy requested changes

2020-12-10 08:39 UTC, gizeasy commented on src/components/Pagination/Pagination.tsx
> +  onChange: (props: { pageNumber: number; e?: React.ChangeEvent }) => void;
` e?: React.ChangeEvent` - получаейтся всегда возвращать e?

2020-12-10 08:39 UTC, gizeasy commented on src/components/Pagination/Pagination.tsx
> +    changePage(page);
может тут возвращать евент?

2020-12-10 08:39 UTC, gizeasy commented on src/components/Pagination/Pagination.tsx
> +              из {totalPages}
из - давай добавим возможность переопределять сверху компонента, из - по умолчанию

2020-12-10 08:39 UTC, gizeasy commented on src/components/Pagination/Pagination.css
> +  &_size {
Модификаторы блока лучше писать до элементов.

2020-12-10 08:39 UTC, gizeasy commented on src/components/Pagination/Pagination.css
> +    }
в место 
```css
.Pagination-Item,
      .Pagination-More {
        width: var(--control-height-xs);
}
```

можно определить переменную и использовать ее в `.Pagination-Item, .Pagination-More`

2020-12-10 10:54 UTC, c1n1k approved these changes

2020-12-10 11:19 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.tsx
> +  onChange: (props: { pageNumber: number; e?: React.ChangeEvent }) => void;
убрал вообще евент из колбека

2020-12-10 11:19 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.tsx
> +    changePage(page);
убрал евент

2020-12-10 11:19 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.tsx
> +              из {totalPages}
сделал

2020-12-10 11:19 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.css
> +  &_size {
поднял вышел

2020-12-10 11:19 UTC, karpovfv-nedra commented on src/components/Pagination/Pagination.css
> +    }
сделал, спасибо

2020-12-10 11:20 UTC, karpovfv-nedra commented on src/components/Modal/__stories__/examples/ModalExample/ModalExample.css
> -
удалил отсюда и из сайдбара этот стиль, так как он распространялся на весь сторибук

2020-12-10 12:17 UTC, gizeasy approved these changes

2020-12-10 12:19 UTC, merged