docs(owToGo): added new section
gazprom-neft/consta-uikit pull request #655
Opened 2020-12-03 15:10 UTC by gizeasy

issue -  #626

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-03 15:13 UTC, arhayka commented on docs/common/about.mdx
> +<Meta title="Документация|О дизайн системе" id="common-about" parameters={{ order: 100 }} />
О дизайн-системе

2020-12-03 15:14 UTC, arhayka commented on docs/common/developers/commits-style.mdx
> +  title="Документация|Разрабодчикам/Правила оформления коммитов"
РазрабоДчикам —>Разработчикам

2020-12-03 15:15 UTC, arhayka commented on src/components/Attach/__stories__/Attach.stories.tsx
> +  title: 'Компонеты|/Attach',
Компоненты (н пропущено)

2020-12-04 08:27 UTC, fooontic approved these changes

2020-12-04 08:55 UTC, arhayka commented on docs/common/developers/file-structure/file-structure-components.mdx
> +  title="Документация|Разработчикам/Файловая Структура/Компонент"
Файловая структура (во втором слове не нужна заглавная буква)

2020-12-04 08:55 UTC, arhayka commented on docs/common/developers/file-structure/file-structure.mdx
> +  title="Документация|Разработчикам/Файловая Структура/Общее"
Файловая структура (во втором слове не нужна заглавная буква)

2020-12-04 09:35 UTC, arhayka approved these changes

2020-12-04 09:40 UTC, arhayka requested changes

2020-12-04 09:40 UTC, arhayka commented on docs/common/howToGo.mdx
> +- 80% — компоненты из дизайн-системы
вот тут в конце строчки запятую добавь, плиз

2020-12-04 09:40 UTC, arhayka commented on docs/common/howToGo.mdx
> +Если хотите самостоятельно добавить новый компонент, напишите, — как вы собираетесь его реализовывать — в общих чертах (какой API будет у компонента, спорные технические моменты и т. д.).
Тут слишком много тире, видимо, побилось форматирование. Давай уберем:

Если хотите самостоятельно добавить новый компонент, напишите, как вы собираетесь его реализовывать, в общих чертах (какой API будет у компонента, спорные технические моменты и т. д.).

2020-12-04 09:59 UTC, arhayka approved these changes

2020-12-04 10:00 UTC, merged