added Stepper component
gazprom-neft/consta-uikit pull request #676
Opened 2020-12-15 13:30 UTC by karpovfv-nedra

## Описание изменений

добавлен компонент stepper

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-15 16:05 UTC, c1n1k commented on src/components/Stepper/Stepper.tsx
> +  e: React.MouseEvent;
почему только событие мыши?

2020-12-16 05:50 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.tsx
> +  e: React.MouseEvent;
тут подразумеваются только клики по кнопкам, поэтому маус евент

2020-12-16 06:53 UTC, c1n1k approved these changes

2020-12-16 07:25 UTC, gizeasy requested changes

2020-12-16 07:25 UTC, gizeasy commented on src/components/Stepper/Step/Step.css
> +  font-size: var(--step-font-size);
Переменная используется только в компоненте Step, давай модификатор size перенесем в Step. Так будет понятнее откуда `--step-font-size` взялся.

2020-12-16 07:25 UTC, gizeasy commented on src/components/Stepper/Step/Step.tsx
> +export const Step = React.forwardRef<HTMLButtonElement, Props>((props, ref) => {
Название дочернего компонента должно начинаться с префикса родителя и быть блоком
https://consta-uikit.vercel.app/?path=/docs/%D1%81ommon-file-structure-components--page

т.е. StepperStep
если в другом компоненте у меня будет ребенок Step, стили будут афектится.

2020-12-16 07:25 UTC, gizeasy commented on src/components/Stepper/Stepper.css
> +  &_size {
Перенести в Step

2020-12-16 07:25 UTC, gizeasy commented on src/components/Stepper/Stepper.tsx
> +  const iconSize = getSizeByMap(sizeMap, size);
если модификатор size перенесете в Step, то и расчет iconSize тоже перенесите.

2020-12-16 07:25 UTC, gizeasy commented on src/components/Stepper/Stepper.tsx
> +    gridTemplateColumns: `repeat(${items.length}, minmax(min-content, 1fr))`,
давай сделаем через variable css? с пометкой в css что переменная задается в JS

2020-12-16 10:36 UTC, karpovfv-nedra commented on src/components/Stepper/Step/Step.css
> +  font-size: var(--step-font-size);
избавился от переменной `--step-font-size`, перенёс модификатор  в StepperStep, и в нём задаю размер шрифта

2020-12-16 10:36 UTC, karpovfv-nedra commented on src/components/Stepper/Step/Step.tsx
> +export const Step = React.forwardRef<HTMLButtonElement, Props>((props, ref) => {
спасибо, я понял, переименовал

2020-12-16 10:36 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.css
> +  &_size {
сделал

2020-12-16 10:36 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.tsx
> +  const iconSize = getSizeByMap(sizeMap, size);
сделал

2020-12-16 10:36 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.tsx
> +    gridTemplateColumns: `repeat(${items.length}, minmax(min-content, 1fr))`,
сделал

2020-12-16 11:53 UTC, fooontic requested changes

2020-12-16 11:53 UTC, fooontic commented on src/components/Stepper/Stepper.css
> +.Stepper {
В Фигме компонент называется Steps. Давайте его так и назовём.

2020-12-16 11:53 UTC, fooontic commented on src/components/Stepper/__stories__/Stepper.stories.tsx
> +            <Button onClick={handleNext} label="Дальше" iconRight={IconForward} />
Сейчас сторя с самим компонентом выглядит очень сложно. Непонятно, о каком компоненте собственно речь. Надо бы избавиться от всего лишнего и оставить только самое нужное. В идеале вообще только сами Степс, если всё же нужны кнопки, то оставить только кнопки Назад, Дальше и т.д.  Как минимум избавиться от подложки и сложного контента (можно только текстовый оставить). 

А вот уже в документацию можно положить текущий пример, как показательный образец.

2020-12-16 13:38 UTC, Miocene commented on src/components/Stepper/Stepper.css
> +  display: grid;
Гид лучше всё же использовать для крупных сущностей.
Тут лучше флексы

2020-12-16 13:38 UTC, Miocene commented on src/components/Stepper/Stepper.css
> +  grid-template-columns: var(--stepper-grid-columns);
Шаги не должны быть обязательно одного размера. Сейчас, если один шаг чуть длиньше остальных, то он переносится на вторую строку. Хотя сам шаг мог бы растянуться

2020-12-16 13:38 UTC, Miocene commented on src/components/Stepper/StepperStep/StepperStep.css
> +.StepperStep {
За счет того, что семантически это кнопка, текст выравнивается по центру, когда строк становится больше одной.
Надо задать выравнивание по левому краю

2020-12-16 13:38 UTC, Miocene commented on src/components/Stepper/StepperStep/StepperStep.css
> +  padding: var(--space-xs) 0;
Тут сверху есть отступ, а в фигмовском компоненте нету.
С одной стороны, это нехорошо. Он не оправдан никакой графической сущностью. Будет сложнее рассчитывать отступы от других элементов интерфейса.
С другой, больше область клика.

И из-за палочки снизу отступы выглядят неравными.

@fooontic что скажешь?

2020-12-16 13:38 UTC, Miocene commented on src/components/Stepper/StepperStep/StepperStep.css
> +    transition: background-color 0.2s;
Тут не хватает еще транзишна для opacity, который ниже меняется

2020-12-16 15:59 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.css
> +.Stepper {
переименовал

2020-12-16 16:00 UTC, karpovfv-nedra commented on src/components/Stepper/__stories__/Stepper.stories.tsx
> +            <Button onClick={handleNext} label="Дальше" iconRight={IconForward} />
согласен!
убрал всё лишнее из стори

2020-12-16 16:00 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.css
> +  grid-template-columns: var(--stepper-grid-columns);
обновил

2020-12-16 16:01 UTC, karpovfv-nedra commented on src/components/Stepper/StepperStep/StepperStep.css
> +.StepperStep {
задал выравнивание по левому краю

2020-12-16 16:01 UTC, karpovfv-nedra commented on src/components/Stepper/StepperStep/StepperStep.css
> +  padding: var(--space-xs) 0;
пока оставил всё как есть, за исключением того, что палочку опустил пониже на её толщину, чтобы отступы хотя бы выглядели равными

2020-12-16 16:02 UTC, karpovfv-nedra commented on src/components/Stepper/StepperStep/StepperStep.css
> +    transition: background-color 0.2s;
спасибо! потерял где-то..
добавил

2020-12-17 07:31 UTC, gizeasy commented on src/components/Stepper/Stepper.tsx
> +    gridTemplateColumns: `repeat(${items.length}, minmax(min-content, 1fr))`,
вообще гриды убрал?

2020-12-17 07:33 UTC, karpovfv-nedra commented on src/components/Stepper/Stepper.tsx
> +    gridTemplateColumns: `repeat(${items.length}, minmax(min-content, 1fr))`,
да, и variable css соответственно тоже

2020-12-17 07:37 UTC, gizeasy approved these changes

2020-12-17 07:43 UTC, fooontic commented on src/components/Stepper/StepperStep/StepperStep.css
> +  padding: var(--space-xs) 0;
Мне кажется сейчас стало лучше. Область клика всё же важнее. В фигме поправим подстать текущему решению лучше

2020-12-17 07:44 UTC, fooontic approved these changes

2020-12-17 09:04 UTC, Miocene approved these changes

2020-12-17 09:48 UTC, merged