feat(Breadcrumbs): Добавил брэдкрамбы
gazprom-neft/consta-uikit pull request #677
Opened 2020-12-15 14:53 UTC by dmitriykorsakovnedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-15 15:39 UTC, c1n1k commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +          <a
роутер не подцепишь

2020-12-15 15:44 UTC, c1n1k commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +        <Fragment key={`${label}:${link}`}>
семантика не нужна?

2020-12-15 15:49 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +        <Fragment key={`${label}:${link}`}>
В целом можно добавить, не помешает)

2020-12-16 08:24 UTC, gizeasy commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +          <a
Кажется что вариант с онкликом, большенство устроит. 
В целом можно создать рендерпропс, куда на вход будут падать `{Icon, label, link, item, isActive, className, iconSize, size, isFirst}`, и хорошо описать придется как и зачем это все использовать.
Думаю что лучше сделать в отдельной задаче.
А еще там будет контекстное меню, и я пока не представляю как оно подружится с рендерпропс

2020-12-16 08:28 UTC, gizeasy approved these changes

2020-12-16 10:09 UTC, nedradigital commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +        <Fragment key={`${label}:${link}`}>
Сделал списком

2020-12-17 08:42 UTC, kolebayev commented
Если isButton из доки пока не стали делать, то все ок
<img width="495" alt="изображение" src="https://user-images.githubusercontent.com/24884175/102464050-efd7d380-405c-11eb-9ad4-2c06beecb97c.png">

2020-12-17 09:07 UTC, fooontic requested changes

2020-12-17 09:07 UTC, fooontic commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
Сейчас не очень очевидно работает maxCount если указать меньше 3, то он не срабатывает и показывает все, ничего не скрывая. Надо либо это как-то ограничить, либо подписать дополнительно.

2020-12-17 09:07 UTC, fooontic commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
А ещё надо логику его скрытия чутка подправить. Если `onlyIconRoot=true` то скрытие от третьго элемента, если `onlyIconRoot=false` то от второго

2020-12-17 09:25 UTC, gizeasy commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
> А ещё надо логику его скрытия чутка подправить. Если `onlyIconRoot=true` то скрытие от третьго элемента, если `onlyIconRoot=false` то от второго

кажется что это лишнее

2020-12-18 08:58 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.css
> +  padding: 0;
убрал марджины

2020-12-18 08:58 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.css
> +      font-size: var(--control-text-size-l);
сделано

2020-12-18 08:58 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                  onlyIcon: onlyIconRoot && isFirst,
сделано

2020-12-18 08:58 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.css
> +    top: 2px;
сделано

2020-12-18 11:15 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
> Сейчас не очень очевидно работает maxCount если указать меньше 3, то он не срабатывает и показывает все, ничего не скрывая. Надо либо это как-то ограничить, либо подписать дополнительно.

подписать в сторибуке в смысле и в документации?

2020-12-18 11:16 UTC, dmitriykorsakovnedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
> А ещё надо логику его скрытия чутка подправить. Если `onlyIconRoot=true` то скрытие от третьго элемента, если `onlyIconRoot=false` то от второго

maxCount тогда еще усложнится) будет работать от 4х в этом случае
Точно стоит делать?

2020-12-21 20:40 UTC, fooontic commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
если сложно, то можно забить

2020-12-21 20:42 UTC, fooontic commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
> подписать в сторибуке в смысле и в документации? 

я бы просто не добавлял это как нобу. В компоненте и доке есть и хватит. В нобах она может только больше смущатьь

2020-12-21 20:43 UTC, fooontic approved these changes

2020-12-22 08:33 UTC, gizeasy commented
Не прошли тесты, добавьте id к стори

2020-12-22 08:42 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +      {maxCount && rest.length > 1 ? (
я убрал нобу эту из стори

2020-12-22 08:42 UTC, karpovfv-nedra commented
> Не прошли тесты, добавьте id к стори

добавил айдишник

2020-12-24 11:25 UTC, merged