feat: (ContextMenu) added component
gazprom-neft/consta-uikit pull request #715
Opened 2020-12-18 12:09 UTC by gizeasy

issue - #595

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-22 09:35 UTC, fooontic requested changes

2020-12-22 09:35 UTC, fooontic commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
> +## Добавлени эелементов в пункт меню
**Добавление элементов**

2020-12-22 09:35 UTC, fooontic commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +};
У тебя вроде используется мапа для размера иконок, но сами иконки не меняются. Вопрос тогда зачем эта мапа для иконок? По идее у тебя сейчас правильно сделано, что иконки не меняются в зависимости от размера Меню. Они и должны быть всегда размера S.

2020-12-22 09:35 UTC, fooontic commented on src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.css
> +  --top-space-decrement: calc(1px - 1px);
Кажется, чтобы избежать такого _изящного_ решения, можно просто сделать. 
```
&_first {
    padding-top: 0;
  }
```

Тогда и строчку ниже можно будет переписать на что-то попроще 
```
padding: calc(var(--top-space) - var(--top-space-decrement)) 0 var(--bottom-spase) 0;
``` 
--->
```
padding: var(--top-space) 0 var(--bottom-spase) 0;
```

2020-12-22 10:40 UTC, fooontic requested changes

2020-12-22 10:40 UTC, fooontic commented on src/components/ContextMenu/__stories__/ContextMenu.stories.tsx
> +  disabled: boolean('disabled', false),
Давай disabled уберём из нобов. Он только смущать больше будет. Так как дизейблить все пункты бессмысленно, а по отдельности неправильно. Либо как вариант задизейблить один пункт и переназвать саму нобу.

2020-12-22 12:49 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +};
это мапа для стрелочки если есть под меню, она тоже всегда `S`?

2020-12-22 13:02 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.css
> +  --top-space-decrement: calc(1px - 1px);
по макету не совсем верно 

```css
&_first {
    padding-top: 0;
  }
```

это так только при размере `s`

в остальных случаях нужно отнять от --top-space, --space-xs

но заменил определение переменной на переопределение свойства `padding`

2020-12-22 13:10 UTC, dmitriykorsakovnedra commented on src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
> +      spareDirection,
Какой-то ад из свойств..
Может их хотябы сгруппировать, типа разделить на те что нужны айтему и поповеру, а может и как-нибудь еще

2020-12-22 13:33 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.tsx
> +  label: string | number;
не мешается же, но может кому и пригодиться

2020-12-22 13:48 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +  let sideArray: React.ReactNode[] = [];
тут может прийти как один элемент так и массив
и каждый(элемент массива или одиночный) нужно обернуть в Side чтобы дать отступы

2020-12-22 13:55 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +          leftSpase: sideArray.length === 0,
за ранее не известно сколько будет элементов справа и сколько с лева, по этому в JS вычесляю `leftSpase`

![image](https://user-images.githubusercontent.com/13190808/102895817-72ee9480-4476-11eb-872b-b68f4d108b87.png)

2020-12-22 13:58 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +        className={cnContextMenuItem({ size, active, disabled, withSide: true })}
не понял(

2020-12-22 14:04 UTC, gizeasy commented on src/components/ContextMenu/ContextMenu.tsx
> +  const addLevel: AddLevel<Item> = (level, items, anchorRef, activeItem) => {
имеет, каждый левел представлен как отдельный поповер, это нам дает:
рендерим только те уровни которые требуются,
каждый левел рендерится отностилено позиции предыдущего, 
если нет места для появлении левела, меню начнет раскрываться в противоположную позицию.

еще скрытие левелов идет по таймауту, думаю что просто цссом бы не обошлись, а так заюзали весь функционал поповеров, и в целом не так много пришлось своего выдумывать.

2020-12-22 14:31 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.css
> +    color: var(--color-control-typo-disable);
да косяк, исправил не поинтер-эвентами, так как нужно чтоб отработало событие, чтоб скрыть раскрывшееся под меню на уровне выше. 

```css
&_disabled {
    color: var(--color-control-typo-disable);
    cursor: default;

    &:hover {
      background: transparent;
    }
  }
```

2020-12-22 14:38 UTC, kordy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +  let sideArray: React.ReactNode[] = [];
> тут может прийти как один элемент так и массив
> и каждый(элемент массива или одиночный) нужно обернуть в Side чтобы дать отступы

ну я понял, `const sides = [].concat(side); ` всегда вернет массив

2020-12-22 14:39 UTC, dmitriykorsakovnedra commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +  let sideArray: React.ReactNode[] = [];
`const sides = [].concat(side); ` всегда вернет массив

2020-12-22 14:41 UTC, dmitriykorsakovnedra commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +          leftSpase: sideArray.length === 0,
тогда можно дать всем левый отступ, кроме первого, и всем после центрального, дать левый отступ больше.
Так не люблю логику в js, которую можно цссом обойти..

2020-12-22 14:45 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
> +      spareDirection,
сгруппировал написал комментарии

2020-12-22 14:45 UTC, dmitriykorsakovnedra commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +        className={cnContextMenuItem({ size, active, disabled, withSide: true })}
А даж заменять не надо ведь, просто можно вырезать if с 91 по 102 и визуально ничего не изменится же.
Или мы боремся за то чтобы убрать лишний див?

2020-12-22 14:46 UTC, gizeasy commented
все что пофиксил пометил смайлом 👍

2020-12-22 14:52 UTC, gizeasy commented on src/components/ContextMenu/__stories__/ContextMenu.stories.tsx
> +  disabled: boolean('disabled', false),
сделал чтоб дизейблился только один пункт и переименовал кнобу

2020-12-22 14:53 UTC, gizeasy commented
добавил тесты

2020-12-22 15:04 UTC, fooontic commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +};
да, пойдёт

2020-12-23 09:51 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +  let sideArray: React.ReactNode[] = [];
const sides = [].concat(side);  - не получилось чтото на reactNode ругался и тип never[] выводился, но идею понял и соратил код))

2020-12-23 09:52 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +          leftSpase: sideArray.length === 0,
дал всем правый отступ а у центрального он больше, спасибо, кучу лишнего убрал))

2020-12-23 09:53 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +        className={cnContextMenuItem({ size, active, disabled, withSide: true })}
борьба за лишний див)) но сократить код удалось всетаки)))

2020-12-23 10:08 UTC, dmitriykorsakovnedra commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +  let sideArray: React.ReactNode[] = [];
Тайпскрипт вечно портит элегантные решения.. :(

2020-12-23 10:23 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +};
привел мапу к виду
```
s: 'xs',
m: 's',
l: 's',
```

2020-12-23 10:24 UTC, dmitriykorsakovnedra approved these changes

2020-12-24 11:36 UTC, fooontic commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +};
Давай избавимся от мапы всё же. 
Все кастомные иконки (которые пользователь сам прокидывает) должны быть размера S, независимо от размера Контекстного меню. А иконка стрелочки для сабменю пускай будет всегда размера XS, также независимо от размера Контекстного меню.

2020-12-24 11:38 UTC, fooontic requested changes

2020-12-24 11:38 UTC, fooontic commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +        <IconArrowRight size={iconSize} />
`size="xs" view="ghost"`

2020-12-24 11:45 UTC, gizeasy commented on src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
> +};
готово

2020-12-24 12:03 UTC, fooontic approved these changes

2020-12-24 14:50 UTC, c1n1k approved these changes

2020-12-24 19:49 UTC, merged