Textfield/add missing forms
gazprom-neft/consta-uikit pull request #724
Opened 2020-12-21 20:36 UTC by fooontic

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-12-22 08:15 UTC, gizeasy requested changes

2020-12-22 08:15 UTC, gizeasy commented on src/components/TextField/TextField.css
>      &_clearClear {
Думаю что надо переименовать `_clearClear` на `_clear`, так как все остальные называются в одно слово если с двух сторон одинаково.

2020-12-22 13:27 UTC, dmitriykorsakovnedra approved these changes

2021-01-13 08:17 UTC, fooontic commented on src/components/TextField/TextField.css
>      &_clearClear {
Не уверен. Все остальные самостоятельный сами по себе, а этот скорее для связки нужен только. Сам по себе он не очень нужен. Название в таком случае является своего рода маркером

2021-01-13 08:23 UTC, gizeasy approved these changes

2021-01-13 08:24 UTC, merged