feat(EventInterceptor): added EventInterceptor context
gazprom-neft/consta-uikit pull request #739
Opened 2020-12-30 14:12 UTC by karpovfv-nedra

## Описание изменений

Реализован контекст для подключения компонентов для использования СПА. Подключен компонент Button к этому контексту.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-11 08:58 UTC, dmitriykorsakovnedra commented on src/EventInterceptor/EventInterceptor.tsx
> +  { children, handler }: { children: React.ReactNode; handler: any },
handler: any :(

2021-01-11 09:08 UTC, karpovfv-nedra commented on src/EventInterceptor/EventInterceptor.tsx
> +  { children, handler }: { children: React.ReactNode; handler: any },
убрал

2021-01-12 10:13 UTC, gizeasy requested changes

2021-01-12 10:13 UTC, gizeasy commented on src/EventInterceptor/EventInterceptor.tsx
> +const EventInterceptorContext = React.createContext(({}: EventInterceptorProps) => {});
сейчас в контексте всегда лежит функция, может по умолчанию
```ts
const EventInterceptorContext = React.createContext<
  (({}: EventInterceptorProps) => void) | undefined
>(undefined);
```

тем самым сможем проверять в хуке есть ли функция в контексте и уже после этого переопределять пропсы компонента, или просто проксировать без переопределения

2021-01-12 11:02 UTC, gizeasy commented
еще думаю держать все функции "Проксирования" отдельно от компонентов
имеем 1 общий хук который по ключу компонента даст компоненту нужный ему, выполнив который мы за проксируем все пропсы

EventInterceptorProvider
```tsx
<EventInterceptorProvider map={{
      'Button': functionForButton,
      'Component': functionForComponent,
    }} handler={console.log}>
```

в компоненте
```
const proxyProps = useEventsHandler('Button')(props);
```

2021-01-13 10:00 UTC, karpovfv-nedra commented on src/EventInterceptor/EventInterceptor.tsx
> +  const eventInterceptor = (props: EventInterceptorProps) => {
сделал

2021-01-13 10:00 UTC, karpovfv-nedra commented on src/EventInterceptor/EventInterceptor.tsx
> +const EventInterceptorProvider = (
переложил

2021-01-13 10:03 UTC, karpovfv-nedra commented
> еще думаю держать все функции "Проксирования" отдельно от компонентов
> имеем 1 общий хук который по ключу компонента даст компоненту нужный ему, выполнив который мы за проксируем все пропсы
> 
> EventInterceptorProvider
> 
> ```tsx
> <EventInterceptorProvider map={{
>       'Button': functionForButton,
>       'Component': functionForComponent,
>     }} handler={console.log}>
> ```
> 
> в компоненте
> 
> ```
> const proxyProps = useEventsHandler('Button')(props);
> ```

переделал в 1 общий хук, добавил объект `map` для вызова конкретной проксирующей функции по названию компонента. 
правда `useEventsHandler('Button')(props)` - не удалось сделать, я в этом хуке использую хук useContext, реакт не даёт возможность использовать хуки в колбеках, поэтому сейчас `useEventsHandler('Button', props)`

2021-01-13 17:37 UTC, gizeasy requested changes

2021-01-13 17:37 UTC, gizeasy commented on src/components/EventInterceptor/usePropsHandler.tsx
> +  const propsHandler = map[componentName];
давай мапу вынесим, чтоб была возмоджность свою мапу подключать, вдруг потребуются другии функции для компонентов, сейчас понятно что мы делаем для СПА. Но возможно потребуется чтото другое. 

```tsx
<EventInterceptorProvider eventHandler={console.log} map={{ Button: buttonEventHandler }}>
```
можно отдавать из `EventInterceptor` готовую мапу так сказать ту которую мы рекомендуем. если нужно что-то другое допишут своих функций, для своих компонентов или для уже существующих.

так же предлагаю условие на наличии функции в мапе и налоичия контекста вынести выше в `usePropsHandler`, это нам даст не писать условие в каждой функции хендлера, а описать прямо сдесь.

```tsx
export const usePropsHandler = (componentName: EventInterceptorPropComponent, props: Props) => {
  const context = React.useContext(EventInterceptorContext);
  if (!context) {
    return props;
  }

  const { eventHandler, map } = context;
  const propsHandler = map[componentName];

  if (!propsHandler) {
    return props;
  }

  return propsHandler(props, eventHandler);
};
```

еще думаю нужно воспользоваться дженериками для usePropsHandler чтоб он отдавал ровно  тот-же тип пропсов что в него приходит, и убрать any

2021-01-13 18:04 UTC, gizeasy requested changes

2021-01-13 18:04 UTC, gizeasy commented on src/components/Button/Button.tsx
> +  } = usePropsHandler('Button', props);
`usePropsHandler(cnButton(), props);`

2021-01-14 06:01 UTC, karpovfv-nedra commented on src/components/EventInterceptor/usePropsHandler.tsx
> +  const propsHandler = map[componentName];
мапу вынес выше, в `EventInterceptor` с возможностью переопределения, хук `usePropsHandler` поправил, дженерики добавил

2021-01-14 06:01 UTC, karpovfv-nedra commented on src/components/Button/Button.tsx
> +  } = usePropsHandler('Button', props);
поменял, спасибо)

2021-01-14 09:46 UTC, gizeasy requested changes

2021-01-14 09:46 UTC, gizeasy commented on src/components/Button/__stories__/Button.stories.tsx
> +    <EventInterceptorProvider eventHandler={console.log}>
мапу забыл прокинуть

2021-01-14 09:46 UTC, gizeasy commented on src/components/Button/__stories__/Button.stories.tsx
> +    <EventInterceptorProvider eventHandler={console.log}>
сделай экспорт мапы из компонента EventInterceptor, ну а саму мапу положи в отдельный файлик

2021-01-14 10:00 UTC, nedradigital commented on src/components/Button/__stories__/Button.stories.tsx
> +    <EventInterceptorProvider eventHandler={console.log}>
Давай оставим, чтоб не надо было мапу по умолчанию прокидывать. Пусть будет вшита.
Типа переписать можно, но не обязательно.
А экспорт да, надо сделать, чтоб оверрайдить можно было частично

2021-01-14 10:15 UTC, karpovfv-nedra commented on src/components/Button/__stories__/Button.stories.tsx
> +    <EventInterceptorProvider eventHandler={console.log}>
@gizeasy @nedradigital я мапу вынес в отдельный файлик, и по дефолту будет использоваться она. не хочется прокидывать большой объект с мапой дефолтной, может лучше чтоб она была скрыта? она скоро станет примерно такой:
```
export const map: EventInterceptorPropMap = {
  Button: buttonEventHandler,
  TextField: textFieldEventsHandler,
  Checkbox: checkboxEventsHandler,
  SnackBar: snackBarEventsHandler,
  Select: basicSelectEventsHandler,
};
```

2021-01-14 11:39 UTC, gizeasy approved these changes

2021-01-14 11:44 UTC, dmitriykorsakovnedra commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Button: buttonEventHandler as EventHandler,
Давайте либо везде cnButton(), либо везде 'Button'

2021-01-14 11:47 UTC, gizeasy commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Button: buttonEventHandler as EventHandler,
давай тогда cnButton(), жесткая завязка на имя блока

2021-01-14 11:47 UTC, karpovfv-nedra commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Button: buttonEventHandler as EventHandler,
да, у меня в следующем пре будут cnComponent везде. я в следующем это место поправлю, ок?

2021-01-14 11:48 UTC, dmitriykorsakovnedra commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Button: buttonEventHandler as EventHandler,
ок

2021-01-14 11:49 UTC, dmitriykorsakovnedra approved these changes

2021-01-14 11:55 UTC, merged