Добавлена возможность разворачивания строк в таблице
gazprom-neft/consta-uikit pull request #740
Opened 2020-12-31 12:51 UTC by CustomButtons

## Описание изменений
Добавлена возможность разворачивания строк в таблице (#691)
Это полезно для отображения иерархических данных в таблице
![image](https://user-images.githubusercontent.com/5240074/103411062-edfb2d80-4b8f-11eb-8e7e-653b012b027a.png)

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-13 08:18 UTC, gizeasy commented
изменения ломают isResizable

2021-01-13 08:18 UTC, gizeasy requested changes
изменения ломают isResizable

2021-01-20 07:55 UTC, dmitriykorsakovnedra requested changes

2021-01-20 07:55 UTC, dmitriykorsakovnedra commented on src/components/Table/Cell/TableCell.tsx
> +  } = props;
Кажется что ячейка здесь слишком много знает о том о чем не должна знать)
Может мы просто сделаем компонент кнопки для раскрытия дополнительных рядов и прокинем в ячейку как чилдрен?

2021-02-04 11:04 UTC, gizeasy commented
@CustomButtons актуальный PR? будут исправляться замечания?

2021-04-06 13:54 UTC, monolithed commented
Коллеги, нужная вещь, давайте дожмем

2021-11-29 12:40 UTC, closed without merging