Event interceptor: added textfield, checkbox, snackbar, select components
gazprom-neft/consta-uikit pull request #749
Opened 2021-01-14 14:47 UTC by karpovfv-nedra

## Описание изменений

Подключил компоненты textfield, checkbox, snackbar, select к конексту Event interceptor

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-14 14:51 UTC, karpovfv-nedra commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Select: basicSelectEventsHandler as EventHandler,
@gizeasy @nedradigital В общем, использование cnComponent() в качестве ключа не увенчалось успехом, когда импорчу сюда cn'шки, они прилетают как undefined, и использовать в качестве ключей мапы`[cnComponent()]:` не удаётся :(
Плюс ещё надо подумать, как отловить именно появление snack'ов в снакбаре, сейчас пока отлавливается и на закрытии, поэтому изменения не окончательные, жду ещё ваших комментов)

2021-01-14 16:40 UTC, gizeasy commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Select: basicSelectEventsHandler as EventHandler,
про cn - странно

про снеки, что если запоминать предыдущее состояние, сравнивать его с текущим и по ключам понимать какой удалили и какой добавили, правда изменение не отловим((( вообще думаю что достаточно передовать просто все items, не понятно зачем появление и исчезновение. Еще кнопка закрытия снека и так кидает событие что на нее нажали

2021-01-14 16:53 UTC, gizeasy commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Select: basicSelectEventsHandler as EventHandler,
также `const item = newProps.items[newProps.items.length - 1];`

не факт что добавлен будет последний item, сейчас есть возможность вставить в середину, что опять пододвигает отправку всего массива items при изменении

еще кажется что в текущей реализации, евентами компонент будет плеваться при любом рендере, а надо только при изменении props.items useEffect работает)) правда линтер ругается о том что возможно функция будет работать вне компонента

```
// отключил правило так как хук точно отработает внутри компонента
  // eslint-disable-next-line react-hooks/rules-of-hooks
  useEffect(() => {
    console.log(newProps.items);
  }, [newProps.items]);
```

2021-01-14 16:56 UTC, gizeasy commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Select: basicSelectEventsHandler as EventHandler,
чтоб не отключать правило достаточно переименовать функцию в useSnackBarEventsHandler, 
думаю надо везде переименовать чтоб было понятно что это хук и он будет работать только внутри компонента

2021-01-15 08:22 UTC, karpovfv-nedra commented on src/components/EventInterceptor/eventInterceptorMap.ts
> +  Select: basicSelectEventsHandler as EventHandler,
в снакбаре сделал так: на useEffect при изменении количества items отрабатывает хэндлер, просто в объект options засунул массив items, содержащий сообщение и статус для каждого снака)
функции-хэндлеры для компонентов переименовал в хуки

2021-01-15 10:13 UTC, gizeasy requested changes

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/basicSelectEventsHandler.tsx
> +    const [event] = onChangeArgs;
в onChange падает не евент а item, его тип мы не знаем, 
чтобы вытащить с него лейбл используй `getOptionLabel`
в `value` думаю лучше ложить целиком item

и еще, `value` можно поменять не только через onChange компонента, а просто прокинуть в свойство `value` его значение. Думаю лучше не завязываться на onChange, а завязаться на изменение `value`. Ну или сделать и так и так.

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/checkboxEventsHandler.tsx
> +        label: (eventArgs.target.offsetParent! as HTMLLabelElement).innerText,
label можно брать из пропсов

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/checkboxEventsHandler.tsx
> +        checked: eventArgs.target.checked,
checked тоже можно брать из пропсов

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/checkboxEventsHandler.tsx
> +  newProps.onChange = (...onChangeArgs) => {
тут также onChange не факт что поменяет состояние checked
думаю лучше завязаться на изменение checked у компонента

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/snackBarEventsHandler.tsx
> +      const items = newProps.items.map((item) => ({
а почему бы просто не отдавать items?

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/textFieldEventsHandler.tsx
> +        placeholder: target.placeholder,
почему не воспользовался пропсами?

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/textFieldEventsHandler.tsx
> +        value: target.value,
почему не воспользовался пропсами?

2021-01-15 10:13 UTC, gizeasy commented on src/components/EventInterceptor/propsHandlers/textFieldEventsHandler.tsx
> +  newProps.onChange = (...onChangeArgs) => {
опять же не факт что onChange вызовет изменение value

2021-01-15 13:44 UTC, karpovfv-nedra commented on src/EventInterceptor/EventInterceptor.tsx
> +const EventInterceptorProvider = ({ children }: { children: React.ReactNode }, { ...rest }) => {
удалил всё лишнее, спасибо! файлы с хуками переименовал, с мапой пока ничего не делал

2021-01-15 13:45 UTC, karpovfv-nedra commented on src/components/EventInterceptor/propsHandlers/basicSelectEventsHandler.tsx
> +    const [event] = onChangeArgs;
ага, я понял. не стал завязываться на onChange, завязался на пропсы и изменение value

2021-01-15 13:45 UTC, karpovfv-nedra commented on src/components/EventInterceptor/propsHandlers/checkboxEventsHandler.tsx
> +        label: (eventArgs.target.offsetParent! as HTMLLabelElement).innerText,
взял из пропсов

2021-01-15 13:46 UTC, karpovfv-nedra commented on src/components/EventInterceptor/propsHandlers/snackBarEventsHandler.tsx
> +      const items = newProps.items.map((item) => ({
отдал просто items, без преобразований

2021-01-15 13:46 UTC, karpovfv-nedra commented on src/components/EventInterceptor/propsHandlers/textFieldEventsHandler.tsx
> +        placeholder: target.placeholder,
взял из пропсов

2021-01-15 13:46 UTC, karpovfv-nedra commented on src/components/EventInterceptor/propsHandlers/textFieldEventsHandler.tsx
> +        value: target.value,
взял из пропсов

2021-01-15 13:46 UTC, karpovfv-nedra commented on src/components/EventInterceptor/propsHandlers/textFieldEventsHandler.tsx
> +  newProps.onChange = (...onChangeArgs) => {
привязался на изменение value

2021-01-18 10:26 UTC, dmitriykorsakovnedra commented on src/EventInterceptor/EventInterceptor.tsx
> +const EventInterceptorProvider = ({ children }: { children: React.ReactNode }, { ...rest }) => {
> в файле src/components/EventInterceptor/EventInterceptor.tsx
> думаю все-таки не подставлять мапу по дефолту иначе она все равно попадает в бандл, надо протестировать если просто будем реэкспортить из файла, попадет ли в бандл мапа если не использолвать контекст, чейчас она точно попадает так-как импортиться usePropsHandler в котором импортится EventInterceptorContext

Мне очень не нравится что мапу нужно будет импортить и прокидывать в проектах, ведь по сути она будет без изменений в 90% случаев.

Давайте может тогда еще одну надстройку сделаем может? типа DefaultEventProvider, в котором будет мапа прокидываться?

2021-01-19 07:46 UTC, gizeasy commented on src/EventInterceptor/EventInterceptor.tsx
> +const EventInterceptorProvider = ({ children }: { children: React.ReactNode }, { ...rest }) => {
кажется что DefaultEventProvider это лишнее, а 1 раз на проекте добавить мапу не сложно, плюс человек сразу понимает что он может все что угодно туда кинуть.

2021-01-19 08:17 UTC, karpovfv-nedra commented on src/EventInterceptor/EventInterceptor.tsx
> +const EventInterceptorProvider = ({ children }: { children: React.ReactNode }, { ...rest }) => {
убрал из `src/components/EventInterceptor/EventInterceptor.tsx` мапу дефолтную. сейчас она просто экспортиться из файлика. сейчас при оборачивании в `< EventInterceptorProvider >` необходимо будет указывать не только `eventHandler`, но и `map`. а саму мапу мы импортим из файлика как раз

2021-01-19 09:35 UTC, gizeasy commented on src/components/Button/__stories__/Button.stories.tsx
> +import { eventInterceptorMap } from '../../EventInterceptor/eventInterceptorMap';
Клева что вынес, но в данном случае, когда соберется пакет придется импортить его по пути 
`import { eventInterceptorMap } from '@consta/uikit/__internal__/src/components***` что не хорошо
я уже где-то писал об этом:
нужно проверить теорию
если  сделать `export * from './eventInterceptorMap';` в файле с провайдером
собрать пакет, линкануть на какой-ни-буть тестовый проект, подключить кнопку к проекту без провайдера и собрать проект, и убедиться что код из мапы не попал в сборку проекта

сможешь проверить?

2021-01-19 10:23 UTC, karpovfv-nedra commented on src/components/Button/__stories__/Button.stories.tsx
> +import { eventInterceptorMap } from '../../EventInterceptor/eventInterceptorMap';
да, проверено, если сделать такой реэкспорт, то в бандл мапа не попадает) блин, круто!

2021-01-19 11:25 UTC, dmitriykorsakovnedra approved these changes

2021-01-19 18:00 UTC, gizeasy approved these changes

2021-01-19 18:01 UTC, merged