docs(breadcrumbs): add docs for Breadcrumbs
gazprom-neft/consta-uikit pull request #764
Opened 2021-01-21 07:27 UTC by arhayka

Добавила документацию для хлебных крошек. 
Почему-то в примере с размером не работают размеры xs и s. Посмотрите, плиз, что я делаю не так :)

2021-01-21 08:26 UTC, kolebayev commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +Всё это можно описать в объекте `pages`. Он может выглядеть примерно так:
Здесь не `в объекте`, а `в массиве`

2021-01-21 08:27 UTC, kolebayev commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +Всё это можно описать в объекте `pages`. Он может выглядеть примерно так:
Ну и далее все с `pages`

2021-01-23 12:13 UTC, arhayka commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +Всё это можно описать в объекте `pages`. Он может выглядеть примерно так:
ой, да, спасибо)

2021-01-27 09:50 UTC, gizeasy approved these changes

2021-01-29 12:25 UTC, fooontic requested changes

2021-01-29 12:25 UTC, fooontic commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +Это хлебные крошки, нужны, чтобы показать путь к текущей странице.
Что-то меня смущает это предложение. Его либо на два нужно разделить либо как-то переписать. Пытался прочитать по разному, но никак оно у меня в голове складно не звучит.

2021-01-29 12:25 UTC, fooontic commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +<BreadcrumbsExampleSize />
Почему-то в самой доке размеры не срабатывают. Первые 3 практически одного размера все. @gizeasy @azhadanov сможете помочь Ане?

2021-02-02 11:42 UTC, arhayka commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +Всё это можно описать в объекте `pages`. Он может выглядеть примерно так:
поправила

2021-02-02 11:42 UTC, arhayka commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
> +Это хлебные крошки, нужны, чтобы показать путь к текущей странице.
поправила

2021-02-05 10:52 UTC, fooontic approved these changes

2021-02-08 10:14 UTC, merged