fix(Breadcrumbs): fixed indents and font color
gazprom-neft/consta-uikit pull request #784
Opened 2021-01-28 12:46 UTC by azhadanov

## Описание изменений

Поправлен цвет активного элемента, отступы для всех размеров компонента.
Дополнительно исправлены адреса ссылок в стори на соответствующие лейблу.

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-28 14:17 UTC, gizeasy requested changes

2021-01-28 14:17 UTC, gizeasy commented on src/components/Breadcrumbs/Breadcrumbs.css
> +        margin: 0 var(--space-s);
думаю что лучше задать переменную в компоненте ее применить
в элементе Delimiter: {
     margin: 0 var(--custom-var)
}

а саму переменную менять в модиaикаторе size

2021-01-29 11:05 UTC, gizeasy approved these changes

2021-01-29 12:12 UTC, fooontic approved these changes

2021-01-29 12:24 UTC, merged