fix(Badge): fixed height
gazprom-neft/consta-uikit pull request #785
Opened 2021-01-28 14:07 UTC by azhadanov

issue -  #711

## Описание изменений

Высота теперь берется из переменных темы на контролы, а не задается в компоненте в пикселях.

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-28 14:52 UTC, gizeasy approved these changes

2021-01-29 12:21 UTC, fooontic requested changes

2021-01-29 12:21 UTC, fooontic commented on src/components/Badge/Badge.css
> +      --badge-size: calc(var(--control-box-size-l) * 1.2);
Давай в этой размере заменим на --control-height-xs

2021-01-29 12:21 UTC, fooontic commented on src/components/Badge/Badge.css
> +      --badge-size: calc(var(--control-box-size-l) * 1.6);
А тут заменим на --control-height-s

2021-01-29 12:30 UTC, azhadanov commented on src/components/Badge/Badge.css
> +      --badge-size: calc(var(--control-box-size-l) * 1.2);
Заменил

2021-01-29 12:31 UTC, azhadanov commented on src/components/Badge/Badge.css
> +      --badge-size: calc(var(--control-box-size-l) * 1.6);
Тоже заменил, просто думал использовать переменные одного типа

2021-02-02 08:38 UTC, merged