fix(Checkbox): fixed centering and colors for intermediate
gazprom-neft/consta-uikit pull request #786
Opened 2021-01-28 14:40 UTC by azhadanov

issue -  #771

## Описание изменений

Исправлено центрирование и цвета для ghost при intermediate

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-28 14:56 UTC, gizeasy approved these changes

2021-01-29 12:05 UTC, fooontic requested changes

2021-01-29 12:05 UTC, fooontic commented on src/components/Checkbox/Checkbox.css
> +          left: 3px;
Я, кстати, хотел переписать вот эти значения на относительные, например на em. Чтобы можно было бы модифицировать для разных тем. Например в лэндосе я не мог нигде юзать радио и чекбоксы из-за этого. Отдельное ишшью на это завести, @gizeasy как думаешь?

2021-01-29 12:26 UTC, gizeasy commented on src/components/Checkbox/Checkbox.css
> +          left: 3px;
давай тогда в рамках этой задачи пофиксим

2021-01-29 12:37 UTC, azhadanov commented on src/components/Checkbox/Checkbox.css
> +          left: 3px;
Заменил на em для обоих размеров

2021-02-02 08:36 UTC, gizeasy commented on src/components/Checkbox/Checkbox.css
> +          left: 3px;
@fooontic проверь

2021-02-02 11:54 UTC, nedradigital commented on src/components/Checkbox/Checkbox.css
> +          left: 0.15em;
Тут по идее надо с тригонометрией запариться а не подбирать значения)

У нас хватает данных чтоб вычислить размеры большого прямоугольника, тока синусов с css нет, у нас есть какой-то предобработчик?

![IMG_20210202_145048](https://user-images.githubusercontent.com/69645013/106596722-77729680-6566-11eb-9d83-e21a186d8178.jpg)

2021-02-05 10:56 UTC, fooontic approved these changes

2021-02-10 17:11 UTC, merged