docs(withTooltip): edit docs and examples
gazprom-neft/consta-uikit pull request #788
Opened 2021-01-28 21:28 UTC by arhayka

## Описание изменений

Поправила написанную доку, добавила пару разделов и примеры, сделала меню, всё перелиноковала.

## Чек-лист

- [ /] PR: направлен в правильную ветку
- [/ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ /] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ /] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-29 11:15 UTC, gizeasy requested changes

2021-01-29 11:15 UTC, gizeasy commented on src/hocs/withTooltip/__stories__/withTooltip.mdx
> +который умеет обрабатывать события из списка ниже так, как здесь описано:
списка ниже - остально можно опустить.

2021-01-29 11:15 UTC, gizeasy commented on src/hocs/withTooltip/__stories__/withTooltip.mdx
> +- в компоненте, который возвращает HOC (они главнее).
кажется что не совсем понятно, что главнее
может ниже подписать:
`свойства заданные в компоненте будут главнее`

2021-01-29 12:01 UTC, fooontic approved these changes

2021-02-02 12:44 UTC, gizeasy approved these changes

2021-02-02 12:45 UTC, merged