docs(ContextMenu): edit docs
gazprom-neft/consta-uikit pull request #801
Opened 2021-01-29 11:16 UTC by arhayka

## Описание изменений

Поправила описание, добавила примеров (не везде, но их там и так много).
В конце нет примера использования, помогите, плиз, с ним, если считаете, что нужен.

## Чек-лист

- [ /] PR: направлен в правильную ветку
- [ /] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-01-29 11:57 UTC, fooontic requested changes

2021-01-29 11:57 UTC, fooontic commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
> +Контекстное меню можно добавить на страницу — в любую область, в которой нужна дополнительная навигация.
Может добавим какие-то рекомендации типа таких, как в фигме:
«Чаще всего контекстное меню вызывается правой кнопкой мыши, при нажатии на меню «кебаб» или другие подходящие по смыслу элементы или кнопки.»

2021-01-29 12:11 UTC, gizeasy requested changes

2021-01-29 12:11 UTC, gizeasy commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
> +### Direction
Добавь эти типы в типы над таблицей после
`type Item = unknown;`

2021-01-29 12:11 UTC, gizeasy commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
> +  name: 'Пункт 1-3-1',
поправь форматирование. как в объектах выше

2021-01-29 12:11 UTC, gizeasy commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
> +- [Пример использования](#пример)
Примера нет, но кажется что примеров на странице достаточно. и можно удалить пункт

2021-02-02 12:41 UTC, gizeasy approved these changes

2021-02-05 11:02 UTC, fooontic approved these changes

2021-02-08 10:03 UTC, merged