feat(Table): add custom filters
gazprom-neft/consta-uikit pull request #804
Opened 2021-02-01 10:47 UTC by vasilevx

Добавлены кастомные фильтры

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-02 08:32 UTC, gizeasy requested changes

2021-02-02 08:32 UTC, gizeasy commented on src/components/Table/__stories__/Table.stories.tsx
> +          filterComponent: TableCustomFilterCheckboxGroup,
Сейчас не нравиться что filterComponent имеет пропсы с Any. Надо постараться убрать any использовать либо дженерики либо unknown

2021-02-02 08:32 UTC, gizeasy commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
onCustomFiltersUpdate вызовиться вместе с перерендером таблицы после фильтрации?
Я конечно за то чтобы пользователь сам фильтровал и вызывал рендер. 
Сейчас я не совсем понимаю что если фильрация произайдет на бэке?

2021-02-02 12:44 UTC, vasilevx commented on src/components/Table/CustomFilterCheckboxGroup/TableCustomFilterCheckboxGroup.tsx
> +      title="Фильтровать по выбранным из списка"
Добавил проп title

2021-02-02 12:49 UTC, vasilevx commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
onCustomFiltersUpdate, по аналогии с onFiltersUpdated, вызывается при ререндере. 
Чтобы фильтрацией пользователем имеется ввиду передача в таблицу нового массива rows? В кастомном фильтре, передаваемом в filterComponent, в обработчике нажатия на кнопку подтверждения можно значения фильтра передавать на бэк, оттуда получать новые строки и их передавать в таблицу

2021-02-03 09:23 UTC, gizeasy commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
@vasilevx А при передачи данных в таблицу они также будут фильроваться еще и в компоненте?

2021-02-03 09:29 UTC, gizeasy commented
@fooontic сейчас если пользоваться старой фильтрацией то ее активность мы видим в баре бод шапкой
а фильтрацию новых фильтров мы видим в подсвеченой иконке фильтра
![image](https://user-images.githubusercontent.com/13190808/106726385-5f108380-661b-11eb-91e7-d0bdbb68c6c9.png)

2021-02-03 10:29 UTC, vasilevx commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
@gizeasy сейчас получается, что да. В теории можно поправить проп кастомных фильтров так, чтобы можно было не передавать функцию filterer. Тогда фильтрация внутри будет происходить, но только по "старым" фильтрам, которые остались для совместимости. 
Правильно ли я тебя понял - ты хочешь, чтобы фильтрация всегда происходила вне таблицы, т.е. снаружи поступал новый массив rows?

2021-02-03 10:48 UTC, gizeasy commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
Да, именно так, при работе с билиотекой я понял что нужно стараться вынеосить всю логику из компонента по максимуму, если мы специально не хотим ограничивать использование, и придоставлять только визуальную часть и ни как не навязывать бизнес логику. В идеале по фильтрам хочется чтобы отрабатывал только колбек, в котором текущее выбранное, и в нутри не городить свой стейт, чтоб люди использовали свой стейт в проекте, ведь он всегда у них есть и они сами знают как им удобнее.

2021-02-03 10:59 UTC, dmitriykorsakovnedra commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
Получается что мы ради эдж кейса, когда нужна кастомная фильтрация, заставляем всех юзеров реализовывать фильтры самому. По мне так это не очень хорошо. 
Я думаю надо оставить возможность коробочной фильтрации, так как она наиболее часто использоваться будет.

Может сделать возможность параметром заблочить фильтрацию внутри компонента просто?

2021-02-03 11:19 UTC, gizeasy commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
возможно, тогда надо какойто filterMode придумать, типа фитрация в нутри и фильрация вне, и если вне - то просто вызывать колбеки

2021-02-03 11:27 UTC, dmitriykorsakovnedra commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
Предлагаю просто флажок externalFiltration добавить в CustomFilters, с которым будет пропускаться этап фильтрации в таблице

2021-02-04 08:25 UTC, vasilevx commented
@gizeasy @dmitriykorsakovnedra поправил вид фильтров по обновленным макетам и в каждый фильтр добавил флаг externalFiltration, по-умолчанию он false. В сторисах сделал пример, когда фильтрация по одному параметру происходит "на сервере", а по остальным - внутри таблицы.

2021-02-08 12:06 UTC, gizeasy commented
от дизайнеров пришла просьба убрать старый фильр(визуально)
и вместо старого испотзовать новый список
![image](https://user-images.githubusercontent.com/13190808/107217446-3a534c00-6a1f-11eb-9aea-58e488ae1ebe.png)

2021-02-08 12:30 UTC, dmitriykorsakovnedra commented
> от дизайнеров пришла просьба убрать старый фильр(визуально)
> и вместо старого испотзовать новый список
> ![image](https://user-images.githubusercontent.com/13190808/107217446-3a534c00-6a1f-11eb-9aea-58e488ae1ebe.png)

В этом случае нам нужно будет дублировать функционал, так как формат старых фильтров совсем другой.
+ Это будет подстегивать юзеров использовать старые фильтры и придется их все время поддерживать тогда.
Точно стоит того?

2021-02-12 10:37 UTC, gizeasy approved these changes

2021-02-12 15:06 UTC, al-fyodorov commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
Странное решение дублировать логику старых фильтров с добавлением возможности отображения кастомных компонентов, кроме того флаг больше напоминает костыль из-за не охоты описать правильный тип, лучше сделать как предлагалось выше через необязательный filterer, так как пользователю который фильтрует все на сервере не стоит даже пытаться заполнять это поле оно для него максимально бесполезно, а примеров где, вот сейчас фильтруем на сервере, но потом минут через десять фильтрация перескакивает на клиент вроде и нет.

По поводу поддержки старого решения, так бывает что есть обратно не совместимые фичи, можно было расширить API базовой фильтрации до нужного уровня, и предоставить старым пользователям метод обертку для преобразования старых фильтров к новому API и потом постепенно выпилить и его как большиство перейдет на новую версию.

Если появятся еще какие-нибудь более кастомные фильтры получите пропс вида CustomCustomFilters, кажется такого надо избегать. Кроме того предоставляя пользователю сразу две возможности для фильтрации можно его запутать или не учесть какие-нибудь краевые кейсы которые будут вызывать больше ошибок чем работы компонента.

Конкретно против текущего решения, и склоняюсь за то чтобы оставить только одно API для фильтрации предоставив пользователю старых фильтров преобразовать их к новым или выпустить сразу версию обратно несовместимую. Это позволит сократить количество кода в таблице не усложняя ее. Если большинству кажется что текущий костыль с двумя фильтрациями нормальное решение, то можно сливать ветку дальше по флоу.

2021-02-15 11:33 UTC, gizeasy commented
поправте конфликты

2021-02-15 14:39 UTC, dmitriykorsakovnedra commented on src/components/Table/Table.tsx
> +    onCustomFiltersUpdate,
Валидно, давайте попробуем оставить только новое апи и привести старый формат к новому для поддержки действующих проектов

2021-03-16 14:45 UTC, karpovfv-nedra commented
Всем привет!
Обновил данный PR: поддержка фильтрации осталась, расширил старое API для подключения кастомных фильтров. Обновление не ломает существующую фильтрацию.
Посмотреть результат можно тут: https://consta-uikit-pavwno60x-consta.vercel.app/?path=/story/components-table--with-custom-filters - здесь в одной колонке для типа оставил старый фильтр, а для месторождения, года открытия и полных запасов применил предустановленные компоненты фильтрации.

@gizeasy @al-fyodorov посмотрите плиз

2021-03-19 11:32 UTC, al-fyodorov requested changes

2021-03-19 11:32 UTC, al-fyodorov commented on src/components/Table/Header/TableHeader.tsx
> +      handleTooltipSave(column.accessor, [filterId] as FieldSelectedValues, filterValue);
Кажется тут приведение типа вызвано тем что происходит неправильная проверка наличия `id` у фильтра, но если `id` нет, то значит фильтр создан неправильно и он не применится, и стоит ли такой фильтр выводить?

2021-03-19 11:32 UTC, al-fyodorov commented on src/components/Table/filtering.ts
> +    if (currentFieldFilters.selected?.length) {
```suggestion
    if (currentFieldFilters.selected && currentFieldFilters.selected.length > 0) {
```

И тогда ниже в условии не надо будет перебивать TypeScript указанием, что selected уже существует.

2021-03-19 11:32 UTC, al-fyodorov commented on src/components/Table/filtering.ts
> +    return currentFieldFilters.selected?.length ? [...acc, ...orderedFilters] : acc;
```suggestion
     return orderedFilters.length > 0 ? [...acc, ...orderedFilters] : acc;
```

2021-03-19 11:32 UTC, al-fyodorov commented on src/components/Table/filtering.ts
> +      if (columnFilters && columnFilters.selected!.length) {
В идеале от этого участка кода с кучей `for` надо избавляться, даже если не в текущем PR, то надо завести задачу на доработку.

2021-03-19 11:32 UTC, al-fyodorov commented on src/components/Table/filtering.ts
> +        (selectedFilters[filterToDelete.field] || []).selected!.filter((f) => f !== filter),
Тут точно будет значением по умолчанию массив, если фильтров по такому полю не будет? Кажется если верить типизации, то должен быть объект.

2021-03-19 11:32 UTC, al-fyodorov commented on yarn.lock
> +"@actions/core@^1.2.4":
Странно что новых зависимостей нет, но при этом `yarn.lock` довольно сильно изменился.

@gizeasy, не знаешь в чем может быть дело?

2021-03-19 11:32 UTC, al-fyodorov commented on src/components/Table/SelectedOptionsList/TableSelectedOptionsList.tsx
> +const getTagLabel = (name: string, value?: any): string => {
Хорошо бы еще создать типы для того что может лежать в `value`, с учетом того что мы подозреваем там может быть min, max, name или массив, возможно еще какие варианты.

2021-03-22 09:13 UTC, karpovfv-nedra commented on docs/common/about.mdx
>  1. Форк от библиотеки с фоллбэками.
убрал

2021-03-22 09:14 UTC, karpovfv-nedra commented on src/components/Breadcrumbs/__stories__/Breadcrumbs.mdx
>    BreadcrumbsExampleIconRoot,
убрал, но на 12 строчке тут всё равно с пробелами что-то происходит

2021-03-22 09:14 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +    };
добавил проверку, сократил количество `?` и поисков по массиву

2021-03-22 09:15 UTC, karpovfv-nedra commented on src/components/Table/NumberFilter/TableNumberFilter.tsx
> +  useEffect(() => {
попробовал useLayoutEffect, не подошёл. добавил коммент

2021-03-22 09:15 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +      handleTooltipSave(column.accessor, [filterId] as FieldSelectedValues, filterValue);
да, спасибо, поправил

2021-03-22 09:15 UTC, karpovfv-nedra commented on src/components/Table/filtering.ts
> +    if (currentFieldFilters.selected?.length) {
поправил

2021-03-22 09:16 UTC, karpovfv-nedra commented on src/components/Table/filtering.ts
> +      if (columnFilters && columnFilters.selected!.length) {
в текущем пулл реквесте не делал, времени не хватает..

2021-03-22 09:16 UTC, karpovfv-nedra commented on src/components/Table/filtering.ts
> +        (selectedFilters[filterToDelete.field] || []).selected!.filter((f) => f !== filter),
да, спасибо, проглядел. тут действительно объект

2021-03-22 09:18 UTC, karpovfv-nedra commented on yarn.lock
> +"@actions/core@^1.2.4":
yarn.lock не изменился, сам не могу понять почему это произошло в первый раз и он попал под раздачу в коммите

2021-03-22 09:18 UTC, karpovfv-nedra commented on src/components/Table/SelectedOptionsList/TableSelectedOptionsList.tsx
> +const getTagLabel = (name: string, value?: any): string => {
ага, типы возможные описал

2021-03-22 09:23 UTC, karpovfv-nedra commented on src/components/Table/filtering.ts
> +      if (columnFilters && columnFilters.selected!.length) {
создал задачу на доработку https://github.com/gazprom-neft/consta-uikit/issues/995

2021-03-22 11:49 UTC, al-fyodorov approved these changes

2021-03-22 11:49 UTC, al-fyodorov commented on src/components/Table/Header/TableHeader.tsx
> +    const FilterComponent = curFilter?.component?.name;
[note]
Опционально можно добавить проверку на текущий фильтр если его нет или у него не указан ID он все равно не применится, так что можно даже не пытаться его выводить, по усмотрению @gizeasy, можно исправить отдельно.

2021-03-24 21:55 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +    const FilterComponent = curFilter?.component?.name;
создал ишью. Позже возмемся

2021-03-24 21:56 UTC, gizeasy commented
Упали тесты по таблице, поправьте плиз и вливаю

2021-03-25 05:28 UTC, karpovfv-nedra commented
> Упали тесты по таблице, поправьте плиз и вливаю

поправил

2021-03-25 17:48 UTC, merged