feat(table): table header aligned vertically
gazprom-neft/consta-uikit pull request #809
Opened 2021-02-02 20:34 UTC by schurf-des

issue -  #808

## Описание изменений
Заголовок таблицы выровнен по нижнему краю. Был вертикально по центру

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-03 09:07 UTC, gizeasy approved these changes

2021-02-03 11:53 UTC, azhadanov approved these changes

2021-02-05 11:46 UTC, fooontic requested changes

2021-02-05 11:46 UTC, fooontic commented on src/components/Table/Cell/TableCell.tsx
> +    return 'bottom';
Я наверное тебя не так понял, но я думал ты добавил модификацию для выравнивания книзу, но не заменил старое. Замена не подойдёт, надо добавить всё же модификатор. Иначе у кого-то может в проектах поехать непредсказуемо

2021-02-08 10:29 UTC, schurf-des commented on src/components/Table/Cell/TableCell.tsx
> +    return 'bottom';
Добавил

2021-02-08 13:31 UTC, gizeasy requested changes

2021-02-08 13:31 UTC, gizeasy commented on src/components/Table/Header/TableHeader.tsx
> +export const headerVerticalAligns = ['center', 'bottom'] as const;
Ипользуй тип HeaderVerticalAlign из компонента Table

2021-02-09 09:04 UTC, fooontic approved these changes

2021-02-09 10:53 UTC, gizeasy approved these changes

2021-02-09 10:55 UTC, merged