feat(Table): add column render fn
gazprom-neft/consta-uikit pull request #824
Opened 2021-02-04 10:20 UTC by vasilevx

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-25 16:03 UTC, gizeasy requested changes

2021-02-25 16:03 UTC, gizeasy commented on src/components/Table/Cell/TableCell.tsx
> +) as <T extends TableRow>(p: Props<T> & { ref?: Ref<HTMLDivElement> }) => React.ReactElement;
можно описать не прибегая к приведением к типам

```tsx
type Props<T extends TableRow> = {
  column: TableColumn<T> & {
    isSticky?: boolean;
    isResized?: boolean;
    filterable?: boolean;
  };
  onClick?: (e: React.SyntheticEvent) => void;
  style?: React.CSSProperties;
  className?: string;
  wrapperClassName?: string;
  children: React.ReactNode;
  showVerticalShadow?: boolean;
} & (
  | {
      type: 'header';
      isSticky?: boolean;
      isResized?: boolean;
    }
  | {
      type: 'content';
      isClickable?: boolean;
      verticalAlign: VerticalAlign;
      isBorderTop?: boolean;
      isBorderLeft?: boolean;
    }
  | {
      type: 'resizer';
    }
) &
  React.RefAttributes<HTMLDivElement>;


type Component = <T extends TableRow>(props: Props<T>) => React.ReactElement | null;

export const TableCell: Component = React.forwardRef((props, ref) => {
```

реф и пропсы нормально вывядятся

2021-03-18 07:09 UTC, karpovfv-nedra commented on src/components/Table/Cell/TableCell.tsx
> +) as <T extends TableRow>(p: Props<T> & { ref?: Ref<HTMLDivElement> }) => React.ReactElement;
обновил, спасибо!
конфликты поправил

2021-04-02 07:06 UTC, al-fyodorov requested changes

2021-04-02 07:06 UTC, al-fyodorov commented on src/components/Table/__tests__/helpers.test.ts
> +    expect(getNewSorting<T>(null, 'field')).toEqual({
А почему не передаете тип напрямую в дженерик?

2021-04-02 08:23 UTC, karpovfv-nedra commented on src/components/Table/Header/TableHeader.tsx
> +    const onToggle = handleFilterTogglerClick(column.accessor!);
добавил проверку на него

2021-04-02 08:23 UTC, karpovfv-nedra commented on src/components/Table/__tests__/helpers.test.ts
> +    expect(getNewSorting<T>(null, 'field')).toEqual({
поправил вроде

2021-04-12 13:41 UTC, gizeasy approved these changes

2021-04-13 09:18 UTC, al-fyodorov requested changes

2021-04-13 09:18 UTC, al-fyodorov commented on src/components/Table/__tests__/helpers.test.ts
> +    const result = getNewSorting({ by: 'field', order: 'desc' } as SortingState<TestRow>, 'field');
А зачем приведение типов везде добавили если надо было тип указать напрямую в дженерике, чтобы не было формата:

```tsx
it('Some test', <T extends SomeType>() => { // зачем-то раньше тут был дженерик
  const result = getNewSorting<T>({ by: 'field', order: 'desc' }, 'field');
  ...
})
```

Но ведь было достаточно добавить вот так:

```tsx
it('Some test', () => {
  const result = getNewSorting<SomeType>({ by: 'field', order: 'desc' }, 'field');
  ...
})
```

Но вместо этого добавили вообще приведение типов:

```tsx
it('Some test', () => {
  const result = getNewSorting({ by: 'field', order: 'desc' } as SomeType, 'field');
  ...
})
```

Так мы можем напрямую указать с каким типом работаем? Или не можем?

2021-04-13 09:49 UTC, karpovfv-nedra commented on src/components/Table/__tests__/helpers.test.ts
> +    const result = getNewSorting({ by: 'field', order: 'desc' } as SortingState<TestRow>, 'field');
Да, можем. Указал напрямую в дженерике.
Спасибо!

2021-04-13 12:43 UTC, al-fyodorov approved these changes

2021-04-15 11:20 UTC, merged