feat(UserSelect): create UserSelect component and story/docs
gazprom-neft/consta-uikit pull request #851
Opened 2021-02-15 14:25 UTC by azhadanov

issue -  #580

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-18 13:28 UTC, gizeasy requested changes

2021-02-18 13:28 UTC, gizeasy commented on src/components/SelectComponents/types.ts
> +  getOptionUrl?(arg: ITEM): string;
лучше не использовать тогда общий тип а для UserSelect сделать свой 
с памаметрами `getUserName`, `getUserUrl`, `getUserAdditionalInfo`

2021-02-18 13:28 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +    multi,
давай свойство назовем `multiple`

2021-02-18 13:28 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  Omit<SelectContainerProps, 'value' | 'onChange'> & {
думаю лучше во всех сомпонентах селекта поправить типы 
убрать Omit<SelectContainerProps, 'value' | 'onChange'>
и  прописать те свойства которые будут нужны непосредственно в компоненте

2021-02-18 13:42 UTC, gizeasy requested changes

2021-02-18 13:42 UTC, gizeasy commented on src/components/UserSelect/__mocks__/data.mock.ts
> +    value: 'Andrey Andreev',
убрать лишние параметры

2021-02-25 08:43 UTC, gizeasy requested changes

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.css
> +      --horizontal-space: calc(var(--control-space-xs) * 0.5);
Поговори с дизанерами какую тут переменную вставить так чтоб умножать не пришлось

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.css
> +      padding-left: calc(var(--horizontal-space) * 2.6);
Поговори с дизанерами какую тут переменную вставить так чтоб умножать не пришлось

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.css
> +    --icon-size: calc(var(--graphics-size-xs) - 4px);
плохо использоват значения в пикселях, надо завяваться на перменные

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.tsx
> +          <div className={cnUserItem('AvatarCheckIcon')}>
тут кажется можно обойтись без AvatarCheckIcon, и стили чтобы спозиционировать иконку никинуть на CheckIcon

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.tsx
> +        <div className={cnUserItem('SubUserInfo')}>
Упоменание о User есть в название блока у элементов можно убрать

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  value?: ITEM[] | null;
разве всегда `value` это массив?

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  onChange?: (v: ITEM[] | null) => void;
в onChange всегда попадает массив?

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  const handlerChangeValue = (v: Items): void => {
`(v: Items)` давай не сокращать так код, писать полное название, самодокументированный код все дела

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +export type UserSelectProps<ITEM, GROUP> = Omit<CommonSelectProps<ITEM>, 'options'> & {
`CommonSelectProps` убери плиз, давай прямо в компоненте укажем все нужные пропсы, а то так запутаттся можно будет

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/__mocks__/data.mock.ts
> +        label: 'Andrey Andreev',
Сделай у всех `label разные` иначе пример ломается

2021-02-25 08:43 UTC, gizeasy commented on src/components/UserSelect/__mocks__/data.mock.ts
> +        label: 'Andrey Andreev',
Вообще надо в атуму уметь задавать признак уникальности, типа getKey(item) => string|number

и дальше использовать этот ключ
сейчас по моему там использвется label

Наверное лучше отдельное ишью завести на это

2021-02-25 08:43 UTC, gizeasy commented on src/hooks/useSelect/useSelect.tsx
> +                label: getOptionLabel(item),
тут label используется больше как ключ. остальные свойства сюда можешь гетеррами не затаскивать у нас и так есть Item весь и в момент редера мы можем взять что хотим в самом компоненте не захламляя лишним функционалом этот хук

2021-02-25 08:43 UTC, gizeasy commented on src/hooks/useSelect/useSelect.tsx
> +        .filter((option) => {
тут тоже больше все с вязанно с уникальным ключем элеента, а не с label и subLabel
возмозжно что они совпадут но пользователи буду иметь разные ID

2021-03-03 10:21 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.css
> +      --horizontal-space: calc(var(--control-space-xs) * 0.5);
@kolebayev что думаешь?

2021-03-03 15:31 UTC, gizeasy commented
Тесты упали
и пожалуйста отписывайся по замечаниям

2021-03-04 08:37 UTC, kolebayev commented on src/components/UserSelect/UserItem/UserItem.css
> +      --horizontal-space: calc(var(--control-space-xs) * 0.5);
@gizeasy @azhadanov  у UserSelect нет значения xs на модификатор size, вот [макет](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=469%3A1371)

2021-03-16 09:31 UTC, gizeasy requested changes

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserSelect.tsx
> +  disabled?: boolean;
![image](https://user-images.githubusercontent.com/13190808/111282841-7cd7fc00-864f-11eb-922f-30ef24efb72c.png)

при disabled=true появляется странная обводка и все равно имеется возможнось нажать на крестики
так же при  disabled=true и view=clear имеется возможность редактировать

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.tsx
> +export const UserItem: React.FC<UserItemProps> = (props) => {
@kolebayev 
у нас есть компонент `User` он очень похож на этот компонент с одной лишь разницой что этот компонент с иконкой под аватаркой, как думаешь стоит ли добавить возможность прокидывать иконку `statusIcon` в компонент `User`

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.css
> +  &_multi {
не совсем пониаю как _multi должно влиять на элемент списка?

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserItem/UserItem.tsx
> +export const UserItem: React.FC<UserItemProps> = (props) => {
компонент надо назвать UserSelectItem

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserValue/UserValue.css
> +  &_group {
А зачем это тут?

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserValue/UserValue.tsx
> +export const UserValue: React.FC<UserValueProps> = (props) => {
UserSelectValue

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserValue/UserValue.tsx
> +        withUser,
кажется что withUser тут не нужен, 
withCancel рулит кнопкой самого юзера, кажется вообще лучше завязать на disabled, не вижу иных случаев когда нужно скрыть кнопку

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserValue/UserValue.tsx
> +      <User
думаю возможно отказаться от лишней обертки и классы накинуть все сюда

2021-03-16 09:31 UTC, gizeasy commented on src/components/UserSelect/UserValue/UserValue.css
> +.UserValue {
какжется в этом css много лишнего, посмотри пожалуйста оставь только то что реально нужно

2021-03-16 09:31 UTC, gizeasy commented on src/hooks/useSelect/useSelect.tsx
> +        .filter((option) => {
идея в том что сейчас уникильность элементта вычисляется через `getOptionLabel` нужно сделать 
getOptionKey, и по умолчанию он равен getOptionLabel,

2021-03-17 00:22 UTC, azhadanov commented on src/components/User/User.tsx
> +        <Button
Тут не совсем понял, что нужно сделать

2021-05-19 12:43 UTC, closed without merging