docs(Theme): add doc for creating custom preset
gazprom-neft/consta-uikit pull request #856
Opened 2021-02-16 14:49 UTC by kolebayev

## Описание изменений
Добавлена дока на создание пресета, исправлены опечатки в комментах к цветовым переменным
issue #826

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-18 12:16 UTC, gizeasy commented on docs/common/developers/creatingPreset.mdx
> +src/themes/
src/themes/ -> pathToPresets/
кажется так пользователю подскажем что положить он может его где угодно, как ему удобнее

2021-02-18 12:16 UTC, gizeasy commented on docs/common/developers/creatingPreset.mdx
> +import { myNewPreset } from './themes/myPresetDefault'
pathToPresets/myPresetDefault'

2021-02-20 14:29 UTC, fooontic requested changes

2021-02-20 14:29 UTC, fooontic commented on docs/common/developers/creatingPreset.mdx
> +Здесь подключаются все начертания/насыщенности/weight шрифта. Убедитесь, что в шрифте есть насыщенность, которую вы используете.
если пишешь на русском, пиши всё на русском. weight лучше заменить на «жирности»

2021-03-03 12:31 UTC, gizeasy commented
Добавить в доку как можно закостомить нашу из github c сылкой на темы в github

2021-03-03 15:29 UTC, gizeasy approved these changes

2021-03-03 15:42 UTC, arhayka reviewed
Так, тут нет критичных ошибок, будет круто везде написать CSS вот так :) ну и пару мелочей отметила еще

2021-03-03 15:42 UTC, arhayka commented on docs/common/developers/creatingPreset.mdx
> +в вашем проекте необходимо создать директорию для нового(ых) пресетов.
не надо так, давай просто "для новых пресетов"

2021-03-03 15:42 UTC, arhayka commented on docs/common/developers/creatingPreset.mdx
> +Создание нового пресета подразумевает ручную настройку css переменных (также их принято называть _дизайн токенами_), составляющих темы.
настройку переменных CSS

2021-03-03 15:42 UTC, arhayka commented on docs/common/developers/creatingPreset.mdx
> +Первым делом необходимо определиться с базовыми переменными и записать их в css файл на цвет в папке `_color`.
CSS-файл

2021-03-03 15:42 UTC, arhayka commented on docs/common/developers/creatingPreset.mdx
> +Значения переменных внутри css-класса рассчитываются с помощью [postcss-color-function](https://github.com/postcss/postcss-color-function)
CSS-класса

2021-03-03 16:49 UTC, merged