Feat/themetoggler development
gazprom-neft/consta-uikit pull request #879
Opened 2021-02-21 02:47 UTC by azhadanov

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [x] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-25 15:11 UTC, gizeasy requested changes

2021-02-25 15:11 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  const recalcSize = () => {
сделай как тут https://github.com/gazprom-neft/consta-uikit/blob/2764678132be3dab8c2dd4cc1696215905bbb489/src/components/Tabs/Tabs.tsx#L73

через мапы както нагляднее и. лакониченее, есть еще функция чтоб размеры с мапы доставать

https://github.com/gazprom-neft/consta-uikit/blob/2764678132be3dab8c2dd4cc1696215905bbb489/src/components/Tabs/Tabs.tsx#L175

2021-02-25 15:11 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    if (themes.length === 3) {
Помоему имелось ввиду про `length > 2`

2021-02-25 15:11 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +      const Icon = getThemeIcon(themes[0]);
Лучше вытаскивать иконку не посредственно из `value` тогда кода меньше будет и меньше за чем слетить в компоненте надо будет

2021-02-25 15:11 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  value: ThemePreset;
value сделай Theme[]

2021-02-25 15:11 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  themes: Theme[];
Давай сделаем item где каждый item это не известный компоненту тип
но через гетеры мы можем забрать иконку и лейбл

 в value будет падать целиком эелемент

логику выбора лучше реализовать через `useChoiceGroup `
https://github.com/gazprom-neft/consta-uikit/blob/2764678132be3dab8c2dd4cc1696215905bbb489/src/components/Tabs/Tabs.tsx#L127

2021-02-25 15:23 UTC, MariaLakomkina commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    if (themes.length === 3) {
Да, length>2. Т. Е. Контекстное меню с темами будет появляться, если тем больше двух и до бесконечности)

2021-03-01 12:10 UTC, azhadanov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  value: ThemePreset;
@gizeasy 
Может просто Theme? Зачем в value массив?

2021-03-01 14:34 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  value: ThemePreset;
да ты прав просто ITEM

2021-03-02 14:27 UTC, gizeasy requested changes

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +              className={cnThemeToggler('ContextMenu', [contextMenuClassName])}
`contextMenuClassName` кажется что лишнее

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +            <IconOne
Тут тоже надо кнопку использовать

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +              direction="downStartLeft"
вынеси `direction`, `possibleDirections` в компонент

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getKey: getThemeLabel,
добавь `getItemKey` в компонент, будет использоваться как уникальный ключ, если его нет то уникальность будут указываться в getItemLabel

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +export const ThemeToggler: ThemeToggler = (props) => {
оберни в forwardRef

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +      const emptyFn = () => '';
вынеси за компонент

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +      {getTogglerBody()}
давай уберем `getTogglerBody` сразу рендери тут

2021-03-02 14:27 UTC, gizeasy commented on src/components/ThemeToggler/__mocks__/mock.data.ts
> +  icon: FC<IconProps>;
типы из реакт исплользуй так `React.FC`

2021-03-03 15:11 UTC, azhadanov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  getThemeLabel: ThemePropGetLabel<ITEM>;
Переименовать getThemeLabel в getItem?

2021-03-05 10:15 UTC, gizeasy commented
тесты не прошил

2021-03-05 11:25 UTC, MariaLakomkina commented
Соответствие размеров:
l:l
m:m
s:s
xs:s

Размеры иконок в контекстном меню наследуются из компонента контекстного меню.

2021-03-10 10:42 UTC, azhadanov commented
Добавил мапу для контекстного меню и поправил размер иконок

2021-03-11 12:36 UTC, gizeasy requested changes

2021-03-11 12:36 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +        // size={size}
в кнопку просто прокидывай размер туглера, они должны совпадать, а размер иконки в кнопке привяжется автоматом, можешь не переопределять `iconSize`

2021-03-11 12:36 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +  const {
помести пропсы коммпонента в самый верх

2021-03-11 12:36 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemValue: ThemePropGetValue<ITEM>;
на самом деле нам же не нужен `getItemValue`
`value` мы получаем в пропсах компонента, а далее тебе найти элемент через `getChecked`

2021-03-11 12:36 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +      .filter((theme) => getChecked(theme))
`find`

2021-03-11 13:47 UTC, azhadanov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +        // size={size}
Размер иконки не совсем корректно определяется для этого компонента, поэтому и прокидываю именно iconSize.

2021-03-17 09:39 UTC, al-fyodorov requested changes

2021-03-17 09:39 UTC, al-fyodorov commented on src/components/ThemeToggler/__mocks__/mock.data.ts
> +import { IconProps } from '../../../icons/Icon/Icon';
Файл не должен ли называться `data.mock.ts`?

2021-03-17 09:39 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +      <Button
Можно ли кнопку вынести отдельно и в зависимости от количества тем менять обработчик клика?

2021-03-17 14:16 UTC, gizeasy commented on src/components/ThemeToggler/__stories__/ThemeToggler.stories.tsx
> +// @ts-ignore
добавили в предыдущих прах, @azhadanov смержся с девом

2021-03-17 14:37 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +type Props<ITEM> = PropsWithHTMLAttributesAndRef<
Да кажется что не надо, сейчас ITEM сам выводиться, из прокинутых items, если укажем по умолчанию то придется описывать, а так в каком виде хранят темы в проекте в таком и прокинут, и сделают как удобно

2021-03-17 14:49 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
дело в том что на проекте может быть своя структура тем, к примеру 
отдельно лежат пресеты и отдельно лежит мапа по которой модно вытянуть иконку и label.
Данный подход к апи не навязывает свою структуру, и не обязывает сериализовывать  данные. Не нужно создавать новые типы сущностей, и работа ведется со своими которые есть в проекте.

Дефолтные геттеры, тоже думаю не стоит писать так как мы не угадаем ни когда какая структура будет, и они просто буду занимать место в бандле

2021-03-18 10:19 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Не совсем, подумай, в проекте который использует этот тоглер, массив с темами всегда будет состоять из трех вещей: название, пресет и иконка. И даже если передать в тоглер массив из любых элементов с ключами для получения через геттеры пресетов, названий и иконок, что мешает сдеать это до передачи массива в тоглер?

Кажется что ничего, и вся эта работа и геттеры вызываются в самом компоненте не заранее, а в момент рендера, а предварительная подготовка данных может не только на этапе рендера быть, что уже более гибкое в использовании чем текущее API, так о какой гибкости и универссальности для тоглера мы говорим? В обычном Select это поведение по умолчанию, потому что мы даже не знаем что пользователь хочет в селекте обрабатывать, а тут у тебя конкретный компонент который обрабатывает темы, который выводит кнопки и переключатели тем и ничего более.

2021-03-30 08:36 UTC, kolebayev approved these changes

2021-04-01 09:57 UTC, gizeasy approved these changes

2021-04-01 11:10 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Кажется что общего понимания нет, ладно выражусь по другому, разница в том, что ваш любой формат данных скатывается к тому что КОМПОНЕНТ с помощью getLabel и прочих приблуд заставляет пользователя генерировать данные определенного формата, но это отделено от работы пользователя тем что происходит внутри вашего компонента, но происходит так или иначе, получается навязывание структуры которую вы можете отобразить есть, но к которой доступ только через самописные геттеры есть.

Так зачем усложнять использование компонента если другого отрисовать вы не сможете, а пользователю кроме того чтобы просто прокинуть данные правильного формата, еще надо и геттеры описать, которые его любой формат приведут к вашему, с условием что формат все равно ваш и он навязывается геттерами.

2021-04-01 11:13 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Если глянуть чуть дальше, а не на то что прокинуть в props компонента можно что угодно, а смотреть на всю работу этой системы, есть всегда формат пользователя который вы заставляете так или иначе привести к тому формату с которым вы можете работь в рамках рендера, и заставляете вы его это делать вообще без возможности использования чего-то стандартного, в любом компоненте свой формат надо привести к вашему через геттеры, а это уже не свободный формат данных пользователя.

2021-04-01 11:15 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Если хочется прям совсем совсем предоставить пользователю свободу выбора, тогда маппить и рендерить что-то по массивам вы не должны, а должны предоставлять только базовые блоки из которых пользователь сам замапит списки и прочие компоненты на совершенно своем наборе данных который на 100% не будет соответсвовать вашему. Но кажется у Consta немного другая филосовия, и навязывание формата у вас все равно есть.

2021-04-01 11:17 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Так вот с учетом что так и так есть навязывание формата, зачем переусложнять компонент непонятными преобразованиями данных и их типов если сразу можно условиться принимать данные того формата с которым умеет работать ваш компонент, а пользователь даже если у него глобально хранится light или dark подсчитает options для того чтобы отразить их в списке, так как считать он этоже будет через геттеры.

2021-04-01 11:22 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Вот если раскажешь как `своя_структура_тем -> своя_структура_тем` получается без использования геттеров, а не `своя_структура_тем -> то_что_умеет_рендерить_Consta` на геттерах, то еще понятно что вы ничего не навязываете, а так увы.

2021-04-01 11:28 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Например в конструкторе для CoreBarChart можно указать какие угодно данные в группах, но для отображения этих данных надо писать не геттеры, а рендеры, где пользователь может действительно делать что угодно на своем формате, хоть вместо конкретной группы линейный график отрисовать, это гибкость и возможность системы предоставить пользователю API который имеет ограничения только на фантазии пользователя. А у вас преобразования А к Б через геттеры которые формируют тот формат данных который сможет отобразить пункты в контекстном меню, что угодно там уже не отобразишь, например превью тем как в GitHub, потому что сам API у компонента довольно бедный, а универсальность в кавычках ничего не добавляет.

2021-04-01 11:31 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Вам бы для таких утвеждениях о гибкости собрать бы статистические данные в каком проценте проектов геттеры сложнее чем:

```ts
item => item.label
```

Или что-то подобное, прежде чем утверждать за реальных пользователей насколько это удобно. Для реализации того же КДБ это было не особо удобно, так как в любом месте где достаточно было прокинуть данные надо было прокидывать и геттеры однострочные которые кроме того еще и место в памяти занимают.

2021-04-01 11:33 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Для аппрува хочу увидеть агрументированное объяснение как вот выражается вот это утверждение в рамках этого компонент:

> идея в том чтобы не навязывать свой

2021-04-05 09:37 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
к примеру, чаще всего в проекте будут использоваться только 2 темы.
В состоянии приложения будем держать `theme: light | dark`, и к примеру модуль овечающий за тему экспортит некий `setTheme<light | dark>`, useTheme<light | dark>, и themes

```
export const themes = ['light', 'dark' ] as const;
export const themeDefault = themes[0];
export type Theme = typeof tagPropMode[number];
``` 

в компоненте:

```tsx
<ThemeToogler 
  items={themes} 
  getItemLabel={item => item === 'light' ? 'светлая' : 'темная'}
  getItemIcon={item => item === 'light' ? <Icon1> :  <Icon2>}
  onChange={({ value }) => setTheme(value)}
  value={useTheme()}
>
```

в случае если items определенного формата к примеру:

```
type item = {
  label: string,
  key: string,
  icon: React.FC,
}
```

Тут либо мы в состоянии приложения храним эту структуру целиком, но кажется что лучше хранить только указатель/ключ темы, по этому в модуле с темой все остается также.
В компоненте:

```tsx
const items = themes.map(item => {
  label:  item === 'light' ? 'светлая' : 'темная',
  icon: item === 'light' ? <Icon1> :  <Icon2>,
  key: item,
})

<ThemeToogler 
  items={items} 
  onChange={({ value }) => setTheme(value.key)}
  value={useTheme()}
>
```

По факту все тоже самое, но есть трансполяция в формат компонента и при onChange обратно в формат состяния, ну и лишний цикл, но он не заметный.

Еще пример с готовым массивом тем
к примеру есть необходимость хранить тему в нужном формате, 
пользователи привязанны к компании и для каждой компании набор тем разный, по этому поле авторизации прилетает тема в таком формате

```
type Theme = {
  label: string, // человеческое название
  name: string, // название которое используется в css слассе
  url: string, // ссылка на тему
  Id: string, // id темы на бэке
}
```

в компоненте:

```tsx
<ThemeToogler 
  items={themes} 
  getItemLabel={item => item.label}
  getIteKey={item => item.id}
  getItemIcon={()=> <Icon>} // чтоб не вникать в особенности как вычленять иконку из данных
  onChange={({ value }) => setTheme(value)} 
  value={useTheme()}
>

// в setTheme прилетает value с типом Theme[] что очень хорошо так как есть все данные которые прилетели с бэка и и возможнно будет в setTheme сразу сохранить выбранную тему отправив запрос содержащий ID темы
```

в случае если компонент принимает определенный формат темы

```tsx
const items = themes.map(item => {
  label:  item.label
  icon: <Icon>
  key: item.id,
})

<ThemeToogler 
  items={items} 
  onChange={({ value }) => setTheme(themes.find(theme => value.key === theme.id))}
  value={useTheme()}
>
```

и опять сначала преобразуем в формат для компонента а результат должны вернуть в формате который примет сотояние. 

И я про то что проще работать всегда с одним типом данных не перегоняя туда обратно их.

2021-04-05 10:14 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Примеры которые ты предлагаешь не решают Ваш кейс вида `идея в том чтобы не навязывать свой`, так как повторюсь, геттеры `getItemLabel, getIteKey и getItemIcon` навязывают Ваш формат данных только своим наличием, потому что не указать их нельзя.

Вот тебе простой пример который ты описал выше, чтобы не перегонять данные по разным форматам через циклы:

```tsx
// API response
const themes = [
  {
    label: 'Светлая',
    name: 'light',
    id: '1',
  },
  {
    label: 'Тёмная',
    name: 'dark',
    id: '2',
  }
]

// Состояние приложения
type Theme = 'light' | 'dark'

const appTheme: Theme = 'light'

// Карта тем (мапится один раз в момент ответа от сервера)
const themesMap = {
  light: {
    label: 'Светлая',
    name: 'light',
  },
  dark: {
    label: 'Тёмная',
    name: 'dark',
  },
}

// Метод получения списка тем для ThemeToggler
const getThemeItems = (themesFromApi) => { ... }

// Типы ThemeToggler
type ThemeItem = {
  value: string
  label: string
  icon: string
}

type Props = {
  value: string
  items: readonly ThemeItem[]
  onChange: (value: string) => void
}

const SomeComponent = ({ themesFromAPI }) => {
  const appState = useAppState()

  return (
    <ThemeTooggler 
      items={getThemeItems(themesFromAPI)}
      value={appState.theme}
      onChange={appState.setTheme}
    >
  )
}
```

Простое и лаконичное решение, в случае изменения API надо поменять только метод `getThemeItems`, так как он отвечает за формирование списка, кроме того такое решение и тестировать проще, так как мы можем и без компонента проверить что все формируется правильным образом.

И тут очень многое зависит от того в каком формате данные будут крутиться на строно приложения которое использует Ваш UI-Kit, так как способ что Вы предлагаете не решает ничего кроме `формат А в формат Б`, а учесть что преобразования могут быть и до вашего компонента после получения ответа от сервера где преобразовать можно к чему угодно, но еще и геттеры указать которые будут делать лишние преобразование из-за вот такого использования:

```tsx
const SomeComponent = () => {
  const [appState, changeAppState] = useAppState()

  return (
    <ThemeToogler 
      items={themes} 
      getItemLabel={item => item.label}
      getIteKey={item => item.id}
      getItemIcon={()=> item.icon}
      onChange={({ value }) => changeAppState('theme', value)} 
      value={appState.theme}
    >
  )
}
```

Против вот такого использования:

```tsx
const SomeComponent = () => {
  const [appState, changeAppState] = useAppState()

  return (
    <ThemeToogler 
      items={themes}
      onChange={(value) => changeAppState('theme', value)} 
      value={appState.theme}
    >
  )
}
```

Потому что по опыту использования UI-Kit в рабочем проекте Ваши геттеры больше мешают чем что-то реально делают, формат данных приходилось преобразовывать еще до компонентов потому что такой формат был, а потом еще и геттеры указывать логическая нагрузка которых равна нулю.

Поэтому предлагаю задуматься и выяснить реяльно ли это полезная практика, а не маркетинговый трюк "Мы не навязываем Вам формат данных, Вы формируете удобный формат для нас через геттеры!"

2021-04-05 10:16 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Дополню еще тем что например в компоненте Select это оправданная операция, так как там может быть реально что угодно, а тут скорее опять хотите пропихать "потому что так везде", не обращая внимания на то надо это или нет.

2021-04-05 12:13 UTC, gizeasy commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Данный же все равно переголняются в формат но в момент получения их с бэка, если же нам надо отправить эти данные обратно на бэк то придется также мапить данные перед отправкой их обратно, в случае с геттерами имеется возможность держать в items все что необходимо для отправки обратно, без необходимости мапить данные обратно. Мы можем держать не посредственно пресет темы в items и в стейте темы, в случае с определенным типом items прилется мапить данные для того чтобы вытащить пресет и прокинуть его в компонент Theme.

в целом согласен с тем что можно и так с определенным типом items, но кажется что сильно много мапингов всяких возникает. 

получется так с геттерами мы можем хранить все что нужно в items и value будет такого же типа что удобно, человек думает в пределах одной сушньности и пишет гетеры от куда что взять.

{
  label,
  id,
  preset,
  ...// и все что будет завязанно на тему, моджет еще какиенибуть признаки темы, типа для плоховидящих 
}

и мы все данные берем с одного места и геттерами в конкретном случае забираем все что надо.
так же можем держать только ключи темы и через геттреы мапить данные и доставать все что нужно.

в случае с определенным типом 
мы имеем ряд функций мапингов которые по ключам нам выдадут который формат для компонента, пресет для темы и все что потребуется. Но и это-же можно сделать в варианте с геттерами. 

Кажется что оба варианта хороши, но вариант с геттерами немного гибче, но имеет более усложненное Api. 
Нужнали эта гибкость когда мы можем готовить нудженый формат вне компонента и отдавать сухие данные в компонент, скорее всего нет, спасибо убедил))

тогда получается в value указывать уникальный ключ темы и onChange будет отдавать тоже ключ темы?

2021-04-05 12:59 UTC, al-fyodorov commented on src/components/ThemeToggler/ThemeToggler.tsx
> +    getItemKey,
Давай пока оставим как есть с учетом что все работает, чтобы не блочить задачу, а потом по возможности проведете рефакторинг.

2021-04-05 13:00 UTC, al-fyodorov approved these changes

2021-04-15 10:55 UTC, merged