feat(Grid): added component Grid
gazprom-neft/consta-uikit pull request #956
Opened 2021-03-03 15:08 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-05 10:54 UTC, azhadanov approved these changes

2021-03-09 15:32 UTC, al-fyodorov requested changes
Замечаний по несколько раз описывать не стал, все что указано относится сразу к нескольким местам и нескольким файлам, при исправлении лучше сразу найти повторяющиеся проблемы и исправить.

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/GridItem/GridItem.tsx
> +export const gridItemPropCol = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const;
А почему нельзя обойтись чисто строками или чисто числами, какой смысл создавать константный тип `string | number` для указания значений от 1 до 12?

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/GridItem/GridItem.tsx
> +export const gridItemPropCol = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const;
Гибкости использования это не дает, даже если с сервера придет строка можно сделать `Number(value)` или наоборот `String(value)`, а выйгрыша кроме лишнего описания нет.

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/__stories__/Grid.mdx
> +| `as`           | `React.ElementType`           | 'div'        | HTML-тег, в виде которого этот компонент будет представлен в DOM                                    |
Судя по коду не обязательный как и `ref`, то что выставляется значение по умолчанию для внешнего пользователя не является обязательным.

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/__stories__/examples/GridExampleCols/GridExampleCols.css
> +.GridExampleCols {
Стили повторяются, точно нельзя сделать общий набор для примеров?

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/useBreakpoints.ts
> +type Breakpoint = { [key: string]: string | number | undefined };
```suggestion
type Breakpoint = Record<string, string | number | undefined>
```

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/useBreakpoints.ts
> +export type Breakpoints = { [key: string]: Breakpoint | undefined };
```suggestion
export type Breakpoints = Record<string, Breakpoint | undefined>
```

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/Grid/useBreakpoints.ts
> +  let cnProps = {};
Точно нельзя через reduce прогнать без мутирования объекта?

2021-03-09 15:32 UTC, al-fyodorov commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
>  import { ContextMenuExampleOutsideClick } from './examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick';
По хорошему это отдельлный коммит, так как правилась документация не относящаяся к функциональной возможности.

2021-03-09 18:55 UTC, kolebayev requested changes
Закинь пж под заголовок в доке вводный кусочек:

Модульная сетка — один из ключевых инструментов компановки содержимого на странице. Ее можно встраивать в любые блоки для управления потоком контента или построить на ней свой лэйаут.

2021-03-10 08:59 UTC, gizeasy commented on src/components/Grid/__stories__/examples/GridExampleCols/GridExampleCols.css
> +.GridExampleCols {
да потом кто-ни-буть стили поменяет в одном месте, оно по всем примерам раскатится, уж лучше пусть будет все по отдельности изалированно, друг от друга

2021-03-10 09:22 UTC, gizeasy commented on build.tsconfig.json
> +    "downlevelIteration": true
target убрал

2021-03-10 09:22 UTC, gizeasy commented on build.tsconfig.json
> +    "target": "ES2017",
убрал

2021-03-10 09:24 UTC, gizeasy commented on build.tsconfig.json
> +    "downlevelIteration": true
убрал `target`
показалось что без него не работало `downlevelIteration`, проверил все нормально

2021-03-10 09:26 UTC, gizeasy commented on src/components/Grid/GridItem/GridItem.tsx
> +export const gridItemPropCol = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const;
я думал разрешить только 1-12, так как по факту только они и поддерживают
но можно указать и любые, в дальнейшем думаем сделать поддержку любого числа

2021-03-10 10:31 UTC, gizeasy commented on src/components/Grid/useBreakpoints.ts
> +type Breakpoint = { [key: string]: string | number | undefined };
fix

2021-03-10 10:31 UTC, gizeasy commented on src/components/Grid/useBreakpoints.ts
> +export type Breakpoints = { [key: string]: Breakpoint | undefined };
fix

2021-03-10 10:31 UTC, gizeasy commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
>  import { ContextMenuExampleOutsideClick } from './examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick';
fix

2021-03-10 12:27 UTC, gizeasy commented on src/components/ContextMenu/__stories__/ContextMenu.mdx
>  import { ContextMenuExampleOutsideClick } from './examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick';
случайно вышло((
скоро вольем прку, после нее `mdx` будут форматироваться при коммите

думаю можно оставить так

2021-03-10 14:09 UTC, gizeasy commented
в отдельный комит вынес изменения конфигурации, добавил `postcss-mixin`, а то css файлик сильно большой был
комментарии поправил/ ответил

@al-fyodorov глянь

2021-03-11 10:24 UTC, al-fyodorov approved these changes

2021-03-11 11:59 UTC, kolebayev approved these changes

2021-03-11 12:12 UTC, merged