fix(TextField): fix cols and rows props
gazprom-neft/consta-uikit pull request #957
Opened 2021-03-05 13:32 UTC by azhadanov

issue -  #722

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [x] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-09 07:05 UTC, gizeasy requested changes

2021-03-09 07:05 UTC, gizeasy commented on src/components/TextField/TextField.tsx
> +    minRows: minRows || rows,
Напиши еще запрет на row и minRows
чтоб доступны были только если `type= textarea`
и чтоб нельзя было указать `minRows` и `maxRows` если указан `rows`

2021-03-09 07:52 UTC, gizeasy commented
@kolebayev посмотри на api, норм не норм?

2021-03-09 18:44 UTC, kolebayev commented
> @kolebayev посмотри на api, норм не норм?

для новых пропсов minRows, maxRows в таблицу свойств доки нужно добавить уточнение, что они про видимые строки:
Минимум/Максимум строк -> Минимум/Максимум ```видимых``` строк

2021-03-10 14:11 UTC, gizeasy commented on src/components/TextField/TextField.tsx
> +    minRows: minRows || rows,
решили делать в отдельной задаче

2021-03-10 14:12 UTC, merged