refactor(Tabs): removed casting to types and more fix
gazprom-neft/consta-uikit pull request #958
Opened 2021-03-05 14:02 UTC by gizeasy

* removed casting to types
* fixed css
* code optimizatio

issue -  #921

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-09 07:58 UTC, azhadanov approved these changes

2021-03-09 18:21 UTC, kolebayev commented
@gizeasy баг расчета ```--tabOffsetLeft``` при первом рендере. попался в хроме и фаерфоксе, но дело не в цсс, кажется
 
<img width="1791" alt="изображение" src="https://user-images.githubusercontent.com/24884175/110518079-b7580b00-811c-11eb-99d6-1dd42b98bd2d.png">

2021-03-09 18:23 UTC, kolebayev requested changes
Написал комент со скрином @gizeasy

2021-03-09 19:27 UTC, gizeasy commented
у меня не повторяется, но переписал этот кусок кода обратно

2021-03-09 20:11 UTC, gizeasy commented
> @gizeasy баг расчета `--tabOffsetLeft` при первом рендере. попался в хроме и фаерфоксе, но дело не в цсс, кажется
> 
> <img alt="изображение" width="1791" src="https://user-images.githubusercontent.com/24884175/110518079-b7580b00-811c-11eb-99d6-1dd42b98bd2d.png">

поковырял проблемы и кажется что это из-за того что css для каждой стори подлетает через JS
и у тебя в браузере он просто не успевает применится как все отрендорелось, от этого такое поведение, я пробывал у себя воспроизвести с этим же кодом не вышло, но вышло со старым когдом в фаерфоксе с открытими дев тулзами(через раз вылазит). Если компонент на реальном проекте будет, то такого бага не будет, так как css будет лежать в head и загрузиться в первую очередь. Можно конечно костыль воткнуть чтоб после рендера ждал 50мс и потом повторно вызывал функцию позиционирования линии, но кажется этот костыль лишний.

2021-03-10 14:26 UTC, kolebayev approved these changes

2021-03-10 14:27 UTC, merged