feat(ProgressSpin): add default spinning
gazprom-neft/consta-uikit pull request #971
Opened 2021-03-09 23:35 UTC by azhadanov

issue -  #914

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [x] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-10 08:39 UTC, gizeasy commented
тесты упали

2021-03-10 08:45 UTC, gizeasy requested changes

2021-03-10 14:21 UTC, gizeasy requested changes

2021-03-10 14:21 UTC, gizeasy commented on src/components/ProgressSpin/ProgressSpin.tsx
> +  progress?: number | undefined;
`undefined`  не обязательно писать если поставил `?`

2021-03-10 14:21 UTC, gizeasy commented on src/components/ProgressSpin/ProgressSpin.tsx
> +      className={cnProgressSpin({ spin: !progress }, [className])}
тут если progress = 0 то класс применится, а не надо

2021-03-17 08:17 UTC, al-fyodorov requested changes
@gizeasy, а вы коммиты объединяете только при объединении веток, или где-то есть требование чтобы в PR тоже лишних коммитов не было? Чтобы случайно все три коммита не ушли в master ветку после текущего PR.

2021-03-17 08:17 UTC, al-fyodorov commented on src/components/ProgressSpin/ProgressSpin.tsx
> +      className={cnProgressSpin({ spin: !progress && progress !== 0 }, [className])}
Достаточно проверки:

```ts
cnProgressSpin({ spin: progress === undefined }, [className])
```

Так как спиннер должен крутиться пока значение для прогресса не указано, а по типизации значение может быть только числом или не определенным.

2021-03-17 08:17 UTC, al-fyodorov commented on src/components/ProgressSpin/ProgressSpin.tsx
> +  const animatedProgress = typeof progress === 'number' ? progress : 50;
Кажется лучше написать какой-нибудь обобщенный type guard для проверки прогресса, например:

```ts
export const isNumber = (value: unknown): value is number => {
  return typeof value === 'number'
}
```

И можно будет использовать его для определения класса спинера:

```ts
cnProgressSpin({ spin: !isNumber(progress) }, [className])
```

2021-03-17 08:17 UTC, al-fyodorov commented on src/components/Timer/Timer.tsx
> +  progress?: number | undefined;
Необязательно указывать `undefined`.

2021-03-18 04:47 UTC, al-fyodorov approved these changes

2021-04-15 11:02 UTC, merged