feat(Collapse): create component, story, doc, tests
gazprom-neft/consta-uikit pull request #988
Opened 2021-03-16 14:42 UTC by azhadanov

issue -  #862

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [x] PR: прилинкованы затронутые issue и связанные PR
- [x] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [x] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-17 12:02 UTC, gizeasy requested changes

2021-03-17 12:02 UTC, gizeasy commented on src/components/Collapse/Collapse.css
> +      --children-up-space: var(--space-2xs);
--body-offset-up

2021-03-23 18:29 UTC, azhadanov commented on src/components/Collapse/Collapse.css
> +      .Collapse-Icon {
Там же через flex-direction: row-reverse, так что последний элемент всегда текст

2021-03-23 18:29 UTC, azhadanov commented on src/components/Collapse/Collapse.css
> +    .Collapse-Icon {
Мы вроде решили это пока не реализовывать

2021-03-30 08:39 UTC, kolebayev requested changes
<img width="329" alt="изображение" src="https://user-images.githubusercontent.com/24884175/112959832-7fa51780-914c-11eb-8e01-3c26e26f9584.png">

При выставлении view=secondary текст внутри коллапса (и любые другие вложенные компоненты) не должны подчиняться пропсам коллапсАйтема

2021-03-31 00:46 UTC, azhadanov commented
> <img alt="изображение" width="329" src="https://user-images.githubusercontent.com/24884175/112959832-7fa51780-914c-11eb-8e01-3c26e26f9584.png">
> 
> При выставлении view=secondary текст внутри коллапса (и любые другие вложенные компоненты) не должны подчиняться пропсам коллапсАйтема

Не особо понял, что нужно поправить тут.
На то, что передается внутрь Коллапса и сейчас не влияют пропсы самого Коллапса. Только от его размера зависят вертикальные отступы и ширина children`a, как было в макете.

2021-04-21 12:44 UTC, gizeasy approved these changes

2021-04-21 12:46 UTC, kolebayev approved these changes

2021-04-21 14:36 UTC, karpovfv-nedra approved these changes

2021-04-28 15:31 UTC, merged